CONTRIBUTING.md
CONTRIBUTORS.md
INSTALL.md
README.md

Update URLs and references in MD files …

Update URLs and references in MD files

---

CONTRIBUTING.md

Update CoC contact

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other-issue.md

Add split issue templates, for bug reports, feature requests, and others.

Update issue templates

---

.gitignore
dist/rpm/singularity-ce.spec.in
e2e/version/version.go
mconfig
mlocal/checks/project-post.chk
mlocal/frags/Makefile.stub
scripts/ci-rpm-build-test
scripts/make-dist.sh

Change tarball / package name to singularity-ce
- Fixes #19  …

Change tarball / package name to singularity-ce

---

CHANGELOG.md
INSTALL.md

Update the CHANGELOG and INSTALL docs for 3.8.0-rc.1
Merging to master and then branching, and ensuring that the install doc references the RC (with an explanatory note in the INSTALL.md), to make sure `singularity-ce` package name is visible.
- Based this …

Update CHANGELOG.md & INSTALL.md for 3.8.0-rc.1

---

cmd/internal/cli/build.go
internal/app/singularity/remote_login.go

Minor aesthetic fix to user prompts

---

.circleci/config.yml

Major overhaul of CI config using [reusable configuration](https://circleci.com/docs/2.0/reusing-config) and [pipeline parameters](https://circleci.com/docs/2.0/pipeline-variables/#pipeline-parameters-in-configuration). Collapse `rpmbuild` pipeline jobs into `build_and_test` pipeline. Minor consistency fixes.

CI Config Refactor

---

.circleci/config.yml

Bump Go to v1.15 in CI configuration.

Bump Go to 1.15

---

CHANGELOG.md
INSTALL.md

Update CHANGELOG/INSTALL.md for 3.8.0-rc.2 …

Update CHANGELOG/INSTALL.md for 3.8.0-rc.2

---

.github/RELEASE_PROCEDURE.md
CHANGELOG.md
INSTALL.md

Update changelog on master. Will merge with the deps and GHSA into release-3.8 in one go.
- Added …

3.8.0 changelog entries

---

internal/pkg/build/sources/oci_unpack.go

https://github.com/sylabs/singularity/pull/150

Pick #150 (Update restrictive permissions sandbox warning) to release-3.8

---

CHANGELOG.md
e2e/env/env.go
e2e/env/regressions.go
internal/pkg/runtime/engine/singularity/process_linux.go
internal/pkg/util/shell/escape.go
internal/pkg/util/shell/escape_test.go

https://github.com/sylabs/singularity/pull/153

Pick #153 (Allow env vars with literal $ via \\\$ in SINGULARITYENV_) to release 3.8

---

CHANGELOG.md
go.mod
internal/pkg/build/files/copy.go
internal/pkg/build/files/copy_test.go
internal/pkg/build/files/files.go
internal/pkg/build/files/files_test.go
internal/pkg/build/stage.go

https://github.com/sylabs/singularity/pull/162

Pick #162 (Handle absolute symlinks in multi-stage copy) to release-3.8

---

CONTRIBUTING.md
INSTALL.md
pkg/build/types/parser/deffile.go

General edits and removal of obsolete `GOPATH` location requirement in `INSTALL.md`
- Fixes #175 
- …

Update INSTALL.md for non-GOPATH build etc.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Ensure CoC is recognized by GitHub by placing it in expected file.
- Fixes #185  …

Ensure CoC is recognized by GitHub

---

.circleci/config.yml
INSTALL.md

Bump Go to latest patch release.

Bump Go to 1.16.7

---

.circleci/config.yml
INSTALL.md

Bump Go to latest patch release.

Bump Go to 1.16.7 (3.8)

---

CHANGELOG.md
CONTRIBUTORS.md
internal/pkg/build/files/copy.go
internal/pkg/build/files/copy_test.go
internal/pkg/build/sources/conveyorPacker_arch.go
internal/pkg/build/sources/conveyorPacker_debootstrap.go
internal/pkg/build/stage.go

Picking build related bug fixes:
- #197 
- #210 
- #255  …

Pick #197 #210 #255 to release-3.8

---

CHANGELOG.md
cmd/internal/cli/delete.go
cmd/internal/cli/remote.go
docs/remote.go
e2e/delete/delete.go
e2e/imgbuild/imgbuild.go
e2e/remote/remote.go
internal/app/singularity/remote_login.go
internal/pkg/build/sources/conveyorPacker_library.go
internal/pkg/remote/credential/login_handler.go
internal/pkg/remote/remote.go
internal/pkg/util/uri/uri.go
internal/pkg/util/uri/uri_test.go

Picking remote related bugfix PRs:
- #217 
- #216 
- #244 
- #249 
- #253  …

Cherry pick #217 #216 #244 #249 #253 to release 3.8

---

CHANGELOG.md
e2e/docker/docker.go
internal/pkg/build/sources/conveyorPacker_oci.go
internal/pkg/cgroups/cgroups_linux_test.go
internal/pkg/cgroups/example/cgroups-no-hugetlb.toml
internal/pkg/runtime/engine/singularity/process_linux.go
internal/pkg/util/shell/escape.go
internal/pkg/util/shell/escape_test.go
pkg/util/fs/proc/proc.go
pkg/util/fs/proc/proc_linux_test.go

Picking runtime related bugfixes:
- #199
- #209 
- #252  …

Cherry pick #199 #209 #252 to release-3.8

---

CHANGELOG.md
INSTALL.md

Markdown doc changes for 3.8.2 …

Markdown doc changes for 3.8.2

---

CHANGELOG.md
INSTALL.md

Ensure CHANGELOG and INSTALL changes are present on master branch. …

Merge v3.8.2 into master

---

CHANGELOG.md
INSTALL.md

3.8.3 changelog / install.md changes …

3.8.3 changelog / install.md changes

---

CHANGELOG.md
INSTALL.md

Merge 3.8.3 changelog / install.md changes to master …

Merge 3.8.3 changelog / install.md changes to master

---

e2e/imgbuild/imgbuild.go
internal/pkg/build/sources/conveyorPacker_busybox_test.go

e2e: Disable busybox bootstrap due to frequent dl failures (release-3.8)

---

internal/pkg/build/sources/conveyorPacker_busybox_test.go

Missed in the previous BusyBox disabling. …

Temporarily disable TestBusyBoxPacker

---

CHANGELOG.md
INSTALL.md

Markdown changes for 3.9.0-rc.3 …

Markdown changes for 3.9.0-rc.3

---

CHANGELOG.md

Changelog: correct 3.9.0-rc.3 date …

Changelog: correct 3.9.0-rc.3 date

---

CHANGELOG.md
internal/app/singularity/config_global_linux.go

Merge additional fix to release-3.9 for 3.9.0-rc.3

Merge additional fix to release-3.9 for 3.9.0-rc.3

---

.circleci/config.yml
INSTALL.md

Bump Go to 1.17.3

---

internal/app/singularity/push.go
internal/pkg/client/library/pull.go

Do not display progress bar when pull/push output is redirected
Closes #414

Omit progress bar on redirected output

---

CHANGELOG.md
INSTALL.md

Update CHANGELOG.md and README.md for 3.9.0 …

docs: Update CHANGELOG.md and README.md for 3.9.0

---

CHANGELOG.md
INSTALL.md

CHANGELOG entry / INSTALL changes for 3.9.1

---

CHANGELOG.md
INSTALL.md
examples/plugins/cli-plugin/go.sum
examples/plugins/config-plugin/go.sum
examples/plugins/log-plugin/go.sum
examples/plugins/ubuntu-userns-overlay-plugin/go.sum

Merge markdown and packaging changes made on release-3.9 branch into master. …

Merge release-3.9 changes from 3.9.1 release to master

---

CHANGELOG.md
makeit/gengodep

Fixed via a dependency update. These have been seen reported in the
community, so mention them here.

docs: Note mvdan.cc/sh related bug fixes in changelog

---

CHANGELOG.md
CONTRIBUTORS.md
cmd/internal/cli/sign.go

Clarify source of key index (3.9)

---

CHANGELOG.md
INSTALL.md
go.mod
go.sum

Address context timeout in single stream download.
- Fixes #516 
- Added myself as a contributor to …

deps: Update scs-library-client to 1.2.1

---

CHANGELOG.md
INSTALL.md
go.mod
go.sum

Address context timeout in single stream download.
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #516  …

deps: Update scs-library-client to 1.2.1 (3.9)

---

README.md
SUPPORT.md

Fix some links not working after changes to the Sylabs site.
Link to the community repository and mention the community calls in additional appropriate places. …

docs: Fix / tidy README/SUPPORT links

---

.circleci/config.yml
CHANGELOG.md
INSTALL.md

Bump versions for 3.9.7 release …

Bump versions for 3.9.7

---

CHANGELOG.md
INSTALL.md

Markdown changes for release 3.9.8 …

doc: Markdown changes for release 3.9.8

---

.circleci/config.yml
INSTALL.md

ci: bump to Go 1.18.1

---

internal/pkg/build/oci/oci.go

PR #727 was written while reviewing the Docker registry API v2 spec, in which it is stated a manifest HEAD request does include
`Docker-Content-Digest`.
I had not considered potential differences in the oci-distribution-spec. This makes it clear that `Docker-Content-Digest` is a SHOULD header, and lists it as a field clients should not depend on.
The `containers/image` `docker.GetDigest` function doesn't handle the lack of a `Docker-Content-Digest` header, so we should fall-through to the old `GetManifest` approach on error.
In practice I didn't find any registry that wasn't serving the Docker-Content-Digest header, but we should follow the oci-distribution-spec.
- Fixes #733
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and …

fix: Add fall-through for missing Docker-Content-Digest

---

CHANGELOG.md
INSTALL.md

Update changelog and install docs for 3.9.9 …

Update changelog and install docs for 3.9.9

---

CHANGELOG.md
INSTALL.md

Keep changelog / install doc on master up-to-date for latest stable release info.
- Added myself as …

doc: Merge release-3.9 markdown changes to master

---

LICENSE.md
e2e/key/key.go
pkg/sypgp/sypgp.go

Missing in error on #757 
- Fixes #758  …

fix: Add Apptainer copyright lines for #757

---

go.mod
go.sum
internal/app/singularity/push.go
internal/pkg/client/progress.go

Move everything to current v7
- Fixes #763  …

deps: Rationalize vbauerster/mpb versioned dependencies

---

CHANGELOG.md

Remove some 3.10 entries that were backported, and are listed below in
3.9.x entries.
Correct changes vs new features split. …

docs: Tidy CHANGELOG.md

---

CHANGELOG.md
INSTALL.md

docs: Markdown changes for 3.10.0-rc.1 release candidate …

docs: Markdown changes for 3.10.0-rc.1 release candidate

---

CHANGELOG.md
INSTALL.md

docs: CHANGELOG/INSTALL bump for 3.10.0-rc.2 …

docs: CHANGELOG/INSTALL bump for 3.10.0-rc.2

---

CHANGELOG.md

Add CHANGELOG entries for #784 & #864 …

Add CHANGELOG entries for #784 & #864

---

CHANGELOG.md
e2e/imgbuild/regressions.go
e2e/testdata/regressions/issue_4967.def
e2e/testdata/sshfs.def
internal/pkg/build/build.go
internal/pkg/build/stage.go
pkg/network/network_linux_test.go

Cherry-pick:
- https://github.com/sylabs/singularity/pull/872
- https://github.com/sylabs/singularity/pull/900
- https://github.com/sylabs/singularity/pull/901 …

Pick e2e changes from main to 3.10.1

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTORS.md
INSTALL.md
cmd/internal/cli/cgroups.go

Cherry picks:
- https://github.com/sylabs/singularity/pull/865
- https://github.com/sylabs/singularity/pull/906
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.m …

Pick build changes from main to 3.10.1

---

.circleci/config.yml
CHANGELOG.md

ci: add almalinux 9 package build (release-3.10) …

ci: add almalinux 9 package build (release-3.10)

---

.circleci/config.yml
CHANGELOG.md

ci: add almalinux 9 package build …

ci: add almalinux 9 package build

---

CHANGELOG.md
internal/pkg/build/sources/conveyorPacker_oci.go

Pick runscript fix (simplified version) from #918 
Pick changelog entry from #915  …

Pick runscript fix #918 to release-3.10

---

CHANGELOG.md
INSTALL.md

Update CHANGELOG.md / INSTALL.md for 3.10.2 …

CHANGELOG / INSTALL for 3.10.2

---

CHANGELOG.md
INSTALL.md

Merge release-3.10 changes to main to update markdown instructions, changelog on main. …

Merge release-3.10 changes to main

---

go.mod
go.sum
internal/app/singularity/push.go
internal/pkg/client/progress.go

Bump `github.com/vbauerster/mpb` to latest major version.

Bump github.com/vbauerster/mpb to v8 (master)

---

go.mod
go.sum
internal/app/singularity/push.go
internal/pkg/client/progress.go

Bump `github.com/vbauerster/mpb` to latest major version.

Bump github.com/vbauerster/mpb to v8 (release-3.10)

---

.circleci/config.yml
INSTALL.md

chore: bump Go to 1.19.2 (release-3.10)

---

.circleci/config.yml
INSTALL.md

chore: bump Go to 1.19.2 (main)

---

cmd/internal/cli/action_flags.go
cmd/internal/cli/actions.go
cmd/internal/cli/build_linux.go
cmd/internal/cli/cgroups.go
cmd/internal/cli/cgroups_test.go
cmd/internal/cli/inspect.go
cmd/internal/cli/instance_start_linux.go
cmd/internal/cli/run_help_linux.go
cmd/internal/cli/startvm.go
internal/pkg/runtime/engine/singularity/process_linux.go
internal/pkg/runtime/launch/launcher_linux.go
internal/pkg/runtime/launch/options.go
internal/pkg/util/shell/interpreter/interpreter.go
internal/pkg/util/shell/interpreter/interpreter_test.go

This PR removes the execStarter code from the CLI layer. execStarter was responsible for assembling CLI flags/options into an engine configuration, and calling the Singularity runtime's starter executable to launch the container with that configuration.
execStarter has been replaced with a Launcher struct, which is passed configuration via functional options, and implements an Exec function that performs container launch.
The intention of this PR is to remove the direct coupling of CLI and starter launch, so that next we can add a second OCI runtime launch method, with the CLI calling either the Singularity starter, or the OCI launch as appropriate.
The functional options / Launcher configuration are currently a naive translation of the previous direct use of CLI flag variables in …

refactor: move execStarter functionality out of CLI layer

---

cmd/internal/cli/actions.go
internal/pkg/runtime/launcher/launcher.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/launcher_linux_test.go
internal/pkg/runtime/launcher/options.go
internal/pkg/runtime/launcher/util.go

Refactor the existing code so that:
* The internal/pkg/runtime/launcher package contains common option handling, utility functions, and a Launcher interface.
* There is a launcher.native package containing the existing launch code for the native singularity runtime.
Add placeholder OCI launcher
* Accepts no options, fails if options provided.
* Implements an Exec method which does nothing.
Fixes #1021 …

launcher: refactor and add OCI placeholder launcher

---

CHANGELOG.md
cmd/internal/cli/pull.go
docs/content.go
docs/remote.go
e2e/pull/pull.go
e2e/pull/regressions.go
e2e/remote/remote.go
e2e/verify/verify.go
etc/remote.yaml
internal/app/singularity/push.go
internal/pkg/build/remotebuilder/remotebuilder_test.go
internal/pkg/build/sources/conveyorPacker_library_test.go
internal/pkg/remote/endpoint/service.go
internal/pkg/remote/remote_test.go

This reverts commit 5408fa04d014e7598ada16d5b2e9c2e1d6c30518.

Revert "Point at sycloud.io SCS endpoints"

---

CHANGELOG.md
cmd/internal/cli/pull.go
docs/content.go
docs/remote.go
e2e/pull/pull.go
e2e/pull/regressions.go
e2e/remote/remote.go
e2e/verify/verify.go
etc/remote.yaml
internal/app/singularity/push.go
internal/pkg/build/remotebuilder/remotebuilder_test.go
internal/pkg/build/sources/conveyorPacker_library_test.go
internal/pkg/remote/endpoint/service.go
internal/pkg/remote/remote_test.go

This reverts commit 9ff96958eba1bf24e0bebb2cf456d3111d2cbb7a.

Revert "Point at sycloud.io SCS endpoints" (release-3.10)

---

.circleci/config.yml
CHANGELOG.md
INSTALL.md

Bump go to 1.19.3
Update docs for 3.10.4 …

chore: release 3.10.4 prep

---

.circleci/config.yml

See https://discuss.circleci.com/t/heroku-gpg-issues-in-ubuntu-images/43834/1 …

ci: workaround for heroku GPG key issue

---

.circleci/config.yml

See https://discuss.circleci.com/t/heroku-gpg-issues-in-ubuntu-images/43834/1 …

ci: workaround for heroku GPG key issue (release-3.10)

---

INSTALL.md
debian/control

If `crun` is not available, require `runc`.
- Fixes #1144  …

pkg: fix Ubuntu 18.04 deb build

---

CHANGELOG.md

Now that sufficient functionality is in place for `--oci` mode, add a CHANGELOG entry for the current state. …

doc: Add CHANGELOG entry for `--oci`

---

e2e/imgbuild/imgbuild.go

Check that %test shebang is honored at build and runtime, and %runscript shebang honored.
- Fixes #869 
- …

e2e: Test custom %test / %runscript shebang

---

CHANGELOG.md
e2e/cgroups/cgroups.go
e2e/suite.go
internal/pkg/runtime/launcher/native/launcher_linux.go

Start an instance with a cgroup by default, where the calling user is root, or cgroups v2 unified mode with systemd as manager is available.
This allows `singularity instance stats` to work by default in these circumstances.
The PR also includes a fix for a limitation of non-group instances with cgroups that is more broadly exposed by the above change:
When joining a non-root instance using cgroups, we need to move our instance joining process into the instance cgroup.
Previously we did this directly. However, it is common for a CLI instance join to be started under a session scope cgroup that is root owned, and not delegated. We cannot move the CLI process into the instance cgroup directly from here, due to the requirements detailed in: …

instance: start with cgroup if possible, to enable stats

---

CHANGELOG.md
e2e/gpu/gpu.go
internal/pkg/runtime/launcher/oci/launcher_linux.go
internal/pkg/runtime/launcher/oci/mounts_linux.go

oci: support legacy --nv bind mode
- Fixes #1033 …

feat: oci: support legacy --nv bind mode

---

internal/pkg/build/oci/oci.go
pkg/ocibundle/native/bundle_linux.go

When the cache is enabled, and `--oci` mode is used, extract the image directly from the cache oci-layout, rather than copying into a temporary oci-layout first.
In addition, within the transparent caching functions, check if an image manifest is present before performing a copy into the cache. Although the copy is effectively a no-op if the image is present, this avoids some overhead.
- Fixes #1221 …

oci: Use cache more efficiently for --oci mode

---

CHANGELOG.md
INSTALL.md

Update INSTALL.md for 3.11.0 release
Update CHANGELOG.md for 3.11.0 release …

docs: 3.11.0 changes in MD files

---

e2e/oci/oci.go

On EL7/8 ARM64, the transition of state for a container can be slow enough that it's not seen if the state check is run immediately after a KILL.
If an immediate check doesn't give the required state, wait 1s and check again.
- Fixes #1437
- Based this PR against …

e2e: Retry OCI state check after 1s

---

e2e/oci/oci.go

Pick #1438
On EL7/8 ARM64, the transition of state for a container can be slow enough that it's not seen if the state check is run immediately after a KILL.
If an immediate check doesn't give the required state, wait 1s and check again.
- Fixes #1437 
- Based …

e2e: Retry OCI state check after 1s (release-3.11)

---

dist/rpm/singularity-ce.spec.in

Make the %files section match with the change in #1452.
Apologies that I missed this in review.
- Fixes #1454 
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md …

rpm: fix: Update %files section for statedir change

---

.circleci/config.yml
CHANGELOG.md
INSTALL.md

Documentation and CI Go version bump. …

Merge v3.11.1 release changes to main

---

internal/pkg/runtime/launcher/oci/launcher_linux.go

If we are running under cgroups v1 or with the cgroupfs manager (i.e. not systemd as cgroup manager), do not attempt to enter a cgroup at startup with crun. We cannot create a cgroup unprivileged in this situation.
Under cgroups v1, crun will not perform the cgroups manipulation that leads to the issue we worked around in #1539. Any other issue with the cgroup that we are in at launch cannot be rectified, either.
- Fixes #1569 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTIN …

fix: oci: Don't create cgroup for crun on v1 / cgroupfs

---

CONTRIBUTORS.md
INSTALL.md

As explained in the image, minimal docker images of either centos or ubuntu do not have `git` or `wget` preinstalled, both of which are later used for the download of this repo and go accordingly.
Feel free to quash the commits, I just saw that I have to add myself to the Contributors :<
- Fixes #1572
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make …

Update the INSTALL.md to be compatible with minimal docker images

---

RELEASE_PROCEDURE.md

Minor fixes to `RELEASE_PROCEDURE.md` encountered in the course of working on release 3.11.2

minor fixes in RELEASE_PROCEDURE.md

---

CHANGELOG.md
INSTALL.md

Merging latest from `release-3.11` back into `main` following 3.11.2 release.

merging 3.11.2 back into main

---

RELEASE_PROCEDURE.md

Pick #1603 
Minor fixes to `RELEASE_PROCEDURE.md` encountered in the course of working on release 3.11.2

minor fixes in RELEASE_PROCEDURE.md (release-3.11)

---

README.md
SUPPORT.md

We are moving to GitHub Discussions as the primary location for usage, feature, and roadmap discussion.
Promote it via updated links. The singularityce-community repo, which is managed via HackMD, will have redirection notices added.
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing. …

docs: Promote GitHub Discussions, retire HackMD

---

.circleci/config.yml
CHANGELOG.md
INSTALL.md
RELEASE_PROCEDURE.md

Merging latest from `release-3.11` back into `main` following 3.11.3 release.

merge 3.11.3 changes back into main

---

mlocal/checks/project-post.chk

Fixes #1797 
As it's a small bugfix in my opinion (non-blocking bug), following the CONTRIBUTING.md directives:
* No changes done in the CHANGELOG.md
* I don't PR toward release branch

Fix bad shell operator

---

CHANGELOG.md
mlocal/checks/project-post.chk

Fix bad shell operator (release-3.11)

---

CHANGELOG.md
INSTALL.md

Sync CHANGELOG.md and INSTALL.md

docs: merge v3.11.4 onto main branch

---

e2e/actions/actions.go

This PR splits off some of the e2e tests that previously lived under actionExec() (e2e/actions/actions.go) to a separate function, actionExecMultiProfile(). As the names hopefully make clear, the difference is in which set of run profiles the tests are run under: actionExec() runs its tests only under `e2e.UserProfile`; the new actionExecMultiProfile() runs its tests under `e2e.UserProfile`, `e2e.RootProfile`, and `e2e.FakerootProfile`.
- Fixes #1848

split off selected tests from actionExec() to actionExecMultiProfile()

---

e2e/actions/oci.go

Instead of counting the mounts, compare the full mount table before and after execution. The assert.Equal will produce a nice diff if they don't match, easing troubleshooting.
Cherry-picked from the WIP #1838 to simplify that ongoing PR.
- Based this PR against …

e2e: In actionOCiOverlayTeardown, show mount table differences

---

internal/pkg/runtime/launcher/oci/launcher_linux.go
pkg/ocibundle/native/bundle_linux.go

In Singularity's native mode, we assemble the runtime representation of the container's rootfs under a tmpfs mounted on buildcfg.SESSIONDIR. The pristine rootfs, whether from a SIF file or an OCI source image extracted to a directory, is mounted into the tmpfs before other overlays, customised files, host mounts etc. are layered over it.
The location of buildcfg.SESSIONDIR is set when SingularityCE is compiled. It is documented that it needs to be on a local filesystem. Using a tmpfs mount over a local fs SESSIONDIR avoids potential issues with mounts over network file systems etc. The OCI mode is currently vulnerable to issues as it creates the runtime bundle on TMPDIR.
Also, prior to this PR, our code assumes that an OCI container rootfs sits directly in the runtime bundle, and can be …

oci: create runtime bundle within buildcfg.SESSIONDIR tmpfs

---

internal/pkg/client/oci/auth.go

Oversight in review / rebase to merge #1917  …

fix: Remove Warningf of credential in oci-sif docker:// push

---

CHANGELOG.md
e2e/key/key.go
internal/pkg/sypgp/sypgp.go
internal/pkg/sypgp/sypgp_test.go

Improves the clarity of the output of `singularity key list`.

improve `key list` output

---

internal/pkg/runtime/launcher/oci/mounts_linux.go

Also capitalize Nvidia -> NVIDIA
- Fixes #1963 …

fix: Correct ROCm -> NVIDIA in error message

---

CHANGELOG.md

* Grouping OCI changes together, so it is easier to get an overview of of OCI-mode or ignore it.
* Removal of explanation of existing flags that have been added to OCI mode, to save space. Their function is already known / documented.
* Grouping other changes by category, to make it easier for admins / users to identify things of interest. …

docs: revise changelog for upcoming 4.0.0-rc.1

---

internal/pkg/runtime/launcher/oci/launcher_linux.go

With cgroups v1 it isn't possible for rootless users to manage cgroups via systemd or cgroupfs.
In this situation, crun ignores the `--systemd-cgroup` flag, but `runc` will fail if it is set.
Don't set `--systemd-cgroup` for rootless with cgroups v1.
- Fixes #2057 …

oci: don't request --systemd-cgroup in rootless v1

---

e2e/verify/verify.go

EL7 doesn't support the algorithms we need for the OCSPResponder in our Verify tests.
We already skip the OCSP tests if the responder isn't available.
We need to skip the responder startup on EL7. Use kernel < 3.11 as a proxy for EL7.
- Fixes #2071
- Based this …

fix: e2e: skip OCSPResponder start on EL7

---

e2e/security/oci.go

When we are checking for capabilities in the test, we need to accommodate systems that don't have CAP_AUDIT_READ, e.g. EL7.
CAP_AUDIT_READ is in the default set for an OCI container, but is not present on EL7. Perform a bitwise and with the system full capset for the values we are checking.
- Fixes #2072
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make …

fix: e2e: handle max cap in OCI capabilities tests

---

.golangci.yml

Adds comments to explain rule exclusions recently added in .golangci.yml

lint: add explanatory comments for exclusions in .golangci.yml

---

.github/dependabot.yml
CHANGELOG.md
INSTALL.md

Add dependabot coverage of release-4.0 branch
Update markdown docs for the release candidate.
- Added myself …

chore: prepare docs, dependabot for 4.0.0-rc.1

---

internal/pkg/build/sources/conveyorPacker_zypper.go

Some zypper builds install packages that attempt to modify files in locations that, in fakeroot mode, are bind-mapped into the user namespace. (An example is `filesystem-15.0-11.3.2.x86_64`, which attempts to execute a `chown` on `/dev/cpio`.) Because the running of `zypper` itself, when building in fakeroot mode, is done as a regular user inside the namespace, it lacks the permissions to perform operations of this sort on files in privileged locations.
RPM provides a way to suppress this kind of behavior, by specifying - as an RPM macro - the set of directories that are "network mounts" (per RPM's terminology). Operations that RPM packages attempt to perform on things inside these directories in the course of their installation (or uninstallation) will be suppressed. The name of the …

add custom .rpmmacros creation for fakeroot zypper builds

---

internal/pkg/build/sources/conveyorPacker_zypper.go

Pick #2107 
Some zypper builds install packages that attempt to modify files in locations that, in fakeroot mode, are bind-mapped into the user namespace. (An example is `filesystem-15.0-11.3.2.x86_64`, which attempts to execute a `chown` on `/dev/cpio`.) Because the running of `zypper` itself, when building in fakeroot mode, is done as a regular user inside the namespace, it lacks the permissions to perform operations of this sort on files in privileged locations.
RPM provides a way to suppress this kind of behavior, by specifying - as an RPM macro - the set of directories that are "network mounts" (per RPM's terminology). Operations that RPM packages attempt to perform on things inside these directories in the course of their installation (or uninstallation) will be suppressed. The name …

fix: add prepareFakerootRpmMacros() (release-4.0)

---

internal/pkg/build/sources/conveyorPacker_zypper.go

This PR improves the code introduced in PR #2107 in terms of the teardown of the temporary dirs and mounts created in the course of setting up a custom `~/.rpmmacros` for fakeroot-mode zypper-based builds.

zypper: improve .rpmmacros cleanup

---

examples/lima/README.md
examples/lima/singularity-ce.yml

Add a VM template for Lima, which provides a nice way to get SingularityCE in a Linux VM on both Intel and ARM Macs.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUT …

examples: Add lima VM template

---

CHANGELOG.md
INSTALL.md

Merges changes from 4.0.0-rc.2 release (CHANGELOG.md, INSTALL.md) back into `main` branch.

merging chgs from 4.0.0-rc.2 back into main (CHANGELOG.md, INSTALL.md)

---

e2e/remote/remote.go

The e2e test "TestE2E/SEQ/REMOTE/use_exclusive" (`remoteUseExclusive()`, e2e/remote/remote.go:563) depends on there not being a remote.yaml in the root user's homedir prior to the test being run.
This PR adds code that moves existing remote.yaml in users' homedir aside for the duration of this test, and moves them back into place as part of the test's cleanup.

e2e: move aside existing remote.yaml files in remoteUseExclusive()

---

e2e/remote/remote.go

Pick #2230 
The e2e test "TestE2E/SEQ/REMOTE/use_exclusive" (`remoteUseExclusive()`, e2e/remote/remote.go:563) depends on there not being a remote.yaml in the root user's homedir prior to the test being run.
This PR adds code that moves existing remote.yaml in users' homedir aside for the duration of this test, and moves them back into place as part of the test's cleanup.

e2e: move aside existing remote.yaml files in remoteUseExclusive() (release-4.0)

---

cmd/internal/cli/build.go
cmd/internal/cli/build_linux.go
cmd/internal/cli/singularity.go
e2e/actions/actions.go
e2e/docker/docker.go
e2e/imgbuild/imgbuild.go
e2e/instance/instance.go
internal/pkg/build/sources/conveyorPacker_oci.go
internal/pkg/build/sources/conveyorPacker_oras.go
internal/pkg/client/oci/nativesif.go
pkg/build/types/bundle.go

Add support for the `--authfile` flag for (non-remote) `build` command.

build: add support for --authfile flag

---

internal/pkg/client/library/pull.go
internal/pkg/client/library/push.go
internal/pkg/client/net/pull.go
internal/pkg/client/ocisif/ocisif.go
internal/pkg/client/oras/oras.go
internal/pkg/client/oras/pull.go
internal/pkg/client/progress/progress.go
internal/pkg/client/progress/progress_roundtripper.go
internal/pkg/client/progress/progress_test.go
internal/pkg/client/shub/pull.go
internal/pkg/ociimage/fetch.go

Implements progress bars for:
- ORAS push/pull
- Library OCI-SIF push/pull
- Fixes #2212

add progress-bars for oras & ocisif operations

---

internal/pkg/client/library/pull.go
internal/pkg/client/library/push.go
internal/pkg/client/net/pull.go
internal/pkg/client/ocisif/ocisif.go
internal/pkg/client/oras/oras.go
internal/pkg/client/oras/pull.go
internal/pkg/client/progress/progress.go
internal/pkg/client/progress/progress_roundtripper.go
internal/pkg/client/progress/progress_test.go
internal/pkg/client/shub/pull.go
internal/pkg/ociimage/fetch.go

Pick #2252 
Implements progress bars for:
- ORAS push/pull
- Library OCI-SIF push/pull
- Fixes #2212

add progress-bars for oras & ocisif operations (release-4.0)

---

.circleci/config.yml
INSTALL.md

Bump Go in CI and INSTALL.md to current release. …

chore: bump Go to 1.21.3

---

.circleci/config.yml
INSTALL.md

Bump Go in CI and INSTALL.md to current release. …

chore: bump Go to 1.21.3 (release-4.0)

---

CHANGELOG.md
INSTALL.md

Update INSTALL, README.md for 4.0.1 bugfix release. …

chore(docs): Prepare for 4.0.1 release

---

CHANGELOG.md
INSTALL.md

Merge 4.0.1 docs changes to main. …

chore: merge 4.0.1 docs changes to main

---

.circleci/config.yml
.golangci.yml
internal/pkg/remote/credential/login_handler.go
internal/pkg/remote/remote_test.go
internal/pkg/security/security_test.go
internal/pkg/sypgp/sypgp.go
internal/pkg/util/fs/overlay/overlay_linux.go
pkg/build/types/parser/deffile.go
pkg/build/types/parser/deffile_test.go
pkg/util/fs/proc/proc_linux_test.go

Misc. linter fixes for `golangci-lint` v1.55.1

linter fixes for golangci-lint 1.55.1

---

go.mod
internal/pkg/build/buildkit/daemon/executor.go

Drop explicit usage of Open Telemetry. I don't believe what we have is of use if we aren't likely to be collecting / exporting events and data. …

buildkit: drop otel

---

CONTRIBUTORS.md
LICENSE_DEPENDENCIES.md
e2e/actions/oci.go
go.mod
go.sum
internal/pkg/runtime/launcher/oci/cdi_linux.go
internal/pkg/runtime/launcher/oci/cdi_linux_test.go
internal/pkg/runtime/launcher/oci/launcher_linux.go

Pick https://github.com/sylabs/singularity/pull/2309 …

Update container-device-interface to v0.6.2 (release-4.0)

---

.markdownlint.yml
e2e/README.md
e2e/internal/e2e/private_repo.go
e2e/internal/e2e/profile.go
e2e/suite.go

Improve the documentation for the e2e testing suite: its structure, its initialization, the various helpers available, etc.
- Fixes #861

document e2e helpers, best practices, etc.

---

.circleci/config.yml

Update the version of node used in CircleCI from 18 to 20.

update node ver. in CircleCI: 18 -> 20

---

.circleci/config.yml

Update the version of node used in CircleCI from 18 to 20.

update node ver.: 18 -> 20 (release-4.0)

---

LICENSE_DEPENDENCIES.md
go.mod
go.sum

Allows removal of replace directive pinning us to a specific commit after buildkit additions.
oras-go replace is also removed here as it's not used. We no longer import oras-go. …

deps: bump docker/docker to v25.0.0-beta.1

---

internal/pkg/build/buildkit/daemon/executor.go

In our `singularity-buildkitd` executor code, we are incorporating the pattern from the upstream `buildkitd`, where `RUN` steps are intended to be executed with `runc` using the `--keep` flag. This leaves the container running after the target process has completed. The container must then be shutdown separately with a `runc delete` if it is not inside of a userns.
Use of `--keep` and a separate delete was added to upstream `buildkitd` to allow per-step resource tracking, this is not something we really need for our provided ephemeral `singularity-buildkitd`.
Different to upstream `buildkitd`, our executor code may user `crun` instead of `runc.` `crun` doesn't have the `--keep` flag, so logic was added to avoid using it. However, there was a logic error in the setting of the `isRunc` …

fix: singularity-buildkitd: Don't use --keep for RUN steps

---

.circleci/config.yml
CHANGELOG.md
INSTALL.md

Squashed merge from 4.0.3 -> main, which is essentially the content of #2516

Merge release-4.0 changes for v4.0.3 to master

---

CHANGELOG.md
pkg/util/singularityconf/config.go

This directive was being used, but was not in the template.
- Fixes #2458  …

singularityconf: add tmp sandbox directive to template

---

CHANGELOG.md
pkg/util/singularityconf/config.go

This directive was being used, but was not in the template.
- Fixes #2458  …

singularityconf: add tmp sandbox directive to template (release-4.1)

---

.circleci/config.yml

Will be EOL before SingularityCE 4.2 is released.
- Fixes #2887 …

ci: drop CentOS 7 build

---

INSTALL.md

Will be EOL and not supported for SingularityCE 4.2.
- Fixes #2891 …

doc: Remove CentOS 7 content from INSTALL.md

---

CHANGELOG.md
CONTRIBUTORS.md
cmd/internal/cli/action_flags.go
cmd/internal/cli/actions.go
e2e/env/env.go
e2e/env/oci.go
internal/pkg/runtime/launcher/native/launcher_linux.go
internal/pkg/runtime/launcher/oci/process_linux.go
internal/pkg/runtime/launcher/options.go
internal/pkg/util/env/env.go

and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
- Fixes #2744 …

Allows using multiple --env-file flags.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other-issue.md

Make it clearer that users need to replicate issues on the latest release, and should check latest documentation before requesting features.
We continue to have a very large number of issues reported against old versions / from following outdated documentation, that we do not support.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible …

docs: Revise issue templates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other-issue.md

Whoops! PR preview wraps markdown differently to issues. …

docs: unwrap issue templates

---

e2e/pull/pull.go
internal/pkg/ocisif/imagewriter.go

When we pull an OCI-SIF with `--keep-layers` (so that layers are not squashed), ensure that we can pull an image that contains an overlay.
This requires us to check whether the last layer is ext3. If it is, it is an overlay and we write it to the OCI-SIF as-is.
- Fixes #3136 …

oci: pull OCI-SIF with overlay with --keep-layers

---

.circleci/config.yml
.github/dependabot.yml
CHANGELOG.md
INSTALL.md

Merge release-4.2 changes for 4.2.0-rc.1 onto main branch.

chore: merge release-4.2 / RC changes onto main

---

.github/dependabot.yml
CHANGELOG.md
INSTALL.md

* Drop release-4.2 dependabot config (will be merged onto main)
* Bring across post-RC 4.1.5 changelog entries.
* Update changelog and install docs for 4.2.0 …

chore: prepare 4.2.0 release

---

.github/dependabot.yml
CHANGELOG.md
INSTALL.md

Merge release-4.2.0 at v4.2.0 onto main.
Updates MD files on main. …

chore: merge release-4.2 branch at v4.2.0 onto main

---

CHANGELOG.md
cmd/singularity-buildkitd/main.go
internal/pkg/build/buildkit/client/client.go
internal/pkg/build/buildkit/daemon/daemon.go
internal/pkg/runtime/launcher/oci/oci_linux.go

Pick:
- #3402 
- #3407 
- #3411

Pick OCI-mode XDG var handling improvements (release-4.2)

---

INSTALL.md

Rebase from original by lquenti #3459  …

docs: note how to update submodules after simple clone 

---

CHANGELOG.md
internal/pkg/runtime/engine/singularity/container_linux.go

Pick of https://github.com/apptainer/apptainer/pull/2547

skip mounting inaccessible mount points with `mount hostfs = yes`

---

CHANGELOG.md
examples/fedora-amd64/Singularity
examples/fedora-arm64/Singularity
internal/pkg/build/conveyorPacker.go
internal/pkg/build/sources/conveyorPacker_yum_test.go

Modified pick of https://github.com/apptainer/apptainer/pull/2565

Add a dnf definition file bootstrap option as an alias to yum

---

e2e/nested/nested.go
e2e/testdata/Dockerfile.nested
e2e/testdata/nested.def

Basic e2e tests for singularity nested inside itself.
Also tidy up some things on the previous docker / podman testing.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRI …

e2e: nested singularity-in-singularity tests

---

examples/nested/Dockerfile
examples/nested/Singularity

Small tweaks from work-up of the documentation, missed in last commit.
Add timezone files and force unpriv mode.

doc: nested examples tweaks

---

pkg/sylog/sylog.go
pkg/sylog/sylog_dummy.go

sylog: allow writer to be set
