sylabs/singularity

- LICENSE.md
- cmd/starter/c/starter.c
- internal/pkg/util/starter/starter.go
This is an inelegant, but effective work around for #7 that will prevent GC cycle triggered errors until the effects of closing fds in container startup can be further considered for possible re-work.
Allow debug of Go runtime issues in starter
- Do not clear GOGC and GODEBUG in starter C init
- Log FD_CLOEXEC on fds
Disable GC for the starter
- Prevent a GC cycle firing after fds have been closed, which can cause
a netpoll panic.
Co-authored-by: Adam Hughes <tri-adam@users.noreply.github.com>
- Fixes #7 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the …
> Disable Go runtime GC for starter process

- INSTALL.md
- dist/rpm/singularity-ce.spec.in
- scripts/make-dist.sh
Extracting the `make dist` tarball will now place the source code in a dir `singularity-<version>` rather than just `singularity` to avoid confusion and extracting over an older source tree.
Fixes: #15 …
> Add version to extracted dir from tarball

- .circleci/config.yml
Update `ubuntu-machine` image used in CI to latest ([ref](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images)).
> Update Ubuntu CI Image to Latest

- .circleci/config.yml
- e2e/internal/e2e/priv_linux.go
- internal/pkg/test/privilege_linux.go
Use Go 1.16 in CI. Replace `syscall` package usage for `Setresuid()`/`Setresgid()` in test helpers with `unix` package. As of Go 1.16, the `syscall` functions now include wrappers that ensure all OSThreads mirror a common system call (related discussion [here](https://github.com/golang/go/issues/1435)). This is not compatible with the approach we have taken in our test cases. The `unix` package retains the original semantics, so we use that.
> Bump Go to 1.16

- .circleci/config.yml
Rename `check-stretch` to `check-debian`. Update `golang:stretch` to `golang:buster`, the most recent stable version of Debian.
> Use Latest Debian in CI

- .circleci/config.yml
We are currently using Xcode 10.2.0, which is no longer a supported version ([ref](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions)). Update Xcode to latest supported version.
> Use Latest Xcode in CI

- .circleci/config.yml
Support for `GOPATH` mode will be dropped in Go 1.17 ([ref](https://blog.golang.org/go116-module-changes#TOC_2.)). Modify `check-darwin` job to exercise building outside `GOPATH`. Drop unnecessary `working_directory` directive from `ubuntu-machine` executor for consistency.
> Use Default Working Directory in CI Config

- .circleci/config.yml
- INSTALL.md
Use latest Go patch release in CI config and install documentation.
> Bump Go to 1.16.5

- pkg/image/sif_test.go
Fix issue with `TestSIFInitializer` unit test where `img.Writable` was inconsistent with the `mode` passed to `os.OpenFile`, causing a false negative error for the `NoPartitionSIF` test.
Leverage subtests to improve readability of unit test results. Simplify error check logic.
> Fix TestSIFInitializer Unit Test

- e2e/internal/e2e/dockerhub_auth.go
- e2e/pull/pull.go
- go.mod
- go.sum
- internal/pkg/client/oras/oras.go
- internal/pkg/remote/credential/login_handler.go
The authors of `github.com/oras-project/oras-go` have changed their import path ["just for fun"](https://github.com/oras-project/oras-go/pull/7) as of v0.4.0.
It doesn't appear as if Dependabot has tracked the new version (presumably due to the new path.)
Update the import paths and dependency version to reflect.
> build(deps): update oras-go module name

- e2e/imgbuild/regressions.go
- e2e/instance/instance.go
- e2e/oci/oci.go
- go.mod
- go.sum
- pkg/util/crypt/crypt_dev.go
The `github.com/satori/go.uuid` module is no longer maintained (see #3 and https://github.com/sylabs/sif/issues/7 for more context). We cannot fully replace this module until a stable release of `github.com/sylabs/sif/v2` is available, since the `github.com/sylabs/sif` API requires it. In the interim, replace all other uses of the unmaintained module.
> Partially Replace UUID Module

- .circleci/config.yml
Use alpine3.13 as 3.14 cannot run properly under the version of Docker in use on CircleCI.
See: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12396
- Fixes #120 …
> CI: use alpine3.13 due to CircleCI docker issue

- .github/RELEASE_PROCEDURE.md
- .github/dependabot.yml
Add dependabot monitoring of the current stable branch (currently release-3.8). This will allow dependency updates to be handled smoothly for patch releases.
Previously we have cherry-picked or merged PRs from master, but where master changes its dependency set this runs the risk of missing dep updates on the stable branch.
- Fixes #123  …
> Track release-3.8 branch with dependabot

- .circleci/config.yml
Use latest version of `circleci/go` Orb. Remove `cache:no` override, as this version has addressed a bug where a pre-existing Go install was not removed when a cached version was used.
> Update Go Orb

- CHANGELOG.md
- cmd/internal/cli/build.go
- cmd/internal/cli/build_linux.go
- e2e/imgbuild/imgbuild.go
- internal/pkg/build/stage.go
- internal/pkg/build/util.go
Some software will unavoidably write to the container fs during reasonable tests. Using a build time bind to permit this is problematic as it is host specific (path available to bind), and the files created by the test likely shouldn't really stick around. Allow specifying `--writable-tmpfs` for a `singularity build` to use a writeable tmpfs in the `%test` section of the build only.
- Fixes #109 …
> Allow --writable-tmpfs for %test step of build

- internal/pkg/build/sources/oci_unpack.go
Change to sandbox to keep restrictive permissions was made in Singularity 3.5. It's now appropriate to revise the message so it doesn't point to a discussion thread, and is just a plain warning
- Fixes #85 …
> Update restrictive permissions sandbox warning

- .circleci/config.yml
- INSTALL.md
Use Go 1.16.6 in CI and `INSTALL.md`.
> Bump Go to 1.16.6

- CHANGELOG.md
- e2e/env/env.go
- e2e/env/regressions.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/shell/escape.go
- internal/pkg/util/shell/escape_test.go
From Singularity 3.6, SINGULARITYENV_ prefixed env vars on the host become env vars in the container by:
- Creating an injectable script which will `export KEY=VAL`.
- Sourcing this script in the container setup, through the embedded shell interpreter.
When the injectable script was written, the value for each export statement was being quoted automatically using the Go `q` Printf style formatting. This handles double quoting the value, but also escapes other things in the value per Go string syntax.
It would be expected that a `\\\$LIB` in a SINGULARITYENV_ export at the host shell would resolve to a literal `$LIB` in the container...
- In the host shell `\\\$LIB` is evaluated and becomes `\$LIB`, which will be used as the VAL in the injectable script.
- In the Singularity embedded shell …
> fix: Allow env vars with literal $ via \\\$ in SINGULARITYENV_

- e2e/imgbuild/regressions.go
- e2e/instance/instance.go
- e2e/oci/oci.go
- go.mod
- go.sum
- pkg/util/crypt/crypt_dev.go
- Fix TestSIFInitializer Unit Test #98
- Partially Replace UUID Module #111
> Pick #98 / #111 (SIF adjacent) to release-3.8

- .circleci/config.yml
- INSTALL.md
- CI: use alpine3.13 due to CircleCI docker issue #121
- Bump Go to 1.16.6 #151
> Pick #121 / #151 (CI related) to release-3.8

- go.mod
- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/files/files.go
- internal/pkg/build/files/files_test.go
- internal/pkg/build/stage.go
In a multi-stage build `%copy`, if the source for the copy line is a
symlink we should dereference it and copy the target. Note that if we
are copying a directory we shouldn't dereference any symlinks
within the directory, only the directory itself.
Previously we were doing a straight `cp -frH` to implement this, but
it does not handle the case where a symlink to be copied is an
absolute symlink. The absolute symlink's target is correct in the
context of the stage's rootfs, but we are copying in the host context.
To fix this we manually dereference the top level src of a `%copy` line,
in a manner that will resolve absolute symlinks relative to the src
stage's rootfs correctly.
This PR also:
- Splits host->rootfs copy, and stage->stage copy functions.
- Rewrites the tests for host->rootfs …
> Handle absolute symlinks in multi-stage copy

- CHANGELOG.md
- INSTALL.md
Brings in the markdown file changes made on the `release-3.8` branch.
> Merge 'v3.8.1' to master

- .circleci/config.yml
Now seeing Docker 20.10.7 in CircleCI, which does not have the issue with latest version of alpine from #120 
This reverts commit 849e759eebc8848d779b3d76376a7c63ac81477c.
- Fixes #122  …
> Revert "CI: use alpine3.13 due to CircleCI docker issue"

- CHANGELOG.md
- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/stage.go
When the destination of a line in the `%files` section is ommitted, the
file should be copied to the same full path within the destination
rootfs as it is in the source.
Previously we naively set dst = src in this case, but src might be a
globbing pattern. In this case the file copy destination was the glob
pattern, not the matched path(s) after globbing.
Handle a blank "" dest in the CopyFromHost / CopyFromStage functions,
where globbing occurs. Copy to the correct full path after globbing.
Update tests to capture this behavior.
- Fixes #196
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELO …
> Copy globbed files to correct destination in `%files`

- CHANGELOG.md
- pkg/util/fs/proc/proc.go
- pkg/util/fs/proc/proc_linux_test.go
Cherry pick splitting fix for mountinfo line, and add a test / changelog entry.
- Fixes #198 
- …
> Cherry-pick hpcng #6075

- CHANGELOG.md
- internal/pkg/build/sources/conveyorPacker_debootstrap.go
Sometime the Debian arch string is not identical to the `runtime.GOARCH`
value for a platform. Map from `runtime.GOARCH` to the Debian arch to
address this.
- Fixes #204 …
> fix: use correct Debian arch for debootstrap

- e2e/testdata/Docker_registry.def
The `--dest-tls-verify` must now be specified as a flag to `copy` and
not as a global flag for Skopeo 1.4.0.
- Fixes #219  …
> e2e: fix registry instance for Skopeo 1.4.0

- e2e/testdata/Docker_registry.def
Cherry pick #220 for release-3.8
The `--dest-tls-verify` must now be specified as a flag to `copy` and
not as a global flag for Skopeo 1.4.0.
> e2e: fix registry instance for Skopeo 1.4.0 (release 3.8)

- CHANGELOG.md
- cmd/internal/cli/remote.go
- docs/remote.go
- internal/app/singularity/remote_login.go
- internal/pkg/remote/credential/login_handler.go
fix: --tokenfile is not supported for oci login so give error
docs: revise CLI help for remote login 
Be much more explicit in what a remote endpoint is vs OCI credentials.
Generally expand the descriptive text.
- Fixes #211 
- Based this PR against the …
> Improve OCI login docs, and be explicit on no --tokenfile support

- CHANGELOG.md
- e2e/remote/remote.go
- internal/pkg/remote/remote.go
Repeated `remote login` with the same URI can cause duplicate
`Credentials` entries in `~/remote.yaml`.
Ensure a `remote login` with an existing configured URI replaces the
existing entry. Make `remote logout` remove all entries to clean up the
result of this bug.
Also has a commit to correct e2e test looking for usage messages that were changed in #217 - but e2e was not triggered there.
- Fixes #214 
- Fixes #222  …
> fix: avoid duplicate `remote.yaml` entries from multiple login

- internal/pkg/cgroups/cgroups_linux_test.go
- internal/pkg/cgroups/example/cgroups-no-hugetlb.toml
If the system page size is not 2MB just test cgroups without a hugetlb
limit, rather than putting in more complex logic to work up configs for
different page sizes.
- Fixes #9 …
> testing: skip hugetlb cgroup limit for non-2MB page size

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
It is common for users to run docker containers that expect more isolation than is default in Singularity, and that can create files on startup. This is a simple short-hand to enable `--contain-all, --no-init, --no-umask, --writable-tmpfs`. These options give the best chance of an OCI/Docker container working as expected but *without* requiring the user/uts/net namespaces that we can't rely on in all installations / configurations of SingularityCE.
- Fixes #75
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution …
> Add `--compat` short-hand for improved OCI/Docker compatibility

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
The `--nonet` flag is confusing as it doesn't follow the `no-` hyphenation
pattern, and should apply to VM invocation only, but does not have a
`--vm-` prefix.
On further investigation the `NoNet` variable it sets is never
used. Let's just remove the flag.
- Fixes #239  …
> Remove --nonet flag (unused)

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/singularity.go
- e2e/docker/docker.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/client/oci/pull.go
The `--nohttps` flag does not fit into the pattern of `--no-` prefixes
with a hyphen for negative flags.
Add a `--no-https` flag and deprecate the existing `--nohttps` flag.
- Fixes #238  …
> Change `--nohttps` flag to `--no-https`

- CHANGELOG.md
- cmd/internal/cli/delete.go
- e2e/delete/delete.go
`singularity delete` would accept a hostname in the library:// URI
provided, but would perform the request against the default remote.
Fix this, so it is handled in the same way as for push/pull.
- Fixes #243  …
> fix: honor hostname in library:// URI for `singularity delete`

- internal/pkg/util/uri/uri.go
- internal/pkg/util/uri/uri_test.go
The Sylabs lolcow image has been modified so that it no longer uses
`fortune`, which produced offensive output. Ensure all references to a
lolcow image are to the fixed Sylabs version.
Fixes #248
- Fixes #248 …
> Ensure lolcow references point to non-fortune image

- CHANGELOG.md
- cmd/internal/cli/actions.go
- cmd/internal/cli/delete.go
- cmd/internal/cli/pull.go
When a `library://hostname/...` is specified to a command, the
`--no-https` flag should be honored, to connect to hostname via http
instead of https.
- Fixes #236 …
> Honor `--no-https` for `library://hostname/...` URIs

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/pkg/build/sources/conveyorPacker_arch.go
Fix for arch Linux bootstrap issue downloading the default pacman.conf.
https://github.com/hpcng/singularity/pull/6127
- Fixes #254  …
> Cherry pick hpcng  #6127

- CHANGELOG.md
- e2e/docker/docker.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/shell/escape.go
- internal/pkg/util/shell/escape_test.go
The `CMD` / `ENTRYPOINT` translation is single quoted in the runscript, so we must escape single quotes in `CMD` and `ENTRYPOINT`.
- Fixes #233
See also https://github.com/hpcng/singularity/issues/6128 …
> fix: Escape ' in docker CMD / ENTRYPOINT for runscript

- CHANGELOG.md
- e2e/imgbuild/imgbuild.go
- internal/pkg/build/sources/conveyorPacker_library.go
When a hostname is included in a `library://` URI, or the def file, make sure it is honored by `singularity build`.
- Fixes #246 …
> fix: honor hostname in library URI for `singularity build`

- CHANGELOG.md
- cmd/internal/cli/build_linux.go
- cmd/internal/cli/push.go
- cmd/internal/cli/remote.go
- cmd/internal/cli/singularity.go
- go.mod
- go.sum
- internal/app/singularity/remote_add.go
- internal/app/singularity/remote_add_test.go
- internal/app/singularity/remote_list.go
- internal/app/singularity/remote_login.go
- internal/app/singularity/remote_remove.go
- internal/app/singularity/remote_remove_test.go
- internal/pkg/remote/endpoint/config.go
- internal/pkg/remote/endpoint/service.go
- internal/pkg/remote/endpoint/token.go
- internal/pkg/remote/remote_test.go
Previously, `https://` was always prefixed to a remote endpoint's
configured `URI`. This meant that remote service discovery was not
possible against an http-only server.
Patches have been circulated by the community to allow use of http for
development etc.
This PR allows the `--insecure` flag to be specified to `remote add`.
An insecure endpoint configuration will perform service discovery over
http.
Additionally, the filename for caching remote configs is changed to a
safe 'slug' version of the remote URI. This allows URIs with a '/' or
other special characters in them.
- Fixes #237  …
> Allow `remote add --insecure` for http endpoints

- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
When the source in a `%files` entry is a glob that matches multiple files, and the destination is `""`, make sure we always set the correct real destination for each file.
This is a fix for a case not tested, and not handled properly in #197 
- Fixes #261  …
> fix: always check dest for globbed %files 

- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
Pick #262 which is a fix for an issue not covered in #197 …
> Cherry pick #262 for release-3.8

- CHANGELOG.md
- pkg/image/unpacker/squashfs.go
We were previously setting `--user-xattrs` / `--no-xattrs` based on
the current euid when calling `unsquashfs`. However, in a non-setuid
install `--fakeroot` build the euid is 0, so the flags will not be
set. On distributions other than EL / Fedora (i.e. Debian / Ubuntu
which are not selinux native), this can cause failed extraction.
Decide if we are performing a rootless extraction based on the host
uid, outside of any namespace that is in play.
- Fixes #266 
See also https://github.com/hpcng/singularity/issues/6113
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary …
> fix: Check for *host* non-root uid when setting unsquashfs flags

- CHANGELOG.md
- pkg/image/unpacker/squashfs.go
Picking #267 
fix: Check for *host* non-root uid when setting unsquashfs flags
We were previously setting `--user-xattrs` / `--no-xattrs` based on
the current euid when calling `unsquashfs`. However, in a non-setuid
install `--fakeroot` build the euid is 0, so the flags will not be
set. On distributions other than EL / Fedora (i.e. Debian / Ubuntu
which are not selinux native), this can cause failed extraction.
Decide if we are performing a rootless extraction based on the host
uid, outside of any namespace that is in play.
Fixes: #266
> Pick #267 to release-3.8

- cmd/internal/cli/singularity.go
- go.mod
- internal/app/singularity/oci_attach_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/interactive/interactive.go
Replace the deprecated `golang.org/x/crypto/ssh/terminal` package with `golang.org/x/term`.
- Fixes #295 
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING …
> Replace golang.org/x/crypto/ssh/terminal (master)

- cmd/internal/cli/singularity.go
- go.mod
- internal/app/singularity/oci_attach_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/interactive/interactive.go
Replace the deprecated `golang.org/x/crypto/ssh/terminal` package with `golang.org/x/term`.
- Fixes #295 
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING …
> Replace golang.org/x/crypto/ssh/terminal (3.8)

- CHANGELOG.md
- cmd/internal/cli/build_linux.go
- internal/pkg/build/build.go
- internal/pkg/build/conveyorPacker.go
When we submit a remote build we should check that the 'bootstrap' header is valid before we submit the remote build.
Also ensure it is not a 'localimage' source, as this is not supported at present.
Example...
```
04:51 PM $ singularity build -r test.sif libary://alpine
FATAL:   Unable to build from libary://alpine: invalid build source "libary"
```
- Fixes #10 …
> fix: check remote build bootstrap valid before submitting

- cmd/internal/cli/push.go
This PR fixes that LGTM.com warning:
https://lgtm.com/projects/g/sylabs/singularity/snapshot/5763d01e852b40a6c51c48f0b8f3ed92ceba2676/files/cmd/internal/cli/push.go#x133b9ad5a6cec035:1
According to the [log.Fatalf documentation](https://pkg.go.dev/log#Fatalf):
> Fatalf is equivalent to Printf() followed by a call to os.Exit(1).
Therefore, calling `os.Exit(3)` right after `log.Fatalf()` is redundant.
- Fixes #309.
✅ Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
❌ Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
✅ …
> Fix LGTM warning: Unreachable statement

- e2e/imgbuild/imgbuild.go
- internal/pkg/build/sources/conveyorPacker_busybox_test.go
Disable busybox bootstrap from tgz, as the download from the busybox site has been failing often, disrupting CI / merges. …
> e2e: Disable busybox bootstrap due to frequent dl failures

- e2e/imgbuild/imgbuild.go
- examples/centos-arm64/Singularity
- examples/opensuse-arm64/Singularity
Make OpenSUSE example use LEAP 15.3 which works under fakeroot.
While we are at it, add arm64 OpenSUSE and CentOS boostraps to e2e testing.
- Fixes #307 …
> e2e: Bump OpenSUSE example, add arm64 for OpenSUSE & CentOS bootstrap

- internal/pkg/fakeroot/fakeroot.go
- internal/pkg/runtime/engine/singularity/container_linux.go
Explicitly parse 32-bit uint, instead of using strconv.Atoi.
Fixes remaining warnings listed at: https://lgtm.com/projects/g/sylabs/singularity/alerts/?mode=list
Fixes #318  …
> Fix LGTM uint32 parse warnings

- pkg/runtime/engine/singularity/config/bind.go
- pkg/runtime/engine/singularity/config/bind_test.go
- pkg/runtime/engine/singularity/config/config.go
The parsing routines for bind mount specifications are buried among a large amount of simple Getter/Setter code for the main config struct within `pkg/runtime/engine/singularity/config`. There are also no unit tests on the parsing, and it's a little under-described.
In advance of #118 work, split the parsing functions into a separate file for clarity, and add basic testing. Add a couple of comments, and constants to make things a bit clearer. No real logic changes here - code was just moved.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution …
> Split ParseBindPath from config Get/Setters & add basic tests

- internal/pkg/build/sources/conveyorPacker_busybox_test.go
Missed in the previous BusyBox disabling. …
> Temporarily disable TestBusyBoxPacker (release-3.8)

- e2e/overlay/overlay.go
- internal/pkg/util/bin/bin_test.go
Unfortunately, on some distributions or user environments, variations
in `/bin` symlinking, PATH ordering and propagation / non propagation
across tests run under sudo lead to situations where TestFindOnPath
doesn't work, as the truth value may have the symlink path, while the
function under test returns the target path (or vice versa).
We can't resolve symlinks out in findOnPath to match the test, as the
symlink name can impact the function of the program. E.g. resolving
`mkfs.ext3` to `mke2fs` and calling that will result in an ext2
filesystem, rather than an ext3 filesystem being created.
The best approach here seems to be to force a specific PATH in the
test, instead.
Also add an ensureImage call to e2e overlay tests - found this was missing when running a subset of the e2e and it …
> Fix TestFindOnPath

- cmd/internal/cli/actions_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/util/gpu/nvidia.go
- internal/pkg/util/gpu/nvidia_test.go
- pkg/runtime/engine/singularity/config/config.go
The flags that will be used as options to `nvidia-container-cli` are
currently derived within the CLI and passed in the runtime config.
The potentially dangerous `--ldconfig` flag is always appended to the
actual `nvidia-container-cli` call within `NVCLIConfigure`, so
attempts to pass a malicious `--ldconfig=xxx` from a modified CLI
binary are overridden. However, we should perform the env -> flag
conversion in a trusted portion of code, so we only ever call
`nvidia-container-cli` with a set of flags we directly control.
- Fixes #396
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if …
> fix: perform nvccli env->flags inside runtime, not CLI

- CHANGELOG.md
- e2e/pull/concurrency.go
- e2e/pull/pull.go
- go.mod
- go.sum
- internal/pkg/client/library/library.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/progress.go
- pkg/util/singularityconf/config.go
- pkg/util/singularityconf/parser_test.go
_Work performed by @EmmEff  - I've just cherry picked / squashed off his branch_
Adds singularity.conf and env var overrides:
`SINGULARITY_DOWNLOAD_CONCURRENCY` - number of concurrent requests for
multi-part download (default: 1)
`SINGULARITY_DOWNLOAD_PART_SIZE` - size (in bytes) of part for
multi-part download (default: 5242880)
`SINGULARITY_DOWNLOAD_BUFFER_SIZE` - size (in bytes) of xfer buffer
used to download part (default: 32768)
- Fixes #394 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution …
> feat: support for multi-part concurrent library image download

- CHANGELOG.md
- e2e/config/config.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- pkg/image/image.go
- pkg/util/singularityconf/config.go
The `allow container $type` directives are confusing as they allow
limiting use of SquashFS and EXT3 containers... but will also apply to
those filesystems inside of a SIF.
We commonly present SIF as a separate container format, and users
don't generally need to be aware that it's a wrapper format for other
filesystem types. We generally talk about a `SquashFS` image in the
context of a raw Singularity 2.x image, not the contents of a
SIF. With this in mind it makes more sense to separately allow /
disallow SIF or bare SquashFS etc.
This PR:
* Modifies the logic applying the `allow container
squashfs/ext3` directive so they only apply to *bare* images
in those formats, not SIFs using those formats internally.
* Modifies `allow container encrypted` so that it only controls use of
SIF …
> Split SIF/bare types w.r.t `allow container $type` config

- e2e/pull/concurrency.go
- e2e/pull/pull.go
We can't accumulate config resets with defer as we need to run each test from a 'clean' starting config, and a defer is scoped to the function, not the loop iteration.
Apologies - this wasn't caught when I reviewed the concurrency PR. …
> e2e: linearize config --set --reset for concurrent pull tests

- internal/pkg/runtime/engine/singularity/rpc/args.go
- internal/pkg/runtime/engine/singularity/rpc/client/client.go
- internal/pkg/runtime/engine/singularity/rpc/server/server_linux.go
The previous nvccli PR flipped the 3rd variable in our NVCLI related
functions from RunAsRoot, to UserNS (which has opposite meaning). The RPC
functions signatures were not modified correctly at the same time. …
> Flip RunAsRoot->UserNS in RPC for NvCCLI

- CHANGELOG.md
- internal/app/singularity/config_global_linux.go
When using `config global --set` an invalid directive value could previously
lead to an empty `singularity.conf`, as the file was opened with
`O_TRUNC` before the new config was generated/validated.
Generate the config output to an in memory buffer, and only create /
truncate the `singularity.conf` file once we have generated known valid
output.
- Fixes #409 …
> fix: Don't truncate config file until we have valid output to write

- .circleci/config.yml
- .golangci.yml
- e2e/gpu/gpu.go
- e2e/sign/sign.go
- internal/app/starter/master_linux_test.go
- internal/pkg/build/sources/conveyorPacker_yum.go
- internal/pkg/build/sources/conveyorPacker_zypper.go
- internal/pkg/client/oras/oras.go
- internal/pkg/remote/endpoint/client_test.go
- internal/pkg/util/bin/bin_test.go
- pkg/image/image_test.go
- pkg/util/capabilities/config.go
- pkg/util/capabilities/config_test.go
Bump `golangci-lint` to 1.43. Enable `contextcheck` and `dupl` linters. Wire up context in ORAS `getResolver`, which is caught by the `contextlint` trap.
- Fixes # …
> Bump golangci-lint to 1.43

- e2e/gpu/gpu.go
As pointed out in #416 the GPU tests weren't using the profile indicated on the `tt` test structures, but instead always the UserProfile.
PR corrects this.
Note... this won't be tested in CI as there is no GPU. See the output of a local run below:
<details>
<summary>e2e GPU output</summary>
<pre>
=== RUN   TestE2E/PAR
=== RUN   TestE2E/PAR/GPU
=== PAUSE TestE2E/PAR/GPU
=== CONT  TestE2E/PAR/GPU
=== RUN   TestE2E/PAR/GPU/rocm
=== PAUSE TestE2E/PAR/GPU/rocm
=== RUN   TestE2E/PAR/GPU/build_nvidia
=== PAUSE TestE2E/PAR/GPU/build_nvidia
=== RUN   TestE2E/PAR/GPU/build_nvccli
=== PAUSE TestE2E/PAR/GPU/build_nvccli
=== RUN   TestE2E/PAR/GPU/build_rocm
=== PAUSE TestE2E/PAR/GPU/build_rocm
=== RUN   TestE2E/PAR/GPU/nvidia
=== PAUSE TestE2E/PAR/GPU/nvidia
=== RUN   TestE2E/PAR/GPU/nvccli
=== PAUSE …
> e2e: ensure GPU tests use intended profile

- e2e/env/regressions.go
Pick https://github.com/hpcng/singularity/pull/6282
No longer set python=3 for e2e test that uses conda
- Fixes #421 
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/ …
> no longer set python=3 for conda

- cmd/internal/cli/search.go
Wire up context in `SearchCmd`, which was missed in #376. Thanks @DrDaveD! 
- Fixes #420
- Added …
> Wire Up Contexts in SearchCmd

- .github/dependabot.yml
Update Dependabot target branches to `master` and `release-3.9`, to account for 3.9.0 release.
- Fixes #
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING. …
> Update Dependabot Target Branches

- CHANGELOG.md
- etc/seccomp-profiles/default.json
- go.mod
- go.sum
- internal/pkg/runtime/engine/config/oci/config.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/security/seccomp/seccomp_supported.go
- internal/pkg/security/seccomp/seccomp_supported_test.go
- internal/pkg/security/seccomp/seccomp_unsupported.go
- internal/pkg/security/security.go
seccomp/containers-golang has been archived and will not receive fixes,
so we need to transition to containers/common/pkg/seccomp.
Update our example seccomp profile to the output of `make seccomp.json`
on the new module.
Add handling of errnoRet & defaultErrnoRet in seccomp profiles, and use
this rather than passing the err number in function calls.
Skip over any seccomp rules that are redundant, i.e. the action is the
same as the default action. These now cause AddRule to error with our
updated dependencies.
I've opened #439 as an issue to improve unit and e2e testing here, so that we are checking the _effect_ of a broader variety of filters is as expected. I've added some tests in this PR that cover parts of the internal image-spec -> libseccomp translations, but a lot of paths here …
> Switch to containers/common from seccomp/containers-golang

- e2e/plugin/plugin.go
Check output of plugin commands in addition to return code. Check state reported by plugin list across install/disable/enable/uninstall.
- Fixes #448 …
> e2e: check more output of plugin commands

- CONTRIBUTORS.md
- cmd/internal/cli/sign.go
This is purely a change to the documentation to clarify that the `--keyidx` key index parameter for the `singularity sign ...` command relates to the _private_ keys, so the `--secret` argument is necessary when obtaining the index from `singularity key list`.
- N/A …
> Clarify source of key index

- pkg/util/loop/loop.go
Recently an issue was discovered when using the Singularity container runtime in Arvados Crunch where certain Slurm jobs would start failing with an error message:
```
2021-11-26T18:57:12.918958066Z ERROR [container bcftools_convert_10] (arvc1-xvhdp-ffcjthyczz8gqol) error log:
2021-11-26T18:57:12.918958066Z 
2021-11-26T18:57:12.918958066Z   2021-11-26T18:56:45.272198441Z crunch-run Not starting a gateway server (GatewayAuthSecret was not provided by dispatcher)
2021-11-26T18:57:12.918958066Z   2021-11-26T18:56:45.272309584Z crunch-run crunch-run 2.3.1 (go1.17.1) started
2021-11-26T18:57:12.918958066Z   2021-11-26T18:56:45.272331939Z crunch-run Executing container 'arvc1-dz642-tlt1uw3hyppd06g' using singularity runtime
2021-11-26T18:57:12.918958066Z   2021-11-26T18:56:45.272354161Z …
```
> AttachFromFile: rewrite retry loop

- CHANGELOG.md
- makeit/gengodep
Cherry-pick of #462 
In a previous PR, initialization of the `srcdir` varible was removed
from `makeit/gengodep`. However, the `gengodep` script was still using
`srcdir` when checking for a `${srcdir}/vendor/modules.txt`.
https://github.com/sylabs/singularity/commit/48e7fab83e11a698adbd506d60e13fb375b00fec#
As a result, the vendor dir is never found, and `go` was run with
`-mod=readonly`, which would lead to downloads.
Since go 1.14 the presence of a vendor dir infers `-mod=vendor`
automatically, so we can just remove the handling here.
- Fixes #461 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/ …
> fix: ensure gengodep uses vendor dir if present (3.9)

- CHANGELOG.md
- cmd/internal/cli/build_linux.go
At the CLI level, local builds had a hard fail if a keyserver config
could not be retrieved.
1) Warn instead of fail. For builds that perform verification of a
SIF, it may still be possbile to verify using the local keyring.
2) Don't attempt to get a keyserver config at all, unless build
definition has a bootstrap that will, or may provide a SIF source
image (library/localimage/oras/shub).
- Fixes #465
- Added tests …
> fix: do not require working keyserver config in local build

- CHANGELOG.md
- cmd/internal/cli/build_linux.go
Cherry-pick of #466 
At the CLI level, local builds had a hard fail if a keyserver config
could not be retrieved.
1) Warn instead of fail. For builds that perform verification of a
SIF it may still be possbile to verify using the local keyring.
2) Don't attempt to get a keyserver config at all, unless build
definition has a bootstrap that will, or may provide a SIF source
image (library/localimage/oras/shub).
- Fixes #465
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTIN …
> fix: do not require working keyserver config in local build (3.9)

- pkg/util/loop/loop.go
- pkg/util/loop/loop_test.go
The loop.AttachFromFile code, used to attach an image to a free loop
device, or to find a shared loop device has been refactored.
Previously, a complex loop handled both finding shared loop devices
and attaching to new free devices. The logic was difficult to follow,
especially with regard to tracking which errors were fatal and would
bubble up, vs result in loop continuation, or retries.
The shared and 'fresh' attachment have been separated into two
functions. Some additional logging / error detail has been added.
The test code has been modified to prevent a leak of a loop device.
- Fixes #463 …
> Refactor loop.AttachFromFile

- CHANGELOG.md
- pkg/util/loop/loop.go
- pkg/util/loop/loop_test.go
Cherry pick Arvados fix #458 and refactoring #464 changes to loop device discovery, for 3.9.
- Added …
> Pick loop device discovery change #458 & #464

- .circleci/config.yml
- INSTALL.md
> docs: Update INSTALL.md for 3.9.2

- pkg/util/loop/loop.go
When a transient error is hit in attachLoop, make sure we close loopFd before continuing, so that we don't leak an fd.
Add the close to another fatal error path for code consistency - it's an exit path so it isn't a necessity.
NB: Have seen the alternate approach to loop dev EAGAIN handling that is being applied in an apptainer PR, which is to call a `unix.Sync()` on EAGAIN, rather than moving on or using a delayed retry loop. It does look like this is a neater solution to the underlying problem. However, a full sync can often be _extremely_ expensive in an HPC environment, and it's happening in a place where  `/dev` has been locked. I am concerned this could lead to extremely slow parallel startup of Singularity in some cases, while the ugly but simple retry approach is sufficient.
- …
> fix: Close loopFd in transient error path

- pkg/util/loop/loop.go
When a transient error is hit in attachLoop, make sure we close loopFd
before continuing, so that we don't leak an fd.
Add the close to another fatal error path for code consistency - it's an
exit path so it isn't a necessity.
- Fixes #482  …
> fix: Close loopFd in transient error path (release-3.9)

- CHANGELOG.md
- cmd/internal/cli/actions_linux.go
When using nvidia-container-cli to setup the GPUs in the container, we
need to force NVIDIA_VISIBLE_DEVICES=all to have an exact match to the
legacy GPU binding behaviour, where MIGs are available as well as
physical GPUs.
- Fixes #471  …
> fix: gpu: ensure MIGs available with --nvccli and no --contain

- .github/ISSUE_TEMPLATE/bug_report.md
This changes the bug report template to suggest using `singularity --version` instead of `singularity version` to report the version number, so the project name is included.
None …
> Use singularity --version instead of singularity version in bug report template

- CHANGELOG.md
- cmd/internal/cli/actions_linux.go
Pick #489 
When using nvidia-container-cli to setup the GPUs in the container, we
need to force NVIDIA_VISIBLE_DEVICES=all to have an exact match to the
legacy GPU binding behaviour, where MIGs are available as well as
physical GPUs.
Fixes #471
- Fixes #471 …
> fix: gpu: ensure MIGs available with --nvccli and no --contain (release-3.9)

- CHANGELOG.md
- debian/rules
- debian/singularity-ce.install
- debian/singularity-ce.lintian-overrides
- dist/rpm/singularity-ce.spec.in
- mlocal/frags/Makefile.stub
It's reasonable to expect that `make install` will install man pages,
but that hasn't been the case here... meaning we are somewhat unusual.
Have `make install` call the `man` target.
Ensure the resulting man pages are handled in the Debian package
properly.
- Fixes #512 …
> build: handle man pages with make install

- CHANGELOG.md
- cmd/internal/cli/build.go
If a `singularity build` is run without a terminal Stdin (i.e. non-interactive), fail quickly if the output file already exists. Don't get stuck trying to ask for a y/n that won't come.
This is a quick fix addressing this specific common location where a non-interactive build can get hung up... and there is a `--force` flag to be employed so nobody needs to pipe in a 'y'. 
Really there should be a proper review of where the interactive package is used, and sensible behavior of the functions for these types of uses. We maybe should have variant functions that e.g. fail or fall to a default if Stdin isn't a terminal. However we also need to consider usage that pipes in to answer a prompt (e.g. provide encryption passphrase) from another tool.
Will open a tech-debt issue for the above.
- …
> fix: Don't prompt y/n to overwrite output in noninteractive build

- .circleci/config.yml
- e2e/docker/docker.go
- examples/build-singularity/build-singularity.def
CentOS 8 is EOL. We should switch to an alternative for examples / Docker image usage in our CI and tests.
Rocky or Alma are the obvious choices, without much to choose between them since they are both by definition RHEL compatible, bugs 'n all.
Going with AlmaLinux at this point, as releases have been slightly quicker following upstream than Rocky.
- Fixes #535  …
> Switch centos:8 to almalinux:8

- CHANGELOG.md
- e2e/oci/oci.go
- internal/pkg/runtime/engine/config/oci/config.go
When OCI mount creates a bundle it adds a default `config.json`. In this file, `Process.Terminal` was set to `false`. This means that an `oci run` of a container will not result in sensible interactive behavior, and the user's terminal will be broken.
`runc spec` and `crun spec` both set `Process.Terminal` to `true`, when creating a default config for a rootfs. I believe we should do the same so that sensible interactive behavior is the default.
Note that our e2e tests were already overriding the default config in this manner.
Also change the `mrsdalloway` default hostname to `singularity`.
- Fixes #532  …
> fix: set OCI Process.Terminal: true in oci mount

- CHANGELOG.md
- go.mod
- go.sum
Restores `unset` of global vars within a function.
- Fixes #543
- Added myself as a contributor to …
> fix: update mvdan.cc/sh to HEAD of v3.4 branch

- .circleci/config.yml
- e2e/docker/docker.go
- examples/build-singularity/build-singularity.def
CentOS 8 is EOL. Switching to AlmaLinux as an EL compatible rebuild.
Cherry pick of #536 to release-3.9
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.m …
> Switch centos:8 to almalinux:8 (release-3.9)

- CHANGELOG.md
- debian/rules
- debian/singularity-ce.install
- debian/singularity-ce.lintian-overrides
- dist/rpm/singularity-ce.spec.in
- mlocal/frags/Makefile.stub
It's reasonable to expect that make install will install man pages,
but that hasn't been the case here... meaning we are somewhat unusual.
Have make install call the man target.
Ensure the resulting man pages are handled in the Debian package
properly.
- Fixes #512 …
> build: handle man pages with make install (release-3.9)

- CHANGELOG.md
- go.mod
- go.sum
Cherry pick #546 
Restores `unset` of global vars within a function.
- Fixes #543
- Added myself as …
> fix: update mvdan.cc/sh to HEAD of v3.4 branch (release-3.9)

- CHANGELOG.md
- COPYRIGHT.md
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/fs/files/action_scripts.go
The action script environment processing was calling out to
`getenvkey` and `unescape` go functions via subshell. This is
expensive, especially with large environments, as the environment
etc. must be duplicated for each subshell and other subshell setup
performed.
Replace these two go functions with shell var substitution syntax.
- Fixes #544
- Added tests to validate this PR, linted with `make check`  and tested …
> fix: remove subshell overhead in environment processing (release-3.9)

- mlocal/frags/Makefile.stub
- mlocal/frags/build_cli.mk
Make man page generation part of the `build_cli.mk` fragment, so that man pages are built under `make` and installed with `make install`.
What I should have originally done in #524 instead!
- Fixes #555 …
> fix: split man generation and install

- mlocal/frags/Makefile.stub
- mlocal/frags/build_cli.mk
Make man page generation part of the `build_cli.mk` fragment, so that man pages are built under `make` and installed with `make install`.
What I should have originally done in #524 instead!
- Fixes #555 …
> fix: split man generation and install (release-3.9)

- CHANGELOG.md
- internal/pkg/cgroups/config_linux.go
- internal/pkg/cgroups/example/cgroups-unified.toml
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/cgroups/manager_linux_v2_test.go
Allow the `unified` key to be used in a cgroups config toml file, to directly apply resource limits using the v2 unified hierarchy, rather than v1 -> v2 translation.
- Fixes #538  …
> feat: enable native v2 unified cgroups config

- internal/pkg/cgroups/manager_linux_test.go
- internal/pkg/cgroups/manager_linux_v1_test.go
- internal/pkg/cgroups/manager_linux_v2_test.go
Freezing a cgroup is almost always instant for our trivial test cases... except when it isn't due to system load, slow qemu emulation of alternate architectures etc.
The Linux docs explicitly show this in their example :-)
to freeze all tasks in the container :
FREEZING
FROZEN
Allow up to 5 retries, separated by 1 second for processes to be suspended in our tests.
Verified by running the tests in a hard loop on a loaded and slow constrained system, and observing behaviour.
- Fixes #565
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution …
> tests: allow for cgroups freeze/thaw that isn't instant

- CHANGELOG.md
- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity_test.go
When running `unsquashfs` in a minimal container, we need to bind in the libraries that it requires. In some circumstances, the filename of `.so` that the loader is looking for may not much the filename of the resolved library through symlinks etc.
E.g. on EL8, POWER9 with glibc-hwcaps we have:
```
libpthread.so.0 => /lib64/glibc-hwcaps/power9/libpthread-2.28.so (0x00007fff96a20000)
```
In this case we have to bind `libpthread-2.28.so` into the container as `libpthread.so.0` as we are not creating symlinks, and the loader is looking for `libpthread.so.0` and won't find `libpthread-2.28.so`.
- Fixes #571  …
> fix: bind libs to correct .so file for unsquashfs containment

- CHANGELOG.md
- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity_test.go
Cherry pick of #572 
When running `unsquashfs` in a minimal container, we need to bind in
the libraries that it requires. In some circumstances, the filename of
`.so` that the loader is looking for may not much the filename of the
resolved library through symlinks etc.
E.g. on EL8, POWER9 with glibc-hwcaps we have:
```
libpthread.so.0 => /lib64/glibc-hwcaps/power9/libpthread-2.28.so (0x00007fff96a20000)
```
In this case we have to bind `libpthread-2.28.so` into the container
as `libpthread.so.0` as we are not creating symlinks, and the loader
is looking for `libpthread.so.0` and won't find `libpthread-2.28.so`.
- Fixes #571
- Added …
> fix: bind libs to correct .so file for unsquashfs containment (release-3.9)

- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity_test.go
Refine the unsquashfs library discovery to accommodate the output of the loader --list on EL7, where it outputs a `=>` field even when the arrow isn't going to point to a path.
- Fixes #582  …
> fix: Handle old EL7 library list format

- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity_test.go
Refine the unsquashfs library discovery to accommodate the output of
the loader --list on EL7, where it outputs a `=>` field even when the
arrow isn't going to point to a path.
- Fixes #582 …
> fix: Handle old EL7 library list format (release-3.9)

- go.mod
- go.sum
3.4.3 of mvdan.cc/sh was released, which contains the fix we contributed to solve the unset regression.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.m …
> deps: move to release mvdan.cc/sh v3.4.3

- .circleci/config.yml
- .golangci.yml
- INSTALL.md
- cmd/internal/cli/actions_linux.go
- e2e/actions/actions.go
- e2e/config/config.go
- e2e/ecl/ecl.go
- e2e/imgbuild/imgbuild.go
- e2e/inspect/inspect.go
- e2e/internal/e2e/singularitycmd.go
- internal/app/singularity/remote_add_test.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/oci/oci_test.go
- internal/pkg/build/sources/conveyorPacker_zypper.go
- internal/pkg/runtime/engine/config/oci/generate/generate_test.go
- internal/pkg/runtime/engine/oci/create_linux.go
- internal/pkg/runtime/engine/oci/prepare_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/fs/mount/mount_linux_test.go
- pkg/sypgp/keyring.go
Bump Go to 1.17.7. Use latest `ubuntu-machine` image. Bump Node to 17.x. Bump `golangci-lint` to 1.44, and enable `containedctx`, `decorder`, `grouper` and `maintidx` linters.
> CI Updates (master)

- .circleci/config.yml
- .golangci.yml
- INSTALL.md
- cmd/internal/cli/actions_linux.go
- e2e/actions/actions.go
- e2e/config/config.go
- e2e/ecl/ecl.go
- e2e/imgbuild/imgbuild.go
- e2e/inspect/inspect.go
- e2e/internal/e2e/singularitycmd.go
- internal/app/singularity/remote_add_test.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/oci/oci_test.go
- internal/pkg/build/sources/conveyorPacker_zypper.go
- internal/pkg/runtime/engine/config/oci/generate/generate_test.go
- internal/pkg/runtime/engine/oci/create_linux.go
- internal/pkg/runtime/engine/oci/prepare_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/fs/mount/mount_linux_test.go
- pkg/sypgp/keyring.go
Bump Go to 1.17.7. Use latest `ubuntu-machine` image. Bump Node to 17.x. Bump `golangci-lint` to 1.44, and enable `containedctx`, `decorder`, `grouper` and `maintidx` linters.
> CI Updates (release-3.9)

- .circleci/config.yml
Debian Bullseye has been the latest stable since August 2021. Change our CI to use the bullseye based golang image, instead of the buster (oldstable) image. …
> ci: bump debian to bullseye

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- e2e/actions/actions.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- pkg/runtime/engine/singularity/config/config.go
Allow one or more `bind path` entries in `singularity.conf` to be
ignored by specifying the absolute path of the destination as a
`--no-mount` or `SINGULARITY_NO_MOUNT` value.
This allows finer-grained control of bind mounts than `--contain`,
which will disable all.
It is useful in situations where e.g. a directory `/project` in a
container clashes with a `bind path = /project` entry, but other
default binds from the host are still required.
Note that `/etc/hosts` and `/etc/localtime` were always specially
injected with `--contain`, but the new `--no-mount` handling now
allows this to be overridden also.
- Fixes #625 
- Added changes …
> feat: --no-mount for 'bind path' entries

- CHANGELOG.md
- cmd/starter/c/starter.c
nvidia-container-cli v1.8.0+ requires CAP_NET_ADMIN due to cgroups
v2 (eBPF) related functionality in libnvidia-container.
- Fixes #641  …
> fix: gpu: support nvidia-container-cli >=1.8.0 (release-3.9)

- CHANGELOG.md
- cmd/starter/c/starter.c
nvidia-container-cli v1.8.0+ requires CAP_NET_ADMIN due to cgroups
v2 (eBPF) related functionality in libnvidia-container.
- Fixes #641 …
> fix: gpu: support nvidia-container-cli >=1.8.0

- CHANGELOG.md
- mconfig
- mlocal/checks/project-post.chk
Make seccomp a hard requirement in `mconfig` unless `--without-seccomp` is used. Also check that seccomp is available unless `--without-conmon` is used to disable the build of conmon from source, which requires the seccomp headers.
- Fixes #673
- Based this …
> fix: make seccomp a hard requirement in mconfig

- .circleci/config.yml
- INSTALL.md
- cmd/starter/engines/fakeroot_linux.go
- cmd/starter/engines/singularity_linux.go
- e2e/e2e_test.go
- go.mod
- internal/pkg/image/unpacker/squashfs_no_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_singularity_test.go
- internal/pkg/runtime/engine/singularity/plugins_linux.go
- internal/pkg/security/apparmor/apparmor_supported.go
- internal/pkg/security/apparmor/apparmor_unsupported.go
- internal/pkg/security/seccomp/seccomp_supported.go
- internal/pkg/security/seccomp/seccomp_supported_test.go
- internal/pkg/security/seccomp/seccomp_unsupported.go
- internal/pkg/security/selinux/selinux_supported.go
- internal/pkg/security/selinux/selinux_unsupported.go
- internal/pkg/util/gpu/paths_test.go
- internal/pkg/util/user/cgo_lookup_unix.go
- pkg/network/network_linux_test.go
- pkg/sylog/sylog.go
- pkg/sylog/sylog_dummy.go
- pkg/sylog/sylog_dummy_test.go
- pkg/sylog/sylog_test.go
- pkg/util/fs/lock/var_linux_32bit.go
- pkg/util/loop/loop_no_singularity.go
- pkg/util/loop/loop_singularity.go
- pkg/util/namespaces/setns_linux.go
Bump Go versions used in CI to 1.17 and 1.18. Remove deprecated build constraint format.
> Adopt Go 1.18 (master)

- CHANGELOG.md
- CONTRIBUTORS.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- e2e/env/env.go
- internal/pkg/remote/endpoint/config.go
- pkg/cmdline/flag.go
- pkg/cmdline/flag_test.go
There was a bug reported in slack that `--env` is truncating variables at commas:
> Hello, I am trying to use --env to specify an environment variable (--env clustering_threshold='100,97') but I am running into an issue with 
```WARNING: Ignore environment variable "97": '=' is missing .```
> I have tried to use a backslash to escape the comma but that doesn't seem to work.
> I am currently using singularity-ce version 3.9.0
And I think I've seen this before? https://github.com/google/go-containerregistry/pull/1178. So because I love Go and don't get to work on enough Go projects (and this seemed like maybe a good way to engage with Singularity again) I decided to try for a fix! The bug looks to be the same here - there are just a few more layers added on top of it with the custom cmdline …
> Add registerStringMapVar to handle --env with commas!

- CHANGELOG.md
- CONTRIBUTORS.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- e2e/env/env.go
- internal/pkg/remote/endpoint/config.go
- pkg/cmdline/flag.go
- pkg/cmdline/flag_test.go
Cherry pick #674 
Commit message:
the current flag using a splice type will truncate on commas. In order to better
support commas in --env variables we should have support for types of map[string]string.
This change will add this new option and fix the current --env bug described in slack
that splits name=val1,val2 into just name=val1 and outputs a warning. I saw some custom
parsing code in a different file that maybe was intended to handle this, but it never
gets called because the envar is skipped. If it is not skipped the comma would already
be truncated by the flag parser.
Apologies for mistakes - have not looked at Singularity source code in years it seems!
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> updating --env flags to be a map[string]string (release 3.9)

- CHANGELOG.md
- cmd/starter/c/starter.c
- internal/pkg/runtime/engine/config/starter/starter_linux.go
Fedora 35 (and maybe other distros) uses file capabilities for `newuidmap` and `newgidmap`. We were previously checking these were setuid root. Drop the check and instead output an informative message on execution failure.
Error message is not the tidiest, due to where in the started flow any failure will occur, but is informative:
```
$ singularity run -u --fakeroot docker://alpine
INFO:    Using cached SIF image
INFO:    Converting SIF file to temporary sandbox...
newgidmap: write to gid_map failed: Operation not permitted
ERROR  : 'newgidmap' execution failed. Check that 'newgidmap' is setuid root, or has required capabilities.
ERROR  : Error while waiting event for user namespace mappings: Bad file descriptor
```
With caps per Fedora 35 default, now works:
```
$ singularity run -u …
```
> fix: Allow newuidmap/newgidmap using caps, not setuid root

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/actions_linux.go
- e2e/docker/docker.go
- e2e/env/env.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- pkg/runtime/engine/singularity/config/config.go
Address #487 by adding a `--no-eval` actions flag, which does the following:
1) Quotes environment variable values in the `inject-singularity-env.sh` generated script using single quotes to
ensure the values are not evaluated when the injection script is sourced.
_This behavior applies to existing and newly created images._
2) Uses an alternate path in the generated runscript for images built from OCI sources, that avoids evaluating CMD / ENTRYPOINT parts, and args in the shell.
_This behavior only applies to newly created images, that contain the new form of the generated OCI runscript._
The `--no-eval` flag is implictly added by the Docker/OCI `--compat` mode.
Also adds test cases that cover this new functionality, the historic behavior, and general handling of CMD / ENTRYPOINT/ …
> feat: Add --no-eval for OCI compatible argument and env var handling

- debian/control
- dist/rpm/singularity-ce.spec.in
- mconfig
* [fix: Match mconfig min go version to go.mod](https://github.com/sylabs/singularity/commit/d684010ac96cb26481f8b0bda7dbe4b3cbf10353)
* [rpm: Tidy Requires / Conflicts etc.](https://github.com/sylabs/singularity/commit/3c096b131505d5476b17d31a061ab3585a4d2033)
* Add runtime libeccomp / libseccomp2 dependency.
* Remove `Obsoletes` for `singularity-ce-runtime`... we didn't ever
have any 2.x packaging with a of CE, so there wasn't a split runtime
package.
* Add conflicts for Apptainer (which has a /usr/bin/singularity). 
* [deb: Tidy Requires / Conflicts etc.](https://github.com/sylabs/singularity/commit/4284f9b2945b6a8d93094c27e5498e7dc25148eb)
* Add libseccomp2 runtime dependency.
* Add conflicts with apptainer that provides /usr/bin/singularity.
- Fixes #714 
- Fixes #715 
- Read the …
> Build / packaging cleanup (go check & conflicts / obsoletes/ deps)

- CHANGELOG.md
- internal/pkg/build/oci/oci.go
- internal/pkg/build/oci/oci_test.go
- internal/pkg/client/oci/pull.go
Use a HEAD request when checking digest of remote OCI image sources, via the `docker.GetDigest` function in containers/image.
Previously we were using `GetManifest` and computing the hash ourselves. This is a complete GET, and counts against Docker Hub  API limits even if the cached image is up-to-date.
Note - filename of generated SIF in cache is now `<alg>.<digest>`, previously `<digest>`. Storing the algorithm in the filename prevents conflicts if there is a switch from `sha256` to something else.
Example requests pulling an image that's already cached:
**Before this PR**
One GET against `/v2/` to check API availability (no impact on API limits)
One GET against manifest URL (**counts against API limits**)
```
172.17.0.1 - - [21/Apr/2022:23:16:38 +0000] "GET /v2/ HTTP/1.1" 200 2 "" …
```
> fix: Use HEAD request to check remote OCI image digest

- CHANGELOG.md
- LICENSE_DEPENDENCIES.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- cmd/internal/cli/cgroups.go
- cmd/internal/cli/cgroups_test.go
- e2e/cgroups/cgroups.go
- examples/plugins/config-plugin/main_linux.go
- go.mod
- go.sum
- internal/pkg/cgroups/config_linux.go
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/test/tool/require/require.go
- pkg/cmdline/flag.go
- pkg/runtime/engine/singularity/config/config.go
**feat: Add CLI action flags to apply cgroups limits**
Add CLI action flags that apply cgroups limits without needing the user to write a cgroups TOML file.
Most of the flags supported by Docker are now present, with the exception of `--device-` flags which will be considered later.
Note that only the long form of these flags is supported. The short form of e.g. `--cpus` is `-c` which would clash with existing use in
singularity.
To implement, a JSON serialization of the LinuxResources structures is now passed through the engine configuration. Where a TOML file is used with `--apply-cgroups` it is now read and serialized to JSON, rather than passing the path to the file through to the engine.
At a later date we can/should rationalize our handing of the structures. We should likely accept …
> feat: Add CLI action flags to apply cgroups limits

- internal/pkg/build/oci/oci.go
PR #727 was written while reviewing the Docker registry API v2 spec, in which it is stated a manifest HEAD request does include
`Docker-Content-Digest`.
I had not considered potential differences in the oci-distribution-spec. This makes it clear that `Docker-Content-Digest` is a SHOULD header, and lists it as a field clients should not depend on.
The `containers/image` `docker.GetDigest` function doesn't handle the lack of a `Docker-Content-Digest` header, so we should fall-through to the old `GetManifest` approach on error.
- Fixes #733
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) …
> fix: Add fall-through for missing Docker-Content-Digest (release-3.9)

- .circleci/config.yml
- INSTALL.md
CI stays at 1.17.9 due to plugin known issue.
Install docs were showing 1.18 so bump to 1.18.1.
- …
> ci: bump to Go 1.17.9 (release-3.9)

- .circleci/config.yml
- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- cmd/starter/c/include/starter.h
- cmd/starter/c/starter.c
- cmd/starter/main_linux.go
- e2e/actions/actions.go
- internal/app/starter/cleanup_host.go
- internal/app/starter/master_linux.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
- internal/pkg/runtime/engine/engine_linux.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/runtime/engine/singularity/cleanup_host_linux.go
- internal/pkg/runtime/engine/singularity/cleanup_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/util/bin/bin.go
- pkg/runtime/engine/singularity/config/config.go
- pkg/util/singularityconf/config.go
Allow SIF images to be mounted with `squashfuse` in the unpriv / user-namespace flow.
The approach take here is to:
* Leverage the `MountFUSE` / `UnmountFUSE` functionality from sylabs/sif, rather than duplicating code.
* Perform the mount onto a temporary directory in the CLI layer, at the point where the SIF would otherwise be extracted. The singularity runtime then sees a sandbox.
* Add a 'CLEANUP_HOST' process that is forked from `starter` early, before any namespace manipulation. This process is able to unmount the SIF at cleanup time. A socket from the host cleanup process to the master process is used for coordination.
Mount at the CLI layer, rather than inside of the runtime engine, is used so that we can adopt a similar approach across `singularity oci` commands, and general use …
> feat: squashfuse unpriv SIF image mount (experimental)

- CHANGELOG.md
- e2e/key/key.go
- pkg/sypgp/sypgp.go
Cherry pick https://github.com/apptainer/apptainer/pull/99 - except keep reliance on default Sylabs key server in tests.
Original PR description:
This fixes a few problems with searching on the https://keys.openpg.org/ key server:
- Lines read needed trimming because of a trailing carriage return.
- The name/email portion needed to be url-decoded.
- There is not always exactly one name/email/uid; sometimes there are zero (if no email addresses have been confirmed), one as normal, or more than one if there are multiple uids associated with a key.
In addition, this renames several variables which had misleading names, and consolidates duplicate code in the formatting functions.
- Fixes #495 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTI …
> fix: key search results for keys.openpgp.org and multiple names on a key (apptainer 99)

- CHANGELOG.md
- e2e/env/env.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/util/fs/files/action_scripts.go
Since 3.6.0 we have been passing the entire host environment into the action script, it being stored with a single env var there. We use a newline as our IFS when processing this later on. This requires replacing newlines with some other char or string. To date we have been using the standard `\n` as the replacement. However, this means that any host env var containing a literal `\n` cannot be faithfully passed into the container.
There is no easy perfect solution to this at present.
We cannot do a full escaping of the host env vars, as reversing this in our action script requires either:
* Iterative processing on unescape, as look-ahead is important to understand the context of any `\`. This would be extremely messy and slow to implement in shell code, and impact maintainability in this …
> fix: Handle literal escaped newline \n in host environment vars

- debian/control
The binary package is `libglib2.0-0` even if the headers are in `libglib2.0-dev` without the `-0`.
Also, the deb package build doesn't validate the requires, so my local test build did not catch this one. :cry: 
- Fixes #768
- Based this PR against the …
> deb: fix runtime libglib2.0-0 dependency

- docs/content.go
The current help sections are somewhat out of order with respect to the actual processing, and this is a quick and easy fix to change the order to better reflect the actual processing. I added a small note at the top to explain labels / env from post, and we can discuss tweaking this to add more detail (or remove if desired). 
- Fixes https://github.com/sylabs/singularity/issues/460
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> docs: updating singularity help build for sections to reflect order

- CHANGELOG.md
- cmd/internal/cli/actions_linux.go
- cmd/starter/c/include/starter.h
- cmd/starter/c/starter.c
- e2e/actions/actions.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/util/starter/starter.go
The experimental `--sif-fuse` code was attempting to pass the boolean that controls whether starter spawns the CleanupHost process, for unmounting the FUSE SIF mount, in the starter config structure.
The starter config structure is setup from the Go engine 'prepare' code, which runs in stage1 *after* the point at which CleanupHost is
spawned from the starter C code... so the boolean was never true.
Unfortunately, all the tests we have were passing, because due to a bad negation in an if statement, the `CleanupHost` process
was *always* executed.
Switch to using an env var (`CLEANUP_HOST`) to control whether the `CleanupHost` process is spawned by starter. This is the right way to control starter behavior that needs to occur before 'prepare' in stage1. It's the same approach used to …
> fix: Pass CleanupHost boolean to starter correctly

- .github/dependabot.yml
- RELEASE_PROCEDURE.md
Ensure `release-3.10` branch is monitored by Dependabot. Leaving `release-3.9` branch for now until 3.10 ships.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRI …
> ci: add release-3.10 branch to Dependabot config

- CHANGELOG.md
- INSTALL.md
docs: markdown changes for 3.10.0 release …
> docs: markdown changes for 3.10.0 release

- .github/dependabot.yml
chore: disable dependabot for release-3.9
3.9 is now an archived release. …
> chore: disable dependabot for release-3.9

- CHANGELOG.md
- CONTRIBUTORS.md
- cmd/internal/cli/cgroups.go
Singularity fails to build from source on mips archs and chokes with: 
```
../cmd/internal/cli/cgroups.go:302:26: cannot use stat.Rdev (variable of type uint32) as type uint64 in argument to unix.Major
../cmd/internal/cli/cgroups.go:302:56: cannot use stat.Rdev (variable of type uint32) as type uint64 in argument to unix.Minor
make[2]: *** [Makefile:178: singularity] Error 2
```
Full log [here](https://buildd.debian.org/status/fetch.php?pkg=singularity-container&arch=mips64el&ver=3.10.0%2Bds2-1&stamp=1655166544&raw=0)
It seems to stem from Rdev being defined as uint32 on mipsel, relevant discussion on go forum [here](https://forum.golangbridge.org/t/the-argument-rdev-is-defined-as-type-uint32-in-mips-arch-and-uint64-in-others/21179/6)
This patch fixes the build on mips64el and mipsel.
> mipsel build failure fix: Cast Rdev to uint64 in call to unix.Minor

- CHANGELOG.md
- e2e/README.md
- e2e/internal/testhelper/testhelper.go
- e2e/suite.go
- mlocal/frags/Makefile.stub
- scripts/e2e-test
- scripts/go-test.in
The e2e test suite is cumbersome for developers. To date it has not
been possible to run a subset of tests without commenting out portions
of the `suite.go` and group specific test code.
Add an `E2E_GROUPS` argument to the `make e2e-test` target that will
allow developers to run only the specificed groups of e2e tests.
Add an `E2E_TESTS` argument to the `make e2e-test` target that takes a
regexp to filter the top-level test names that will be run.
make -C builddir e2e-test E2E_GROUPS=VERSION,HELP
To run specific top-level tests (as defined in the `testhelper.Tests`
struct returned by each group's `E2ETests` function) supply a regular
expression in an `E2E_TESTS` argument to the make target:
make -C builddir e2e-test E2E_TESTS=^semantic
You can combine the `E2E_GROUPS` and `E2E_TESTS` …
> e2e: Add E2E_GROUPS & E2E_TESTS to filter e2e test runs

- CHANGELOG.md
- e2e/imgbuild/regressions.go
- e2e/testdata/regressions/issue_4967.def
- internal/pkg/build/build.go
- internal/pkg/build/stage.go
The issue_4967 build regression test was attempting to verify `-c` handling on `%post` and `%test` through `%test -c /bin/bash`.
Handling of `-c` on `%test` is not actually implemented, but the test was passing as the `%test` script passed okay.
Modify the test so that it is actually checking a `%post` script with `-c ...` is invoked as expected. We can leverage the fact that `/bin/sh` on busybox can also be called with `/bin/busybox sh`, which we can then observe on the `/proc/$$/cmdline` in the `%post` block.
While we are here, make the comment and function name for execution of `%pre` and `%setup` scripts on the *host* consistent and more obvious.
- Fixes #871
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms …
> e2e: fix: correctly test `%post -c` for regression 4967

- CHANGELOG.md
- internal/pkg/build/metadata.go
- pkg/build/types/parser/deffile_test.go
- pkg/build/types/parser/testdata_good/shebang_test/shebang_test
- pkg/build/types/parser/testdata_good/shebang_test/shebang_test.json
Akin to start and run, a user might want a test file to use a custom hashbang. This was basically all ready to go and just needed to be extended to the test script! I was not sure where to write tests so I will wait for guidance on that.
This request came from Twitter! https://twitter.com/ifndef_define/status/1536689964225908737 As I noted above I still need to add a test, and will do so with further guidance. I indeed have tested manually/locally and it looks good! :partying_face: 
Signed-off-by: vsoch <vsoch@users.noreply.github.com>
> adding support for test to have a custom shell

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- e2e/actions/actions.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- pkg/runtime/engine/singularity/config/config.go
Add `bind-paths` option for the `--no-mount` flag. This will disable mounting all of the `bind path` entries set in `singularity.conf`.
Previously, `bind path` entries could only be disabled one-by-one by specifying their absolute path.
- Fixes #883
- Based this …
> feat: `bind-paths` option for `--no-mount` flag

- CHANGELOG.md
- cmd/internal/cli/singularity.go
- internal/pkg/build/stage.go
- internal/pkg/image/unpacker/squashfs.go
- internal/pkg/image/unpacker/squashfs_singularity.go
- pkg/cmdline/flag.go
Allow debug output to be turned on from a `SINGULARITY_DEBUG` env var.
Pass debug env var down through nested calls to `singularity` in
wrapped unsquashfs and build stages so that we can see the full debug
output for those.
- Fixes #884
- Based this PR against …
> feat: SINGULARITY_DEBUG env var, and nested debug

- pkg/network/network_linux_test.go
Fixes confusing error on EL9, Fedora etc. where IP address needs to be
given for the nc -l flag.
- Fixes #838 …
> fix: use correct args for nc in network_linux_test.go

- e2e/testdata/sshfs.def
Our sshfs tests must use an image where the ssh key is rsa-sha2, so
that it is compatible with the EL9 default crypto policy.
- Fixes #839  …
> e2e: use rsa-sha2 ssh-key in sshfs test

- CHANGELOG.md
- cmd/internal/cli/actions_linux.go
- e2e/cgroups/cgroups.go
- e2e/testdata/cgroups/cpu_success.toml
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/util/shell/interpreter/interpreter.go
**feat: enable cgroups for non-root instances**
Our existing method for joining an instance cgroup with an action on an `instance://` does not work for non-root instances, without a
usernamepace - so we blocked non-root instances with cgroups. The existing code attempts to move its parent ID (the starter main process), into the instance cgroup. This will receive an operation not permitted error.
We can work around by having the CLI process directly join the cgroup, so that everything is spawned within the instance cgroup.
Also modify e2e cgroups tests to verify this functionality, and correct unintentional test skips in rootless flow.
**e2e: use cpu controller instead of cpuset for cgroups test**
The cpuset controller may not be delegated by default on many distributions.
**fix: handle …
> feat: enable cgroups for non-root instances

- cmd/internal/cli/actions_linux.go
`if err :=` was incorrectly used in #711, resulting in a nil error return.
- Fixes #897  …
> fix: ensure wrapped unsquashfs error is displayed to user

- CHANGELOG.md
- INSTALL.md
Update CHANGELOG.md & INSTALL.md for 3.10.1 …
> docs: CHANGELOG.md / INSTALL.md update for 3.10.1

- CONTRIBUTORS.md
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/oci/oci_test.go
- internal/pkg/build/sources/base_environment_test.go
- internal/pkg/build/sources/conveyorPacker_oci_test.go
- internal/pkg/image/packer/squashfs_test.go
- internal/pkg/image/unpacker/squashfs_test.go
- internal/pkg/util/crypt/crypt_dev_test.go
- internal/pkg/util/fs/helper_linux_test.go
- internal/pkg/util/fs/layout/manager_test.go
- internal/pkg/util/gpu/paths_test.go
- pkg/build/types/bundle_test.go
- pkg/image/ext3_test.go
- pkg/image/image_test.go
- pkg/image/sandbox_test.go
- pkg/image/squashfs_test.go
- pkg/network/network_linux_test.go
- pkg/ocibundle/sif/bundle_linux_test.go
- pkg/sypgp/sypgp_test.go
- pkg/util/archive/copy_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
- Added …
> test: use `T.TempDir` to create temporary test directory

- internal/pkg/build/sources/conveyorPacker_oci.go
PR https://github.com/sylabs/singularity/pull/915 picked an apptainer fix that prevents empty blocks in the OCI generated runscript using additional Go template if/else logic.
This approach works, but is more complex than adding a shell 'no-op' to avoid the empty if block. Inserting shell no-op ':' commands also preserves the full structure of the runscript always.
- Fixes #914  …
> Replace #915 with simpler runscript no-op fix

- e2e/docker/docker.go
correct docker --no-eval no args test cases
They were not using `--no-eval`, when they should be. Other test cases are consistent and correct.
- Fixes #922 …
> e2e: correct docker --no-eval no args test cases

- e2e/docker/docker.go
e2e: correct docker --no-eval no args test cases
- Fixes #922  …
> e2e: correct docker --no-eval no args test cases (release-3.10)

- .circleci/config.yml
- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions_linux.go
- cmd/internal/cli/build_linux.go
- e2e/imgbuild/imgbuild.go
- e2e/testdata/proot_alpine.def
- e2e/testdata/proot_centos.def
- e2e/testdata/proot_ubuntu.def
- examples/docker/Singularity
- examples/library/Singularity
- internal/pkg/build/build.go
- internal/pkg/build/stage.go
- internal/pkg/util/bin/bin.go
Non-root users can now build from a definition file, on systems that do not support `--fakeroot`. This requires the statically built `proot` command (<https://proot-me.github.io/>) to be available on the user `PATH`. 
These builds:
- Do not support `arch` / `debootstrap` / `yum` / `zypper` bootstraps. Use `localimage`, `library`, `oras`, or one of the docker/oci sources.
- Do not support `%pre` and `%setup` sections.
- Run the `%post` sections of a build in the container as an emulated root user.
- Run the `%test` section of a build as the non-root user, like `singularity test`.
- Are subject to any restrictions imposed in `singularity.conf`.
- Incur a performance penalty due to `proot`'s `ptrace` based interception of syscalls.
- May fail if the `%post` and `%test` scripts require …
> feat: non-root, non --fakeroot builds with proot

- CHANGELOG.md
- internal/pkg/build/metadata.go
In Singularity 2.x the bootstrap_history directory was always
populated with any existing definition file, when an existing image
was used as the source for a build.
It appears that in 3.x this was gated behind a conditional, limiting
it to builds that are explicitly `--update` only. This does not
reflect the documentation or 2.x, so remove this conditional.
- Fixes #935 
- Added tests to validate this PR, linted with …
> fix: Ensure bootstrap_history directory populated

- CHANGELOG.md
- internal/pkg/build/metadata.go
In Singularity 2.x the bootstrap_history directory was always
populated with any existing definition file, when an existing image
was used as the source for a build.
It appears that in 3.x this was gated behind a conditional, limiting
it to builds that are explicitly `--update` only. This does not
reflect the documentation or 2.x, so remove this conditional.
- Fixes #935 
- Added tests to validate this PR, linted with …
> fix: Ensure bootstrap_history directory populated (release-3.10)

- e2e/actions/regressions.go
- e2e/cache/cache.go
- e2e/cache/regressions.go
- e2e/cmdenvvars/cmdenvvars.go
- e2e/env/env.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/singularitycmd.go
- e2e/pull/pull.go
- e2e/sign/sign.go
- e2e/suite.go
The SingularityCmd construct used to execute singularity in the e2e tests has defaulted to a fresh, empty cache directory for each execution.
This means that we are downloading full container images on every e2e execution of singularity against docker or library, which slows things down and creates uneccesary request load on the Sylabs Library, Docker Hub, etc.
Switch to using a shared cache by default. Our cache structure has been concurrency safe (given atomic operations on local filesystems) for some time now :crossed_fingers: ... this will also now test that.
Pull tests are modified so that they explicitly use an empty cache, to test the entire pull flow, including container image download.
Any future tests that depend on exercising downloads, the cache specifically, or depend on a …
> e2e: switch to shared cache by default

- e2e/actions/regressions.go
- e2e/cache/cache.go
- e2e/cache/regressions.go
- e2e/cmdenvvars/cmdenvvars.go
- e2e/env/env.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/singularitycmd.go
- e2e/pull/pull.go
- e2e/sign/sign.go
- e2e/suite.go
Cherry pick #975 to release 3.10
The SingularityCmd construct used to execute singularity in the e2e tests has defaulted to a fresh, empty cache directory for each execution.
This means that we are downloading full container images on every execution, which slows things down and creates unneccesary request load on the Sylabs Library, Docker Hub, etc.
Switch to using a shared cache by default.
Pull tests are modified so that they explicitly use an empty cache, to test the entire pull flow, including container image download.
Any future tests that depend on exercising downloads, the cache specifically, or depend on a specific state / order of cached operations will need to also specify their own cache directory.
- Fixes #
- Read the [Guidelines for …
> e2e: switch to shared cache by default (release 3.10)

- go.mod
- internal/app/singularity/remote_status.go
- pkg/util/user-agent/agent.go
Replace use of [func strings.Title](https://pkg.go.dev/strings#Title), which was deprecated in Go 1.18 ([ref](https://go.dev/doc/go1.18#strings)).
> Replace Deprecated Title Function (release-3.10)

- e2e/actions/actions.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/env/env.go
- e2e/env/regressions.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/instance/instance.go
- e2e/pull/concurrency.go
- e2e/pull/pull.go
- e2e/testdata/regressions/issue_4203.def
- e2e/testdata/regressions/issue_4820.def
- e2e/testdata/regressions/issue_4969.def
- e2e/testdata/regressions/issue_5250.def
- e2e/testdata/sshfs.def
E2E tests using docker:// sources cannot run in parallel with caching, due to issues with concurrency and the containers/image oci/layout. We want to use caching as many tests rely on the same image, and Docker Hub rate limiting is still an issue where it is not trivial to provide credentials.
This changeset:
* Replaces some docker:// sources with equivalent library:// sources, in tests that are not explicitly for verifying docker specific
behavior. library:// caching is concurrency safe on local fs with atomic operations (such as CI), allowing a speed-up.
* Removes some redundant docker:// source tests from env/imgbuild etc. which are already covered by the docker group.
* Moves all remaining docker:// source tests into the e2e.docker group, so that all tests using Docker Hub are …
> e2e: Re-work docker / pull related e2e tests

- e2e/actions/actions.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/env/env.go
- e2e/env/regressions.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/instance/instance.go
- e2e/pull/concurrency.go
- e2e/pull/pull.go
- e2e/testdata/regressions/issue_4203.def
- e2e/testdata/regressions/issue_4820.def
- e2e/testdata/regressions/issue_4969.def
- e2e/testdata/regressions/issue_5250.def
- e2e/testdata/sshfs.def
E2E tests using docker:// sources cannot run in parallel with caching, due to issues with concurrency and the containers/image oci/layout. We want to use caching as many tests rely on the same image, and Docker Hub rate limiting is still an issue where it is not trivial to provide credentials.
This changeset:
* Replaces some docker:// sources with equivalent library:// sources, in tests that are not explicitly for verifying docker specific behavior. library:// caching is concurrency safe on local fs with atomic operations (such as CI), allowing a speed-up.
* Removes some redundant docker:// source tests from env/imgbuild etc. which are already covered by the docker group.
* Moves all remaining docker:// source tests into the e2e.docker group, so that all tests using Docker Hub are …
> e2e: Re-work docker / pull related e2e tests (3.10)

- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/env/env.go
- e2e/env/regressions.go
- e2e/imgbuild/regressions.go
Two e2e tests with docker sources were missed in #982 due to a case-sensitive search for bootstrap: docker.
Move one to the docker e2e group. Modify the other to use a library alpine image. …
> e2e: address two missed docker sources from #982

- e2e/imgbuild/imgbuild.go
- e2e/pull/pull.go
One E2E PULL test manipulates the process umask. To avoid causing permissions issues in other tests it must be run alone, in the SEQ section of the E2E suit, via testhelper.NoParallel.
Convert IMGBUILD def file tests docker -> library
- Based this PR against the …
> e2e: fix further concurrency issues

- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/env/env.go
- e2e/env/regressions.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/pull/pull.go
Cherry pick #984 and #986 to release-3.10
**e2e: address two missed docker sources from #982**
Two e2e tests with docker sources were missed in #982 due to a case-sensitive search for bootstrap: docker. Move one to the docker e2e group. Modify the other to use a library alpine image.
**e2e: fix umask manipulation concurrency issue**
One E2E PULL test manipulates the process umask. To avoid causing permissions issues in other tests it must be run alone, in the SEQ section of the E2E suit, via testhelper.NoParallel.
**e2e: Convert IMGBUILD def file tests docker -> library** …
> e2e: pick fixes #984 and #986 (3.10)

- .circleci/config.yml
- .golangci.yml
- e2e/instance/instance_utils.go
- e2e/sign/sign.go
- internal/pkg/build/sources/conveyorPacker_local.go
- internal/pkg/build/sources/conveyorPacker_shub.go
- internal/pkg/cache/cache.go
- internal/pkg/client/progress.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
Bump `golangci-lint` to v1.49. Replace deprecated `deadcode` linter with `unused`. Address various lint.
> Bump golangci-lint to v1.49 (master)

- .circleci/config.yml
- .golangci.yml
- e2e/instance/instance_utils.go
- e2e/sign/sign.go
- internal/pkg/build/sources/conveyorPacker_local.go
- internal/pkg/build/sources/conveyorPacker_shub.go
- internal/pkg/cache/cache.go
- internal/pkg/client/progress.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
- pkg/sylog/sylog.go
Bump `golangci-lint` to v1.49. Replace deprecated `deadcode` linter with `unused`. Address various lint.
> Bump golangci-lint to v1.49 (release-3.10)

- e2e/pull/pull.go
The test manipulates remotes, so no other library operations may run at the same time. …
> e2e: pull regression test 5808 must be non-parallel

- e2e/pull/pull.go
The test manipulates remotes, so no other library operations may run at the same time. …
> e2e: pull regression test 5808 must be non-parallel (release-3.10)

- internal/pkg/build/sources/conveyorPacker_yum.go
Fedora 36 now uses `%{_usr}/lib/sysimage/rpm` as the rpm dbpath. Previously we errored out on anything except `%{_var}/lib/rpm`. We need to accept the new path so that Fedora 36 can bootstrap itself. We need to warn that bootstrapping older distributions may require setting the old path in an `~/.rpmmacros` file.
- Fixes #902  …
> fix: permit rpm bootstrap on Fedora 36

- .circleci/config.yml
- internal/pkg/cgroups/manager_linux.go
- pkg/util/archive/copy.go
Bump golangci-lint to 1.50.
Silence contextcheck warnings that are for a path through dependencies we cannot modify.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUT …
> chore: bump golangci-lint to 1.50 (release-3.10)

- .circleci/config.yml
- internal/pkg/cgroups/manager_linux.go
- pkg/util/archive/copy.go
Bump golangci-lint to 1.50.
Silence contextcheck warnings that are for a path through dependencies we cannot modify.
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUT …
> chore: bump golangci-lint to 1.50 (main)

- CHANGELOG.md
- mlocal/frags/Makefile.stub
Avoids including conmon binary or intermediate build files in the dist tar.gz.
- Fixes #941
- Added myself …
> makefile: make clean on conmon sources in make dist

- CHANGELOG.md
- examples/plugins/ubuntu-userns-overlay-plugin/README.md
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- pkg/plugin/callback/runtime/engine/singularity/singularity.go
- pkg/util/singularityconf/config.go
Mark the callback and the config entry for image driver plugins deprecated.
- Fixes #1051
- Added myself as …
> deprecate image driver plugins

- CHANGELOG.md
- cmd/internal/cli/pull.go
- docs/content.go
- docs/remote.go
- e2e/pull/pull.go
- e2e/pull/regressions.go
- e2e/remote/remote.go
- e2e/verify/verify.go
- etc/remote.yaml
- internal/app/singularity/push.go
- internal/pkg/build/remotebuilder/remotebuilder_test.go
- internal/pkg/build/sources/conveyorPacker_library_test.go
- internal/pkg/remote/endpoint/service.go
- internal/pkg/remote/remote_test.go
Due to issues with the sylabs.io domain, SCS endpoints are currently hosted at sycloud.io.
Adjust references in the code to unblock CI and development work at this point. The URIs are expected to remain valid on restoration of the sylabs.io domain, but this PR is likely to be rolled back. …
> Point at sycloud.io SCS endpoints

- CHANGELOG.md
- cmd/internal/cli/pull.go
- docs/content.go
- docs/remote.go
- e2e/pull/pull.go
- e2e/pull/regressions.go
- e2e/remote/remote.go
- e2e/verify/verify.go
- etc/remote.yaml
- internal/app/singularity/push.go
- internal/pkg/build/remotebuilder/remotebuilder_test.go
- internal/pkg/build/sources/conveyorPacker_library_test.go
- internal/pkg/remote/endpoint/service.go
- internal/pkg/remote/remote_test.go
Due to issues with the sylabs.io domain, SCS endpoints are currently hosted at sycloud.io.
Adjust references in the code to unblock CI and development work at this point. The URIs are expected to remain valid on restoration of the sylabs.io domain, but this PR is likely to be rolled back. …
> Point at sycloud.io SCS endpoints (release-3.10)

- CHANGELOG.md
- pkg/util/capabilities/capabilities.go
Add support for:
* CAP_PERFMON (Linux 5.8)
* CAP_BPF (Linux 5.8)
* CAP_CHECKPOINT_RESTORE (Linux 5.9)
- Fixes #1071
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTI …
> Support additional Linux capabilities

- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/internal/e2e/profile.go
- e2e/internal/e2e/singularitycmd.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Depends on #1021
Add an `--oci` flag to actions (run/shell/exec) that calls the (no-op) OCI launcher instead of the singularity native runtime launcher.
Fix OCI launcher supported option checks for empty structs (not just nils), and always set options.
Add E2E profiles and a test for unimplemented error on the --oci option.
- Fixes #1022  …
> actions: Add --oci flag to call OCI launcher

- cmd/starter/c/starter.c
- internal/pkg/util/gpu/nvidia.go
Ensure that CAP_NET_ADMIN is set in the ambient set in nvccli Go code.
In addition:
* Tidy up the Go code so that capabilities are ordered the same as in starter code, for easy comparison.
* Remove a redundant addition of CAP_MKNOD in starter (already set in line above).
- Fixes #1075
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible …
> fix: set CAP_NET_ADMIN with --nvccli

- cmd/starter/c/include/capability.h
In #1072, additional capabilities were added in Go code. The C starter code uses a loop up to CAPSET_MAX when reconciling capabilities vs supported on the machine. Because CAPSET_MAX was still 37, not 40, it failed to trim the 3 upper capabilities that are unsupported on older kernels.
Correct CAPSET_MAX to fix the issue on older kernels.
- Fixes #1079
- Added tests to validate this PR, linted with `make check`  and …
> fix: correct CAPSET_MAX for changes in #1072

- CHANGELOG.md
- e2e/actions/regressions.go
- e2e/config/config.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/util/fs/overlay/overlay_linux.go
When we are running a container in a user namespace, check whether the kernel supports rootless overlay. If it does, use this instead of underlay.
At present, the visible effects of this are that:
* When running under a user namespace, on a supported system, the overlay session layout is used. The rootfs in the container will appear as an overlay fs mount.
* When running under a user namespace, on a supported system, the `--writable-tmpfs` option can be used, with the same semantics as in set-uid mode.
Note that this changeset does not allow unprivileged persistent overlays (singularity `--overlay` flag). It will be possible to enable
unprivileged overlay directory mounts at a later point, and potentially other overlay mounts via FUSE drivers.
The principle benefit at this stage is to …
> feat: Allow kernel supported unpriv overlay

- CHANGELOG.md
- e2e/pull/pull.go
- e2e/pull/regressions.go
- internal/pkg/client/progress.go
When an http(s) pull doesn't provide a content-length header, we need to ensure the progress bar completes. If we don't do this, the CLI hangs indefinitely.
- Fixes #1087 …
> fix: don't freeze for http(s) pull without content-length

- e2e/cache/cache.go
- e2e/cache/regressions.go
When testing the cache commands in the e2e tests, pull from a local http server, rather than the library. This dramatically speeds up the time taken to run these tests, which are necessarily sequential.
```
Before
--- PASS: TestE2E/SEQ/CACHE (121.30s)
After
--- PASS: TestE2E/SEQ/CACHE (4.94s)
```
- Fixes #1089
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and …
> e2e: Use local http source for cache tests

- .circleci/config.yml
- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/ecl/ecl.go
- e2e/env/env.go
- e2e/env/regressions.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/internal/e2e/image.go
- e2e/overlay/overlay.go
- e2e/pull/pull.go
- e2e/run/run.go
- e2e/sign/sign.go
As much as easily possible, replace use of a library pull with a local busybox or built alpine test image.
Remove redundant docker pulls, that aren't really testing anything additional.
Move docker tests that are very slow, or pulling from local registries, to be parallel again. Modify these tests so that they use `--disable-cache` to avoid docker cache concurrency issues. The other ordered tests are checking the path pulling through the cache.
With these changes, e2e parallelism is better, so it is sensible to use a `resource_class: large` VM for e2e only.
- Fixes #913  …
> Minimize e2e library / docker pulls

- e2e/pull/concurrency.go
Use temporary config for concurrent pull tests. Ensures we are not in the middle of modifying the global config while other tests are running.
- Fixes #1101  …
> e2e: use temp config for concurrent pull tests

- e2e/docker/docker.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/internal/e2e/imageverify.go
The e2e ImageVerify function is currently running under a passed-in profile. When the profile is userns, or fakeroot, this will require extraction of a SIF image to sandbox before inspection.
Builds should always create an image that is executable by a normal user, so we can always use the UserProfile and avoid the extractions.
- Fixes #1103 …
> e2e: always use UserProfile for ImageVerify

- .circleci/config.yml
- CHANGELOG.md
- cmd/internal/cli/actions.go
- cmd/internal/cli/instance_start_linux.go
- cmd/internal/cli/startvm.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/oci/oci.go
- internal/pkg/runtime/launcher/launcher.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/oci_conmon_linux.go
- internal/pkg/runtime/launcher/oci/oci_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/util/bin/bin.go
As a first step toward run/shell/exec actions on native OCI images, implement a minimal `singularity run --oci mybundle` which:
* Requires an on-disk bundle with appropriate `config.json`.
* Runs this bundle using `crun` or `runc`.
* Makes no attempt to handle any arguments or options.
* Does not modify the `config.json` - i.e. it must match namespace / mapping requirements for rootless execution etc.
At this stage, the functionality is essentially equivalent to `singularity oci run` and is not yet useful.
The primary purpose of the PR is to refactor some of the code that passes args for launching a container.
In addition, we now use `crun` in preference to `runc` if available. `crun` supports e.g. single uid->uid mapping in a usernamespace (without root mapping).
- Fixes #598
- Read the …
> feat: run action for OCI bundle

- e2e/actions/actions.go
The actionUmask and actionCompat tests manipulate the process umask. They should be run in the SEQ (non-parallel) section of the end to end tests.
- Fixes #1111 …
> e2e: Move umask manipulating tests to SEQ

- e2e/actions/actions.go
In the actions.fuseMount test, don't just write to the STDIN pipe for the sshfs container, close it also. This ensures `cat > /dev/null`  in the container will see EOF and exit.
- Fixes #1114  …
> e2e: close pipe to actions.fuseMount sshfs container

- CHANGELOG.md
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
When the user's container exits, fakeroot cleanup runs `rm` though the fakeroot engine to remove a temporary container directory, extracted from a SIF image, where necessary.
Under high load / parallelism, on some distros / kernels, execution of fakeroot tempdir cleanup can become stuck. See https://github.com/sylabs/singularity/issues/1109 for discussion of a reproducer.
The fakeroot engine MonitorContainer code sits in a loop waiting for signals. It requires a SIGCHLD to be received before it will wait4 on the child process, to confirm it has exited.
Debug logging showed that sometimes a SIGCHLD was not received by this code. It is not clear why, as `signal.Notify` is set early, and the signals channel buffer is not being filled. The behavior varies between distributions / kernels. It …
> fix: Wait directly in fakeroot MonitorContainer 

- CHANGELOG.md
- e2e/pull/pull.go
- e2e/pull/regressions.go
- internal/pkg/client/progress.go
When an http(s) pull doesn't provide a content-length header, we need to ensure the progress bar completes. If we don't do this, the CLI hangs indefinitely.
- Fixes #1087 …
> fix: don't freeze for http(s) pull without content-length (release-3.10)

- .circleci/config.yml
- e2e/cgroups/cgroups.go
Update CI image to Ubuntu 22.04 LTS.
With cgroups v2 this now enables the rootless cgroups tests, which require a dbus user session. The CI image doesn't include the relevant package, so we need to install that too.
The e2e tests job now includes some workaround to make the CI agent spawned job provide an environment that's more typical for a user... undoing some things the CI image does to help out headless browser test tools. We must have a user dbus and a delegated cgroup for all of the rootless cgroups tests to be possible. …
> chore(ci): update to Ubuntu 22.04

- CHANGELOG.md
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
When the user's container exits, fakeroot cleanup runs `rm` though the fakeroot engine to remove a temporary container directory, extracted from a SIF image, where necessary.
Under high load / parallelism, on some distros / kernels, execution of fakeroot tempdir cleanup can become stuck. See #1109 for discussion of a reproducer.
The fakeroot engine MonitorContainer code sits in a loop waiting for signals. It requires a SIGCHLD to be received before it will wait4 on the child process, to confirm it has exited.
Debug logging showed that sometimes a SIGCHLD was not received by this code. It is not clear why, as `signal.Notify` is set early, and the signals channel buffer is not being filled. The behavior varies between distributions / kernels. It is sometimes easy to trigger, and sometimes …
> fix: Wait directly in fakeroot MonitorContainer (release-3.10)

- e2e/pull/concurrency.go
The default download concurrency is 3, so it is exercised in all other library pull operations. We don't need to explicitly test it. …
> e2e: remove pull concurrency 3 check

- .circleci/config.yml
- CHANGELOG.md
- INSTALL.md
Bump go to 1.19.3
Update docs for 3.10.4 …
> chore: pick 3.10.4 release prep to main

- cmd/internal/cli/actions.go
- cmd/internal/cli/oci_linux.go
- e2e/actions/oci.go
- internal/app/singularity/oci_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- pkg/ocibundle/bundle.go
- pkg/ocibundle/native/bundle_linux.go
- pkg/ocibundle/native/bundle_linux_test.go
- pkg/ocibundle/sif/bundle_linux.go
- pkg/ocibundle/sif/bundle_linux_test.go
When running containers in `--oci` mode, the argument to run is now an image reference corresponding to a native OCI format handled by containers/image, i.e.
* docker://
* docker-archive:
* docker-daemon:
* oci-archive:
* oci:
The source image is extracted into a temporary OCI bundle, with a minimally valid configuration that:
* Runs the process specified by CMD & ENTRYPOINT only.
* Sets the environment specified by the image ENV only.
The approach is very naive - we pull through Singularity's OCI blob cache into a temporary oci layout dir, before creating the bundle from it. Auth handling for registries is not yet wired up. There is duplication of various pieces of code from the build / SIF OCI flows as these are not easily exposed to the area we are working in.
The intent of the PR, at …
> feat: run OCI image sources via temporary bundle

- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/image.go
- e2e/suite.go
- internal/pkg/runtime/launcher/launcher.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- pkg/ocibundle/native/bundle_linux.go
- pkg/ocibundle/native/bundle_linux_test.go
**Stacked on top of #1025 - please review that first**
When using `run` or `exec` with the `--oci` runtime mode, accept arguments on the command line.
For `run`, the arguments override any CMD specified by the image.
For `exec`, the arguments replace ENTRYPOINT/CMD entirely, bypassing the process configuration in the image config.
This mirrors the behavior of Singularity images today, via the exec and run runscripts - but is implemented in the OCI bundle config, rather than a script in the container.
_Also_
* refactor native bundle to functional options
* modify e2e tests to test with args
- Closes #1024 
- Closes #1092 
- Added …
> feat: exec / run args support for --oci mode

- .circleci/config.yml
- INSTALL.md
- cmd/internal/cli/actions.go
- debian/control
- dist/rpm/singularity-ce.spec.in
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/launcher.go
- pkg/ocibundle/native/bundle_linux.go
Enable `singularity shell --oci ...` with behavior matching native runtime, i.e.
* Run shell set with SINGULARITY_SHELL or --shell
* If not set, try /bin/bash --norc
* If not available, use /bin/sh
- Fixes #1025 …
> feat: enable shell for --oci mode

- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- pkg/ocibundle/native/bundle_linux.go
Move ID mapping and process setup code to the launcher, out of the oci bundle package.
Add a minimal config for `--oci` mode, rather than starting with the default OCI config.
Add explicit configuration of mounts, with `tmpfs` mount locations matching the native runtime with `--containall / --compat`.
Ensure ID mapping is always explicit (including for root).
Add tests touching the tmpfs locations. …
> oci: move some code to launcher, use explicit config

- cmd/internal/cli/oci_linux.go
- e2e/actions/oci.go
- internal/pkg/runtime/engine/fakeroot/config/config.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/runtime/launcher/oci/README.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/oci_conmon_linux.go
- internal/pkg/runtime/launcher/oci/oci_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/util/starter/starter.go
Implements initial --fakeroot support for --oci mode. Mirrors behavior with --compat / --contain.
The process of accomplishing this is fairly complex. In theory, we should be able to call `crun` directly from host namespaces. We can let `crun` create a default userns and user mapping, or be able to request arbitrary explicit uid mappings (permitted by /etc/subuid /etc/subgid) to be applied.
Unfortunately this can hit bugs as this path is not well tested in `crun`. See e.g.
* https://github.com/containers/crun/issues/1077
* https://github.com/containers/crun/issues/1072
To avoid requiring the very latest `crun` with fixes, instead move to creating a userns ourselves, with a 'fakeroot' ID mapping in place, and call `crun` from that. This is the kind of flow implemented in other runtimes …
> oci: Add --fakeroot support to --oci mode 

- INSTALL.md
- dist/rpm/singularity-ce.rpmlintrc
- dist/rpm/singularity-ce.spec.in
Tidy up the rpm spec file.
* Remove the manual handling of build root, GOPATH etc. Not needed as we are using go modules now.
* Remove redundant explicit deps.
* Fix crun -> runc dep for EL7, SLES.
* Use rpm make_xxx macros instead of direct make calls.
* Ensure all directories created are owned by package.
- Fixes #1142
- Fixes #1141
- Added tests to validate this PR, linted with `make check`  and tested this PR locally …
> pkg: Update / tidy rpm spec file

- CHANGELOG.md
- etc/conf/testdata/test_1.out.correct
- etc/conf/testdata/test_2.in
- etc/conf/testdata/test_2.out.correct
- etc/conf/testdata/test_3.in
- etc/conf/testdata/test_3.out.correct
- etc/conf/testdata/test_default.tmpl
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- pkg/util/singularityconf/config.go
Use the configuration file sessiondir max size value for --oci mode tmpfs mounts.
Increase the default from 16M -> 64M. The 16M default is very low, and has periodically caused issues running programs that create even small amounts of temporary data on --contained filesystems.
- Fixes #1140 …
> fix: use conf file value for oci tmpfs size

- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux_test.go
Support namespace request CLI options.
* --ipc - no effect, always used in --oci mode.
* --net - only supported with --network none.
* --pid - no effect, always used in --oci mode.
* -u / --userns - only effective for root, non-root always uses user ns.
* --uts
Add info logging where the option is redundant.
- Fixes #1026
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make …
> feat: oci: support namespace flags

- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
- pkg/runtime/engine/singularity/config/config.go
- pkg/util/bind/bind.go
- pkg/util/bind/bind_test.go
- pkg/util/bind/mount.go
- pkg/util/bind/mount_test.go
Implement support for bind mounts (rw & ro) specified using -B/--bind and --mount on the singularity command line.
- Fixes #1027 
- Fixes #1028  …
> feat: oci: enable bind mounts via --bind, --mount

- cmd/internal/cli/sign.go
- docs/content.go
- e2e/sign/sign.go
Add visual indication of key material being used by `singularity sign`. Improve `singularity sign` documentation. Define `SINGULARITY_SIGN_KEY` environment variable for '--key' flag of `singularity sign`. Simplify `singularity sign` end-to-end tests, and add coverage for `SINGULARITY_SIGN_KEY` environment variable.
- Fixes #1148 
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with …
> Environment Variables for Signing Key Material

- cmd/internal/cli/sign.go
- cmd/internal/cli/verify.go
- docs/content.go
- e2e/verify/verify.go
Add visual indication of key material being used by `singularity verify`. Improve `singularity verify` documentation. Define `SINGULARITY_VERIFY_KEY ` environment variable for '--key' flag of `singularity verify`. Simplify `singularity verify` end-to-end tests, and add coverage for `SINGULARITY_VERIFY_KEY ` environment variable. …
> Environment Variables for Verification

- e2e/env/env.go
- e2e/env/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- pkg/ocibundle/native/bundle_linux.go
- pkg/ocibundle/native/bundle_linux_test.go
* Merge image config ENV and env vars requested by user with the --env CLI option.
* Set default SINGULARITY_CONTAINER and SINGULARITY_NAME env variables.
* Set default LD_LIBRARY_PATH to be used later for library injection (this is a singularity default).
* Handle APPEND_PATH / PREPEND PATH like native runtime mode.
- Fixes #1029 
- Added tests to validate this PR, linted with `make check`  and tested this PR locally …
> feat: oci: support --env option in --oci mode

- e2e/env/env.go
- e2e/env/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
** Stacked on 1166 - please review 1166 first **
Pass SINGULARITYENV_ prefixed environment variables into container in --oci mode.
- Fixes #1031  …
> feat: oci: add SINGULARITYENV_ handling for --oci mode

- e2e/env/env.go
- e2e/env/oci.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
** Stacked on 1169 - please review 1169 first **
Allow --env-file to be used to provide environment variables in a file, when running a container in --oci mode.
We use the same approach as the native runtime for compatibility. The env file is evaluated in the embedded shell interpreter, but starting with an empty environment. This handles quoting, comments etc. for us, and keeps maximum compatibility with the existing handling.
- Fixes #1030 …
> feat: oci: enable --env-file in --oci mode 

- CHANGELOG.md
- e2e/instance/instance.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/util/fs/files/action_scripts.go
Inside an instance, expose the instance name as the environment variable `SINGULARITY_INSTANCE`.
- Fixes #1132 
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.m …
> feat: Set SINGULARITY_INSTANCE equal to instance name

- CHANGELOG.md
- e2e/gpu/gpu.go
- etc/rocmliblist.conf
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/util/gpu/rocm.go
A selection of ROCm fixes and addition of --oci support. Am including all in a single PR to minimize amount of work needed testing on a ROCm enabled system.
* In `--oci` mode ensure user and group entries written to container passwd / group files. Required to proceed with ROCm stuff.
* When binding ROCm devices with --contain in effect, we were only taking /dev/dri/cardxxx and /dev/kfd. At least some circumstances also require /dev/dri. Bind the whole of /dev/dri, just like the AMD ROCm container documentation for Docker does.
* Under --oci mode, allow --rocm, which will bind ROCm devices, libraries, and binaries into the container.
* e2e: minimal --rocm --oci test
* fix: rocm: update rocmliblist and fix e2e tests -`rocminfo` now needs `lsmod` and libdrm libdrm_amdgpu. Bind the former in …
> rocm: fixups and --oci support

- internal/app/singularity/instance_linux.go
Show CPU usage as an updating percentages in `instance stats`.
- Fixes #893 …
> instance: CPU usage as percentage

- CHANGELOG.md
- internal/app/singularity/plugin_compile_linux.go
- internal/pkg/buildcfg/confgen/gen.go
- internal/pkg/plugin/create.go
- internal/pkg/plugin/module.go
- mconfig
- mlocal/checks/project-post.chk
Add a `--reproducible` flag for mconfig. This will set BUILDDIR and SOURCEDIR in the buildcfg package to a literal `REPRODUCIBLE_BUILD`, so that binaries do not contain the paths to the source.
Disables pluign functionality, which needs the source path for in-tree plugin builds.
- Fixes #1173  …
> feat: reproducible build (SOURCEDIR / BUILDDIR)

- e2e/e2e_test.go
- e2e/internal/e2e/init/init_linux.go
- e2e/oci/oci.go
- e2e/suite.go
- mlocal/frags/Makefile.stub
- scripts/e2e-test
Cherry pick apptainer approach to drop PID namespace entirely in e2e tests, and handle reaping children.
https://github.com/apptainer/apptainer/pull/368/commits/9c0b50adb03eb6a5e4c519aa16590941cc2597ac
Too many tests are now becoming partly dependent on systemd cgroups management, which doesn't work in the PID namespace. It's not practical to continue splitting them into different groups.
Original PR:
Replace e2e tests PID namespace with PR_SET_CHILD_SUBREAPER
Signed-off-by: Cédric Clerget <cedric.clerget@gmail.com>
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according …
> e2e: replace tests PID namespace with child subreaper

- cmd/internal/cli/actions.go
- e2e/cgroups/cgroups.go
Stacked on top of #1186 - which itself actually makes limit flags effective and practical for instances.
Warn that limits only take effect on `instance start` and not when running an action against a running instance://`
Run the same set of tests as for interactive action resource limits against `instance start`.
- Fixes #817  …
> Support limit flags for instances

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- e2e/env/oci.go
- e2e/internal/e2e/profile.go
- e2e/internal/e2e/singularitycmd.go
- internal/app/singularity/oci_linux.go
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/cgroups/util.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_conmon_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
Honor the --apply-cgroups and individual cgroups resources flags when running in OCI mode.
The launcher instructs runc/crun to create a named cgroup with specified LinuxResources in the config.json. runc/crun must be called with the `--systemd-cgroup` flag when using systemd as cgroup manager.
E2E tests are adapted - they test identical cases for `--oci` mode as the native runtime mode.
- Fixes #1032  …
> feat: oci: support cgroups requests in --oci mode 

- CHANGELOG.md
- internal/pkg/util/fs/overlay/overlay_linux.go
- internal/pkg/util/fs/overlay/overlay_linux_test.go
A sandbox container on a panfs (Panasas) filesystem causes an overlay error at runtime. Add panfs to to the list of incompatible filesystems.
Block panfs as both lower and upper overlay dirs, until support is confirmed with Panasas (same situation as GPFS).
- Fixes #1215 …
> fix: block overlay for panfs

- cmd/internal/cli/build_linux.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
Ensure that the proot rootless build doesn't override a --remote build request.
- Fixes #1273
- Added myself …
> fix: ensure proot flow doesn't override --remote build

- CHANGELOG.md
- e2e/env/env.go
- e2e/env/regressions.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
Ensure UID and GID values returned by running shell interpreter on the env-file are not used for container. They are read-only built-ins, and attempting to set them displays a confusing warning.
- Fixes #1263  …
> fix: avoid readonly warnings with --env-file

- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/internal/e2e/profile.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
In the --oci launcher, When a minimal container doesn't have an `/etc/passwd` or `/etc/groups` file then don't fail with a fatal error. Instead warn like the native runtime does.
- Fixes #1286  …
> fix: lack of passwd / group should be warning in --oci mode

- .circleci/config.yml
Will move up to 1.20 after the 3.11 release, to avoid change in RC->release period.
> chore: bump go to 1.19.5 in CI

- CHANGELOG.md
- internal/pkg/runtime/launcher/native/launcher_linux.go
Setup for `--nvccli` in the native runtime launcher can imply `--writable-tmpfs`. However, in the refactored launcher, the ultimate engineconfig value for `--writable-tmpfs` was set prior to considering GPU options.
Move `--writable-tmpfs` handling after GPU configuration.
This issue *is* correctly detected by the existing e2e tests when running on a machine with an nvidia GPU and functional nvidia-container-cli install. It slipped through testing of 3.11.0 due to a configuration issue on a test machine. That needs to be tackled elsewhere... we can't currently run GPU tests in our SingularityCE CI, unfortunately.
I have manually confirmed this fix on an AWS T4 instance.
- Fixes #1351
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), …
> fix: handle --nvccli implied --writable-tmpfs correctly

- CHANGELOG.md
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
Due to incorrect logic / ordering of checks in prepareNetworkSetup, the combination of `--fakeroot --net --network=fakeroot` generated a false error stating that the fakeroot network was not permitted.
However, execution continued, and the fakeroot network was (correctly) used.
This is a minimal PR to correct the ordering of checks, such that `--fakeroot --net --network=fakeroot` doesn't give a false error.
The code handling checks for permitted networks is messy, and still needs a proper refactor. There is overriding of the `--network` setting for `--fakeroot` in the CLI->launcher layer as well, due to way in which the default network is implemented, via flag default value.
In addition, there doesn't seem to be a good reason as to why `allowed net networks` shouldn't apply when …
> fix: avoid incorrect error with --fakeroot --net --network=fakeroot

- CHANGELOG.md
- internal/pkg/image/unpacker/squashfs_singularity.go
In our handling of unsquashfs extraction, wrapped in a minimal container invocation, we are computing an LD_LIBRARY_PATH that holds the paths to all libraries needed by unsquashfs.
Unfortunately, we were setting `LD_LIBRARY_PATH` in the outer environment, and it does not pass into the container by default. We need to set `SINGULARITYENV_LD_LIBRARY_PATH` to pass it in.
This is very challenging to write a test for, as it requires modifying host binaries or ld.so.conf etc. Verified fix using the reproducer detailed in #1335.
- Fixes #1335 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if …
> fix: Pass LD_LIBRARY_PATH to wrapped unsquashfs correctly

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- internal/app/singularity/instance_linux.go
When a cgroups memory limit is set, show this in the instance stats output. Show the system total RAM when a limit is not set.
- Fixes #1281 …
> fix: show applicable mem limit in instance stats

- e2e/config/config.go
Don't attempt to look for CNI bridge network success via the AllowNet* config directives on hosts that don't support setting up the network.
- Fixes #1369  …
> e2e: gate AllowNet* tests with require.Network

- e2e/actions/oci.go
- e2e/cache/regressions.go
- e2e/cgroups/cgroups.go
- e2e/cmdenvvars/cmdenvvars.go
- e2e/env/oci.go
- e2e/instance/instance.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/image.go
- e2e/run/run.go
- e2e/suite.go
Fetch the OCI archive image used in tests from Docker Hub, so that it will match the host architecture.
- Fixes #1364
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBU …
> e2e: refactor test image handling 

- e2e/pull/pull.go
The v2 library won't serve up an image by hash unless is matches the requestors architecture, or the `--arch` flag is used to specify a different architecture.
Image we pull by hash is always amd64, so set the `--arch` flag appropriately in the test.
Fixes test on non amd64 systems.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible …
> e2e: force arch for pull by hash

- CHANGELOG.md
- internal/pkg/runtime/launcher/native/launcher_linux.go
Pick #1354 
Setup for `--nvccli` in the native runtime launcher can imply `--writable-tmpfs`. However, in the refactored launcher, the ultimate engineconfig value for `--writable-tmpfs` was set prior to considering GPU options.
Move `--writable-tmpfs` handling after GPU configuration.
This issue *is* correctly detected by the existing e2e tests when running on a machine with an nvidia GPU and functionall nvidia-container-cli install. It slipped through testing of 3.11.0 due to a configuration issue on a test machine. That needs to be tackled elsewhere... we can't currently run GPU tests in our SingularityCE CI, unfortunately.
- Fixes #1351 …
> fix: handle --nvccli implied --writable-tmpfs correctly (release-3.11)

- e2e/actions/oci.go
- e2e/cache/regressions.go
- e2e/cgroups/cgroups.go
- e2e/cmdenvvars/cmdenvvars.go
- e2e/env/oci.go
- e2e/instance/instance.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/image.go
- e2e/run/run.go
- e2e/suite.go
Pick #1368 
Refactor test image handling so that:
* We create the OCI archive, and Docker archive, used in the e2e tests with a container/image Copy from our local registry busybox image.
* We use DockerHub credentials for e2e.CopyOCIImage.
* We replace a couple of uses of `library://` images with our local registry ORAS SIF, avoiding some additional network access.
- Fixes #1364 …
> e2e: refactor test image handling (release-3.11)

- e2e/config/config.go
Pick #1370
Don't attempt to look for CNI bridge network success via the AllowNet* config directives on hosts that don't support setting up the network.
- Fixes #1369 …
> e2e: gate AllowNet* tests with require.Network (release-3.11)

- e2e/pull/pull.go
Pick #1371
The v2 library won't serve up an image by hash unless is matches the requestors architecture, or the `--arch` flag is used to specify a different architecture.
Image we pull by hash is always amd64, so set the `--arch` flag appropriately in the test.
Fixes test on non amd64 systems. …
> e2e: force arch for pull by hash (release-3.11)

- CHANGELOG.md
- internal/pkg/util/gpu/paths.go
- internal/pkg/util/gpu/paths_test.go
We use the output of `ldconfig -p` to construct a list of libraries to consider for binding into the container with `--nv` / `--rocm` enabled.
Previously, the entire `ldconfig -p` output was parsed into a map of path->library. This map was then iterated over when computing the binds to perform.
It's possible for a given `<library>.so[.version]` to be present at multiple paths, e.g. when a vendor and system `libEGL.so.0` are both present on the system. Because the map is keyed by path, multiple entries would be created in it. Range over map has a random order in Go, and we can only bind a single `<library>.so[.version]` under `.singularity.d/libs` - so the library bound would vary between runs.
This PR modifies the mapping to be library->path and ensures there is only a single …
> fix: gpu: always bind first variant of lib in ldconfig -p output

- CHANGELOG.md
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
Pick #1355
Due to incorrect logic / ordering of checks in prepareNetworkSetup, the combination of `--fakeroot --net --network=fakeroot` generated a false error stating that the fakeroot network was not permitted.
However, execution continued, and the fakeroot network was (correctly) used.
This is a minimal PR to correct the ordering of checks, such that `--fakeroot --net --network=fakeroot` doesn't give a false error.
The code handling checks for permitted networks is messy, and still needs a proper refactor. There is overriding of the `--network` setting for `--fakeroot` in the CLI->launcher layer as well, due to way in which the default network is implemented, via flag default value.
In addition, there doesn't seem to be a good reason as to why `allowed net networks` shouldn't apply …
> fix: avoid incorrect error with --fakeroot --net --network=fakeroot (release-3.11)

- CHANGELOG.md
- internal/pkg/image/unpacker/squashfs_singularity.go
Pick #1356
In our handling of unsquashfs extraction, wrapped in a minimal container invocation, we are computing an LD_LIBRARY_PATH that holds the paths to all libraries needed by unsquashfs.
Unfortunately, we were setting `LD_LIBRARY_PATH` in the outer environment, and it does not pass into the container by default. We need to set `SINGULARITYENV_LD_LIBRARY_PATH` to pass it in.
This is very challenging to write a test for, as it requires modifying host binaries or ld.so.conf etc. Verified fix using the reproducer detailed in #1335.
- Fixes #1335
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELO …
> fix: Pass LD_LIBRARY_PATH to wrapped unsquashfs correctly (release-3.11)

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- internal/app/singularity/instance_linux.go
Pick #1358
When a cgroups memory limit is set, show this in the instance stats output. Show the system total RAM when a limit is not set.
- Fixes #1281  …
> fix: show applicable mem limit in instance stats (release-3.11)

- CONTRIBUTING.md
Addresses two problems in `CONTRIBUTING.md`, specifically in the discussion of `LICENSE_DEPENDENCIES.md`:
- Replaced use of the phrase "Any new dependency" with the hopefully clearer "Any new or updated dependency". (The former could be misinterpreted to mean "only wholly new dependencies" excluding, e.g., version bumps, and that would be incorrect.)
- Fixed typo in the name of the update script: its extension is `.sh` but was given as `.md`
- Addresses #1392
> Improved discussion of LICENSE_DEPENDENCIES.md in CONTRIBUTING.md

- e2e/docker/docker.go
- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- e2e/internal/e2e/imageverify.go
- e2e/pull/pull.go
There are two kinds of changes here. First, the number of times `singularity exec` and `singularity inspect` are invoked from the `ImageVerify()` function has been reduced from 8 and 2, respectively, to 1 and 1, respectively.
Second, and relatedly, code that invokes `ImageVerify()` and used `defer f()` statements for cleanup has been changed to use `t.Cleanup()` statements that, crucially, check for `!t.Failed()` before performing the actual cleanup operations. This is a good idea in general, since suppressing cleanups when a test fails allows for more straightforward manual inspection of the fail state. This is a change we should eventually make throughout our test suites. But in this case it's especially important, because the consolidation of `singularity exec` and `singularity …
> e2e: improve ImageVerify efficiency and replace defer-based cleanups

- CONTRIBUTORS.md
- LICENSE_DEPENDENCIES.md
- go.mod
- internal/app/singularity/remote_add_test.go
- internal/pkg/remote/remote.go
- internal/pkg/remote/remote_test.go
Updates the Go dependency to [yaml v3](https://gopkg.in/yaml.v3).
- Fixes #1217 …
> Migrate to gopkg.in/yaml.v3

- e2e/docker/docker.go
When we call out to `docker`, do so with a custom `$HOME`, so that any configuration, cache etc. created there cannot affect other tests that may attempt to read configuration etc. at that location.
- Fixes #1396 …
> e2e: fix: use temp HOME for docker

- CHANGELOG.md
- internal/app/singularity/oci_linux.go
For the `OCI` command group, we need cgroups v2 unified mode in order to call `runc` with `--systemd-cgroup` as a non-root user.
Fall back to cgroupfs operation if this constraint is not satisified.
This fixes a failure when running a container using `runc`. `crun` was falling back to cgroupfs itself, even when `--systemd-cgroup` was specified.
Note that our CI cannot test this fix. To test, you need a cgroups v1 system with `runc` installed, and `crun` not installed. Before this patch, `singularity run --oci docker://alpine` will fail. After the patch, it will succeed.
There is no E2E test modification, as on the correct system configuration the tests do find this issue.
- Fixes #1408
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md) …
> fix: fall back to cgroupfs for OCI non-root, non cgroups v2

- e2e/docker/docker.go
Pick #1409
When we call out to `docker`, do so with a custom `$HOME`, so that any configuration, cache etc. created there cannot affect other tests that may attempt to read configuration etc. at that location.
- Fixes #1396
- Based this PR against the appropriate …
> e2e: fix: use temp HOME for docker (release-3.11)

- CHANGELOG.md
- internal/app/singularity/oci_linux.go
Pick #1410
For the `OCI` command group, we need cgroups v2 unified mode in order to call `runc` with `--systemd-cgroup` as a non-root user.
Fall back to cgroupfs operation if this constraint is not satisified.
This fixes a failure when running a container using `runc`. `crun` was falling back to cgroupfs itself, even when `--systemd-cgroup` was specified.
- Fixes #1408  …
> fix: fall back to cgroupfs for OCI non-root, non cgroups v2 (release-3.11)

- CONTRIBUTORS.md
- LICENSE_DEPENDENCIES.md
- e2e/cgroups/cgroups.go
- go.mod
- go.sum
- internal/pkg/cgroups/config_linux.go
- internal/pkg/syecl/syecl.go
- internal/pkg/syecl/testdata/TestAPutConfig/BlackList.golden
- internal/pkg/syecl/testdata/TestAPutConfig/BlackListLegacy.golden
- internal/pkg/syecl/testdata/TestAPutConfig/KitchenSink.golden
- internal/pkg/syecl/testdata/TestAPutConfig/KitchenSinkLegacy.golden
- internal/pkg/syecl/testdata/TestAPutConfig/WhiteList.golden
- internal/pkg/syecl/testdata/TestAPutConfig/WhiteListLegacy.golden
- internal/pkg/syecl/testdata/TestAPutConfig/WhiteStrict.golden
- internal/pkg/syecl/testdata/TestAPutConfig/WhiteStrictLegacy.golden
Pick #1383
Updates the Go dependency on [github.com/pelletier/go-toml](https://github.com/pelletier/go-toml) to v2
- Fixes #1216 …
> updated go-toml dependency to v2 (release-3.11)

- CHANGELOG.md
- cmd/internal/cli/key_export.go
- cmd/internal/cli/key_list.go
- cmd/internal/cli/key_remove.go
- e2e/key/key.go
- pkg/sypgp/sypgp.go
Added `--secret` to the `remove` subcommand for keys. Also added `--private` as a synonym of `--secret`, as it's arguably more common to talk about 'public' / 'private', than it is to use 'secret' (despite e.g. GPG using 'secret' in commands).
For the sake of consistency, added `-p`/`--private` synonyms to `key list` and `key export`, as well.
Added e2e testing for  various conditions involving `key remove`. Also added `--private` condition to `key remove` test in `globalKeyring` (which should fail, since `key remove --private --global` is an illicit combination).
- Fixes #928
> 928 delete private key using cli

- internal/pkg/runtime/launcher/oci/oci_linux.go
Drop the warning that not all OCI functionality is supported with runc.
Some things turned out to be SingularityCE bugs. Some things are very version specific. A new enough runc will work.
- Fixes #1425
- Based this PR against the appropriate branch according to …
> oci: drop warning about runc functionality

- internal/pkg/runtime/launcher/oci/oci_linux.go
Pick #1426
Drop the warning that not all OCI functionality is supported with runc.
Some things turned out to be SingularityCE bugs. Some things are very version specific. A new enough runc will work.
- Fixes #1425 …
> oci: drop warning about runc functionality (release-3.11)

- CHANGELOG.md
- e2e/imgbuild/imgbuild.go
- e2e/internal/e2e/home.go
- examples/almalinux-arm64/Singularity
- examples/almalinux/Singularity
- examples/fedora-arm64/Singularity
- examples/fedora/Singularity
- internal/pkg/build/sources/conveyorPacker_yum.go
- internal/pkg/build/sources/conveyorPacker_yum_test.go
- internal/pkg/test/tool/require/require.go
- internal/pkg/util/rpm/rpm.go
- internal/pkg/util/rpm/rpm_test.go
- pkg/build/types/parser/deffile.go
The yum bootstrap is fragile, as over time rpm has changed both the format of its database, and the location of the database. This means that newer RPM distros (EL9, recent Fedora) cannot bootstrap older ones successfully.
* Refactor code checking for rpm macro values.
* Check for host `_db_backend` value `sqlite` and warn that older distros using `bdb` cannot be bootstrapped in this case.
* Add a `setopt` def file header, which will pass the value to yum/dnf via the `--setopt` flag. This allows specifying `install_weak_deps=False`, which is necessary to bootstrap a minimal Fedora with no systemd (which fails to install).
* Add examples and gated e2e tests so that we test bootstrapping CentOS 7, AlmaLinux 9, or Fedora 37, depending on what the host rpm setup will support.
* Don't create …
> fix: support and test yum bootstrap on newer distros

- CHANGELOG.md
- e2e/imgbuild/imgbuild.go
- e2e/internal/e2e/home.go
- examples/almalinux-arm64/Singularity
- examples/almalinux/Singularity
- examples/fedora-arm64/Singularity
- examples/fedora/Singularity
- internal/pkg/build/sources/conveyorPacker_yum.go
- internal/pkg/build/sources/conveyorPacker_yum_test.go
- internal/pkg/test/tool/require/require.go
- internal/pkg/util/rpm/rpm.go
- internal/pkg/util/rpm/rpm_test.go
- pkg/build/types/parser/deffile.go
Pick #1420
The yum bootstrap is fragile, as over time rpm has changed both the format of its database, and the location of the database. This means that newer RPM distros (EL9, recent Fedora) cannot bootstrap older ones successfully.
* Refactor code checking for rpm macro values.
* Check for host `_db_backend` value `sqlite` and warn that older distros using `bdb` cannot be bootstrapped in this case.
* Add a `setopt` def file header, which will pass the value to yum/dnf via the `--setopt` flag. This allows specifying `install_weak_deps=False`, which is necessary to bootstrap a minimal Fedora with no systemd (which fails to install).
* Add examples and gated e2e tests so that we test bootstrapping CentOS7, AlmaLinux 9, or Fedora 37, depending on what the host rpm setup will support.
* …
> fix: support and test yum bootstrap on newer distros (release-3.11)

- e2e/verify/verify.go
In the e2e VERIFY tests, if the openssl OCSP responder fails to start we now error, and skip the OCSP subtests.
Prior to this change a panic occured, causing other tests not to be run.
Responder startup failure has been observed on SLES 12, where not all the key algorithms we are using are supported by the openssl version that's available.
We do want to test the different key algorithms are handled in our code, so lets leave this as a reported test error for now, rather than gating the test on openssl version.
- Fixes #1417 …
> e2e: fix: don't panic if OCSP responder cannot start

- CHANGELOG.md
- CONTRIBUTORS.md
- cmd/internal/cli/remote.go
- docs/remote.go
- internal/app/singularity/remote_get_login_password.go
- internal/app/singularity/remote_get_login_password_test.go
This PR adds a get login password command that allows users to retrieve the cli token from the currently logged in user.
This enables the workflow to pipe the cli secret directly into docker login flow from reading std-in. This workflow is recommended to prevent the password from ending up in a shell's history or log-files
Example usage:
`singularity remote get-login-password | docker login --username foo --password-stdin`
- Fixes #
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRI …
> add get login password command

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- internal/pkg/cgroups/manager_linux.go
*fix: Never skip device cgroup creation*
If a container is being run with a cgroups LinuxResources config that doesn't include any device rules, then the device cgroup creation was skipped. Singularity has historically had default-allow, while runc/libcontainer/cgroups is default deny.
Under cgroups v1 with cgroupfs manager we need the device cgroup for PID -> cgroup lookup at instance join, so don't skip it... use an explicit allow rule instead.
At update, we still skip if there are no resources provided, so we don't update to a default allow, or deny.
Also set rootless flag on update properly, so that we avoid warnings / errors with rootless cgroups where device limits don't apply.
*e2e: Only test blkio.weight on cgroups v1, not blkio.bfq.weight*
crun has an issue where on cgroups v1 it …
> fix: address cgroups v1 device related e2e test failures

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- internal/pkg/cgroups/manager_linux.go
Pick #1430
*fix: Never skip device cgroup creation*
If a container is being run with a cgroups LinuxResources config that doesn't include any device rules, then the device cgroup creation was skipped. Singularity has historically had default-allow, while runc/libcontainer/cgroups is default deny.
Under cgroups v1 with cgroupfs manager we need the device cgroup for PID -> cgroup lookup at instance join, so don't skip it... use an explicit allow rule instead.
At update, we still skip if there are no resources provided, so we don't update to a default allow, or deny.
Also set rootless flag on update properly, so that we avoid warnings / errors with rootless cgroups where device limits don't apply.
*e2e: Only test blkio.weight on cgroups v1, not blkio.bfq.weight*
crun has an issue where on …
> fix: address cgroups v1 device related e2e test failures (release-3.11)

- e2e/imgbuild/imgbuild.go
Corrects an issue in #1420
- Fixes #1434 …
> e2e: fix incorrect arm64->amd64 in CentOS Yum test

- e2e/imgbuild/imgbuild.go
Pick #1435
Corrects an issue in #1420
Fixes #1434
- Fixes #1434 …
> e2e: fix incorrect arm64->amd64 in CentOS Yum test (release-3.11)

- cmd/internal/cli/build.go
- cmd/internal/cli/cache_clean_linux.go
- cmd/internal/cli/delete.go
- e2e/cache/cache.go
- internal/app/singularity/remote_login.go
Various yes/no questions issued by `singularity` ended in `[N/y]` when "no" is the default response. This wasn't in line with the standard behavior of most command-line tools, which always maintain a yes-before-no order, and indicate the default response purely by means of capitalization.
To bring the behavior of `singularity` in line with this standard, occurrences of `[N/y]` in the following places have been replaced with `[y/N]`:
- e2e/cache/cache.go
- internal/app/singularity/remote_login.go
- cmd/internal/cli/cache_clean_linux.go
- cmd/internal/cli/build.go
- cmd/internal/cli/delete.go
- Fixes #1429
> replaced "[N/y]" with "[y/N]"

- CHANGELOG.md
- dist/rpm/singularity-ce.spec.in
Changed value of `--localstatedir` in `dist/rpm/singularity-ce.spec.in` to `/var/lib` (by pulling from the macro `%{_sharedstatedir}` instead of `%{_localstatedir}`, as was the case previously).
This brings the behavior of our RPM packaging in line with [current FHS specifications](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html), as well as what Red Hat are now [requiring](https://bugzilla.redhat.com/show_bug.cgi?id=2145834).
This also brings the behavior of RPM builds in line, in this respect, with what we do for `.deb` packaging (see `debian/rules`).
- Fixes #1138
> 1138 consider gnu vs fhs definition of localstatedir

- CHANGELOG.md
- dist/rpm/singularity-ce.spec.in
* On SLES we intend to require runc, not crun.
* squashfs had a duplicate Requires, instead of a BuildRequires.
- Fixes #1453 …
> rpm: fix: correct BuildRequires/Requires for SLES

- internal/pkg/remote/endpoint/client.go
The timeout added to the library http client in #1490 caused library pull failures.
There probably should be a sensibly large timeout here, to accommodate large pulls. The code path down through scs-library-client needs to be reviewed and considered to set an appropriate value. …
> fix: remove library http client timeout

- e2e/actions/oci.go
- e2e/suite.go
- internal/pkg/runtime/launcher/oci/process_linux.go
There was a problem where, in OCI mode, a custom working directory (`--cwd`/`--pwd`) would not be respected, and the homedir would be used as the working directory instead.
Interestingly, this was not caught by our e2e tests, which (ultimately) revealed a problem in the way I was handling profiles in the `actionOciExec()` function (e2e/actions/oci.go:228).
This fixes both issues.
> oci: fix custom cwd not respected when homedir set

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/util/fs/helper.go
- internal/pkg/util/fs/helper_linux_test.go
When running in --oci mode as a normal user, Singularity sets up an outer userns that provides an unprivileged root. When --fakeroot is not also requested, runc / crun then map back to the user's own uid/gid via an inner reverse mapping specified in config.json.
This mapping was not being applied correctly, as a userns was not requested in the config.json for all situations where a reverse mapping was requested.
Ensure that if we specify a mapping in config.json then we request a userns so that it is applied.
Cover this behavior in an e2e-test by writing to a host dir from the container, and checking ownership of the file on the host.
- Fixes #1517 …
> fix: oci: explicitly request userns for inner reverse idmap

- CHANGELOG.md
- pkg/util/loop/loop.go
Perform loop device creation via the LOOP_CTL_ADD ioctl against /dev/loop-control.
This avoids hitting an error in the latest kernels that include a change in handling of loop device creation when max_loop is unset.
Our target distros now all provide /dev/loop-control, so we are free to make this change.
Also contains minor fixes to correct an error/debug message, and add an earlier continue in case of failure to open loop device in attachLoop.
- Fixes #1499 …
> loop: Use LOOP_CTL_ADD instead of mknod for dev creation

- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/process_linux.go
Fix `--home` functionality in OCI-mode, so it works even when running as root (e.g. under `sudo`) or when running with `--fakeroot`.
- Fixes #1529 
#1531 describes a more fundamental change to the way custom /etc/passwd information is handled in singularity, which would reduce the likelihood of problems like the one described here arising in the first place.
> oci: fix --home when running as root or fakeroot

- internal/pkg/build/sources/packer_ext3.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/rpc/args.go
- internal/pkg/runtime/engine/singularity/rpc/client/client.go
- internal/pkg/util/crypt/crypt_dev.go
- pkg/ocibundle/tools/loop.go
- pkg/util/loop/loop.go
- pkg/util/loop/loop_test.go
Use x/sys/unix wrappers for ioctl operations.
Use x/sys/unix types and flag constants.
Not for backport. Changes public things under pkg
- Fixes #1505 …
> loop: refactor to use x/sys/unix

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
In `getReverseUserMaps`,we were taking `targetUID` and `targetGID` parameters that define the UID and GID the container will be entereed as. However, the mappings returned were based on the current host UID and GID, and not the target IDs.
Ensure that the user maps use the `targetUID` and `targetGID`.
Split the function up so that the core computation of the user maps can be tested. The tests help to explain what the intended functionality here is... which is beneficial as it's somewhat complex.
- Fixes #519
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the …
> fix: oci: reverse uid/gid maps now honour target IDs

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
When executed from a root-owned cgroup, such as the session scope resulting from a bare ssh login, crun will fail to create our requested container cgroup.
If we are running as non-root, create and move into a user-owned cgroup, so that there's a common user-owned ancestor. This avoids the `crun` error.
Note that no workaround is needed for `runc` as it is able to create the requested container cgroup without any issue.
- Fixes #1538 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONT …
> fix: oci: enter cgroup before executing crun as non-root

- CHANGELOG.md
- pkg/util/loop/loop.go
Cherry pick #1504 
Perform loop device creation via the LOOP_CTL_ADD ioctl against /dev/loop-control.
This avoids hitting an error in the latest kernels that include a change in handling of loop device creation when max_loop is unset.
Our target distros now all provide /dev/loop-control, so we are free to make this change.
Also contains minor fixes to correct an error/debug message, and add an earlier continue in case of failure to open loop device in attachLoop.
- Fixes #1499 …
> loop: Use LOOP_CTL_ADD instead of mknod for dev creation (release-3.11)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/util/fs/helper.go
- internal/pkg/util/fs/helper_linux_test.go
Pick #1518 
When running in --oci mode as a normal user, Singularity sets up an outer userns that provides an unprivileged root. When --fakeroot is not also requested, runc / crun then map back to the user's own uid/gid via an inner reverse mapping specified in config.json.
This mapping was not being applied correctly, as a userns was not requested in the config.json for all situations where a reverse mapping was requested.
Ensure that if we specify a mapping in config.json then we request a userns so that it is applied.
Cover this behavior in an e2e-test by writing to a host dir from the container, and checking ownership of the file on the host.
- Fixes #1517 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms …
> fix: oci: explicitly request userns for inner reverse idmap (release-3.11)

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
Pick #1537 
In `getReverseUserMaps`,we were taking `targetUID` and `targetGID` parameters that define the UID and GID the container will be entereed as. However, the mappings returned were based on the current host UID and GID, and not the target IDs.
Ensure that the user maps use the `targetUID` and `targetGID`.
Split the function up so that the core computation of the user maps can be tested. The tests help to explain what the intended functionality here is... which is beneficial as it's somewhat complex.
- Fixes #1519 …
> fix: oci: reverse uid/gid maps now honour target IDs (release-3.11)

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #1495
Support `--hostname` in OCI mode. Requires UTS namespace, so in OCI mode, `--hostname` will infer `--uts`. Added test in e2e-test suite (e2e/actions/oci.go:148) for this functionality.
- Fixes #1474
> oci: support --hostname (release-3.11)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
Pick #1498 
Support `--scratch` (shorthand: `-S`) for mounting a tmpfs scratch directory in the container in oci mode, just like we do in native mode.
Added e2e tests for this functionality in oci mode, mirroring and extending the e2e tests for the corresponding native-mode functionality. Added a couple of tests to both modes:
- Test that a scratch-mounted dir is indeed present in the container as a mount with `tmpfs` filesystem
- Test that when a bind-mounted dir shares a path with a scratch-mounted dir, the bind-mounted one will override the scratch-mounted one. (This was already behavior in native mode, though it wasn't being tested, as far as I could tell. Now it's enforced by the e2e tests for each of the two modes.)
- Fixes #1482
> oci: support --scratch (release-3.11)

- e2e/actions/oci.go
- e2e/suite.go
Pick #1523 
There was a problem where, in OCI mode, a custom working directory (`--pwd`) would not be respected, and the homedir would be used as the working directory instead.
Interestingly, this was not caught by our e2e tests, which (ultimately) revealed a problem in the way I was handling profiles in the `actionOciExec()` function (e2e/actions/oci.go:228).
This fixes both issues.
> oci: fix custom pwd not respected when homedir set (release-3.11)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/internal/e2e/singularitycmd.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
Pick #1500 
Adds support for `--home` in OCI mode.
Specifically, supplying a single location (e.g. `--home /myhomedir`) will result in a new tmpfs directory being created at the specified location inside the container, and that dir being set as the in-container user's home dir. Supplying two locations separated by a colon (e.g. `--home /home/user:/myhomedir`) will result in the first location on the host being bind-mounted as the second location in-container, and set as the in-container user's home dir.
Added e2e tests in e2e/actions/oci.go to largely mirror how we test the corresponding native-mode functionality, with the caveat that the tests now look for a tmpfs mounted dir inside the container when appropriate. Also made a minor improvement inside the native-mode `--home` tests, to …
> oci: support --home (release-3.11)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #1551 
Brought handling of `resolv.conf` and `--dns` flag in OCI mode on par with their behavior in native mode.
In particular: an `/etc/resolv.conf` file is always created in the OCI container. If a `--dns` argument is provided, its contents (a comma-separated list of IPs of nameservers) determines the content of this `resolv.conf` file. Otherwise, the content is taken from the host's `/etc/resolv.conf` file.
- Fixes #1472
> oci: support resolv.conf and --dns (release-3.11)

- internal/pkg/runtime/launcher/oci/launcher_linux.go
Fixes a tiny typo ("resolve.conf" -> "resolv.conf") in warning message in internal/pkg/runtime/launcher/oci/launcher_linux.go:393
> fixed typo (resolve.conf -> resolv.conf)

- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #1570
If we are running under cgroups v1 or with the cgroupfs manager (i.e. not systemd as cgroup manager), do not attempt to enter a cgroup at startup with crun. We cannot create a cgroup unprivileged in this situation.
Under cgroups v1, crun will not perform the cgroups manipulation that leads to the issue we worked around in #1539. Any other issue with the cgroup that we are in at launch cannot be rectified, either.
- Fixes #1569  …
> fix: oci: Don't create cgroup for crun on v1 / cgroupfs (release-3.11)

- .circleci/config.yml
Change version of Go in CircleCI config (.circleci/config.yml) from 1.20.2 to 1.20.3
> Go version in CircleCI config 1.20.2 -> 1.20.3

- CHANGELOG.md
- etc/conf/testdata/test_1.out.correct
- etc/conf/testdata/test_2.in
- etc/conf/testdata/test_2.out.correct
- etc/conf/testdata/test_3.in
- etc/conf/testdata/test_3.out.correct
- etc/conf/testdata/test_default.tmpl
- pkg/util/singularityconf/config.go
Corrected `singularity.conf` comment, to refer to correct file as source of default capabilities when `root default capabilities = file`.
- Fixes #1583  …
> fix: singularity.conf default root capabilities comment

- e2e/docker/docker.go
- e2e/docker/regressions.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
When we run a container in `--oci` mode, we have a temporary rootfs that must be removed when the container exits.
A container can contain files / dirs with restrictive permissions that prevent direct removal.
Use fs.ForceRemoveAll, which will chmod & remove anything that os.RemoveAll is unable to remove.
- Fixes #1586
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make …
> fix: Remove files with restrictive perms from --oci temp rootfs

- e2e/docker/docker.go
- internal/pkg/runtime/launcher/oci/process_linux.go
In OCI mode, avoid overriding container's HOME environment variable if container specifies its own USER.
Also add e2e test of the above.
- Fixes #1593
> oci: fix to not override HOME when container specifies USER (+ e2e test)

- e2e/docker/docker.go
- internal/pkg/runtime/launcher/oci/process_linux.go
Pick #1594 
In OCI mode, avoid overriding container's HOME environment variable if container specifies its own USER.
Also add e2e test of the above.
- Fixes #1593
> oci: fix to not override HOME when container specifies USER + e2e test (release-3.11)

- CHANGELOG.md
- e2e/config/config.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/util/fs/mount/mount_linux.go
- internal/pkg/util/fs/mount/mount_linux_test.go
- pkg/util/singularityconf/config.go
Pick #1600 
In singularity.conf, add two directives `allow kernel squashfs` and `allow kernel extfs` which default to 'yes'. When set to 'no', these directives prevent a squashfs mount or extfs mount from being performed through the kernel. Note that this only happens in setuid mode / as root.
squashfs and extfs mounts are added from the various locations that handle loopback mounting of a filesystem image. The image could be a container rootfs, an overlay, or an image bind. In each case the image may be a standalone file or embedded in a SIF.
The simplest place to gate these mounts is in mount.AddImage, via the existing check that the fs type is authorized as the source for an image mount.
Authorized filesystems for image mounts are held in a package var. At the start of container …
> Allow kernel squashfs / extfs mount to be disabled in singularity.conf (release-3.11)

- CHANGELOG.md
- e2e/config/config.go
- internal/pkg/runtime/engine/singularity/container_linux.go
_Don't merge until after release-3.11 -> master merge_
Pick #1617
The `allow kernel squashfs` directive was not applied correctly to limit mounts of encrypted squashfs images.
The `encryptfs` mount type is not a generic marker of a LUKS wrapping of a filesystem. It currently signifies only an encrypted squashfs mount, and the mount type is changed from `encryptfs -> squashfs` after the check implemented in `mount.image`.
The need for an encrypted SIF test in the e2e suite was overlooked.
This PR:
* Adds required e2e tests.
* Changes `encryptfs` -> `encrypted_squashfs` for clarity.
* Gates `encrypted_squashfs` images on the `allow kernel squashfs` directive.
- Fixes #1614 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR …
> fix: apply allow kernel squashfs directive to encrypted squashfs (release-3.11)

- CHANGELOG.md
- e2e/config/config.go
- internal/pkg/runtime/engine/singularity/container_linux.go
_Don't merge until after release-3.11 -> master merge_
The `allow kernel squashfs` directive was not applied correctly to limit mounts of encrypted squashfs images.
The `encryptfs` mount type is not a generic marker of a LUKS wrapping of a filesystem. It currently signifies only an encrypted squashfs mount, and the mount type is changed from `encryptfs -> squashfs` after the check implemented in `mount.image`.
The need for an encrypted SIF test in the e2e suite was overlooked.
This PR:
* Adds required e2e tests.
* Changes `encryptfs` -> `encrypted_squashfs` for clarity.
* Gates `encrypted_squashfs` images on the `allow kernel squashfs` directive.
- Fixes #1614
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to …
> fix: apply allow kernel squashfs directive to encrypted squashfs

- .circleci/config.yml
- INSTALL.md
- examples/ubuntu/Singularity
- internal/pkg/build/sources/conveyorPacker_debootstrap_test.go
_Merge after 2024-04-30_
**ci: Drop Ubuntu 18.04 package builds**
Ubuntu 18.04 is EOL 2023-04-30
**Bump example / debootstrap tests to Ubuntu jammy**
Ensure we are using a currently supported Ubuntu in our example definition file, and debootstrap test code.
> Drop Ubuntu 18.04 (EOL)

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- SECURITY.md
- cmd/internal/cli/oci_linux.go
- docs/content.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/app/singularity/oci_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- pkg/ocibundle/tools/overlay_linux.go
Pick #1622
The `--oci` mode intends to follow behaviour that the native runtime implements when run with `--compat`.
One missing aspect is that `--compat` sets `--writable-tmpfs`, where the container rootfs is made writable with a tmpfs backed overlay.
This PR:
- Introduces a simple wrapping of the `oci run` sub-command as `oci run-wrapped`. This hidden command implements prep / cleanup steps that must take place in a userns for non-root `--oci` execution.
- Switches the oci launcher to calling `oci run-wrapped` instead of `oci-run`.
- Adds a tmpfs based overlay creation function for OCI bundles.
- Includes the tmpfs overlay creation in the `oci run-wrapped` flow.
- Copies the native runtime `--compat` e2e tests to OCI mode.
- Fixes #1621 
- Read the [Guidelines for …
> oci: Enable --writable-tmpfs behaviour by default (release-3.11)

- README.md
- SUPPORT.md
Pick #1638
We are moving to GitHub Discussions as the primary location for usage, feature, and roadmap discussion.
Promote it via updated links. The singularityce-community repo, which is managed via HackMD, will have redirection notices added. …
>  docs: Promote GitHub Discussions, retire HackMD (release-3.11)

- .circleci/config.yml
Change version of Go in CircleCI config (.circleci/config.yml) from 1.20.3 to 1.20.4
> Go version in CircleCI config 1.20.3 -> 1.20.4

- RELEASE_PROCEDURE.md
PR #1603 was incomplete, in that there were two more instances of the incorrect `make dist` command line (`git clean -fdx && mconfig -v && make dist`) in the `RELEASE_PROCEDURES.md` file that needed to be fixed to the corrected version (`git clean -fdx && ./mconfig -v && make -C builddir dist`).
> fix leftover occurrences of old `make dist` command line

- mconfig
Given that we now have code that relies on Go Generics (ver. 1.18+) even outside of the testing suite (see e.g. #1562), the minimal Go version specified in `mconfig` has been changed from 1.17 to 1.18
> chg minimal Go version in mconfig to 1.18

- CHANGELOG.md
- e2e/actions/actions.go
- internal/pkg/runtime/engine/singularity/container_linux.go
Bind mounts are now performed in the order of their occurrence in the comma-separated list given to the `-B`/`--bind` flag, or given as the value of the `SINGULARITY_BIND` environment variable. (Previously, image-mounts were always performed first, regardless of the order of items in the comma-separated list.)
(Cherry-picked from [apptainer/apptainer#188](https://github.com/apptainer/apptainer/pull/188) with expanded CHANGELOG comment.)
- Fixes #1604
> Fix mount ordering between image and user binds

- CHANGELOG.md
- cmd/internal/cli/oci_linux.go
- docs/content.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/imgbuild/imgbuild.go
- e2e/suite.go
- internal/app/singularity/oci_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/runtime/launcher/options.go
- pkg/ocibundle/tools/overlay_linux.go
Support `--overlay <overlay_dir>` flag in OCI-mode (in "action" commands, i.e., run/exec/shell). This allows the user to mount a directory as a filesystem overlay, in lieu of using a writable tmpfs (which is the default behavior since version 3.11.3). This enables writes to the filesystem to persist across runs of the OCI container. If `<overlay_dir>` does not exist, Singularity will attempt to create it.
- Fixes #1478
> oci: support --overlay

- CHANGELOG.md
- cmd/internal/cli/oci_linux.go
- e2e/actions/oci.go
- internal/app/singularity/oci_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
When a system doesn't support unprivileged overlay mounts, do not attempt to use them.
This means that a writable-tmpfs is not used, and a container is read-only, when run on a system such as EL7 or SLES12.
The approach taken here is rather inelegant, but works. We'll address it more neatly on `main` where additional oci overlay handling has been developed.
Note that this PR must be tested both on a system supporting unpriv overlay (e.g. Ubuntu 22.04, RHEL9) and a system that doesn't (RHEL7, SLES12).
- Fixes #1676 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to …
> oci: Don't attempt unpriv overlay when not supported (release-3.11)

- e2e/actions/oci.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- pkg/ocibundle/tools/overlay_linux.go
In OCI mode, if there is one or more overlays specified but they are all read-only, wrap Run in an additional writable tmpfs overlay so that the filesystem in its entirety is writable inside the container (in alignment with the goals of #1622 ).
- Fixes #1670
> oci: wrap run in writable tmpfs overlay if there's only read-only overlay(s)

- e2e/actions/actions.go
- e2e/actions/oci.go
In working on #1659 and #1671 , it emerged that in some scenarios (esp. when running as root), our cleanup of overlay mounts was incomplete. Importantly, that cleanup process intentionally logs errors and proceeds (rather than erroring out), in order to clean up as much as possible even under error conditions; but that means that we can't rely simply on exit codes to detect problems in the cleanup of overlay mounts.
This PR adds an e2e test specifically dedicated to detecting such problems, by running an OCI-mode container as root, and comparing the number of current mounts before & after the run.
> oci: Improve testing of overlay cleanup

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- e2e/actions/actions.go
- e2e/actions/common.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
Provides support for `--workdir` in OCI-mode.
Specifying `--workdir <dir>` means that `/tmp` and `/var/tmp` will be mapped, respectively, to `<workdir>/tmp` and `<workdir>/var_tmp` on the host, rather than to tmpfs storage. If `--scratch <scratchdir>` is used in conjunction with `--workdir`, scratch directories will be mapped to subdirectories nested under `<workdir>/scratch` on the host, rather than to tmpfs storage. (This is line with the behavior of `--scratch` in conjunction with `--workdir` in native mode.)
Also changed the usage string for the `--workdir` option to make it clear that $HOME is unaffected by this option. (The latter can be manipulated separately, using the `--home` option.) This is so both in native mode and OCI mode.
- Fixes #1483
> oci: support --workdir

- CHANGELOG.md
- CONTRIBUTORS.md
- cmd/internal/cli/remote.go
- docs/remote.go
- internal/app/singularity/remote_get_login_password.go
- internal/app/singularity/remote_get_login_password_test.go
Pick #1348
This PR adds a get login password command that allows users to retrieve the cli token from the currently logged in user.
This enables the workflow to pipe the cli secret directly into docker login flow from reading std-in. This workflow is recommended to prevent the password from ending up in a shell's history or log-files
Example usage:
singularity remote get-login-password | docker login --username foo --password-stdin
> add get login password command (release-3.11)

- CHANGELOG.md
- CONTRIBUTORS.md
- e2e/cmdenvvars/cmdenvvars.go
- pkg/syfs/syfs.go
This PR adds a new check for the configuration directory via the `SINGULARITY_CONFIGDIR` environment variable, which is checked before the current user's home directory in `sysfs.configDir()`. This is useful if one does not want `.singularity` in their home directory, and can be used to enforce the XDG config directory of the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defining `SINGULARITY_CONFIGDIR=$XDG_CONFIG_HOME/singularity`.
This environment variable complements `SINGULARITY_CACHEDIR`, which can be used to do the same for the XDG cache directory with `SINGULARITY_CACHEDIR=$XDG_CACHE_HOME/singularity`.
> Set custom configuration directory via environment variable

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
Fixes a bug where `--scratch` failed when used in conjunction with `--workdir` if the latter was given a relative (rather than absolute) path.
Also changes the behavior of `--workdir` code so that an error (rather than a warning) is generated if specified workdir cannot be converted to an absolute path.
Lastly, adds e2e tests for this behavior (`--scratch` in conjunction with relative `--workdir`), in both native and OCI modes.
- Fixes #1693
> fix rel. path --workdir with --scratch, add native and oci e2e tests

- CHANGELOG.md
- cmd/internal/cli/inspect.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- test/defs/issue1704.def
As part of the function of `singularity inspect`, an ad-hoc shell script is set up, by concatenating programmatically-generated snippets of shell code. One of these snippets, created in cmd/internal/cli/inspect.go:227, includes a line whose function is to set IFS (the Input Field Separator) _back_ to newline in the scope of the `cat_file()` function, despite being set to ":" (colon) in the global scope (cmd/internal/cli/inspect.go:256).
However, the way this was done until now uses escaping of the newline, as follows: `local IFS=$'\n'`
This escaping apparently doesn't work on certain platforms, resulting in the relevant input being split using the character "n" as the relevant delimiter, rather than using newlines.
I have verified that it fails on Debian 11 "bullseye" on amd64, and the …
> more robust way of setting IFS to newline

- CHANGELOG.md
- cmd/internal/cli/inspect.go
- e2e/docker/docker.go
- e2e/docker/regressions.go
- test/defs/issue1704.def
Pick #1708 
As part of the function of `singularity inspect`, an ad-hoc shell script is set up, by concatenating programmatically-generated snippets of shell code. One of these snippets, created in cmd/internal/cli/inspect.go:227, includes a line whose function is to set IFS (the Input Field Separator) _back_ to newline in the scope of the `cat_file()` function, despite being set to ":" (colon) in the global scope (cmd/internal/cli/inspect.go:256).
However, the way this was done until now uses escaping of the newline, as follows: `local IFS=$'\n'`
This escaping apparently doesn't work on certain platforms, resulting in the relevant input being split using the character "n" as the relevant delimiter, rather than using newlines.
I have verified that it fails on Debian 11 "bullseye" on …
> more robust way of setting IFS to newline (#1708) (release-3.11)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
Pick #1714 
When runc/crun is called from oci_runc_linux.go, Stdin was incorrectly connected for the various runc/crun operations.
* Non-interactive operations such as resume / kill don't need Stdin.
* Interactive operations (run/exec) had cmd.Stdin incorrectly set to os.Stdout. This prevented OCI containers from receiving input from pipes, redirection, etc.
This PR fixes these issues and ports action STDPIPE tests to --oci mode. These were previously missed, resulting in https://github.com/sylabs/singularity/issues/1712 not being caught by the e2e suite.
- Fixes #1712 …
> fix: correct Stdin wire-up in runc/crun execs (release-3.11)

- CHANGELOG.md
- internal/pkg/util/bin/bin.go
- internal/pkg/util/fs/overlay/overlay_item_linux.go
- internal/pkg/util/fs/overlay/overlay_item_linux_test.go
- internal/pkg/util/fs/overlay/overlay_linux.go
- internal/pkg/util/fs/overlay/overlay_set_linux.go
- internal/pkg/util/fs/overlay/overlay_set_linux_test.go
If kernel doesn't support unprivileged overlay mounts, fallback to trying to use `fuse-overlayfs` and `fusermount` for overlay mounting and unmounting.
- Fixes #1727
> oci: fallback to fuse-overlayfs if kernel doesn't support unprivileged overlays

- CHANGELOG.md
- CONTRIBUTORS.md
- internal/app/singularity/instance_linux.go
Adds explicit cast to `uint64` of `Totalram` field in SysInfo system call. This solves a compilation problem on certain versions of Raspberry PI.
This is a pick of https://github.com/apptainer/apptainer/pull/1347
> fix: add missing cast in memoryusage calculation

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/build.go
- cmd/internal/cli/build_linux.go
- cmd/starter/c/include/starter.h
- cmd/starter/c/starter.c
- e2e/actions/actions.go
- e2e/imgbuild/imgbuild.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
- internal/pkg/runtime/engine/fakeroot/config/config.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/options.go
- pkg/runtime/engine/singularity/config/config.go
When we run in `--fakeroot` mode, the `starter` will call `setgroups` and reduce the group membership of the container process to `gid=0` only, inside the fakeroot id-mapped user namespace.
This removes supplementary group membership, and therefore prevents access to files on the host that are restricted by group ownership where the group is a supplementary group of the current user.
If, for example, `$HOME` is accessed via a supplementary group then it cannot be mounted inside the id-mapped user namespace created at the start of a `singularity build --fakeroot`. The build will then fail.
This PR adds a new flag `--no-setgroups` to skip the `setgroups` call in `--fakeroot` mode. This results in the container process *not* having its group membership changed. Host files accessible via host …
> --no-setgroups option for --fakeroot

- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/util/fs/mount/mount_linux.go
Pick #1765 
Fixes incomplete copyright info on files touched by PR #1755
> add missing copyright info to mount_linux.go, overlay_set_linux.go (release-3.11)

- cmd/internal/cli/actions.go
- cmd/internal/cli/build_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/oci_linux.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux_test.go
- internal/pkg/runtime/launcher/options.go
- internal/pkg/util/fs/overlay/overlay_linux.go
- internal/pkg/util/fs/overlay/overlay_linux_test.go
- internal/pkg/util/rootless/rootless.go
- internal/pkg/util/rootless/rootless_test.go
- pkg/syfs/syfs.go
Before this PR, if we are a non-root user we enter a root-mapped user namespace before calling `singularity oci run` at the end of the `--oci` launcher flow. If we are the root user, we do not enter any namespace. This means that bundle preparation, performed by the launcher, takes place outside of any namespaces.
As a non-root user, we want to perform bundle preparation inside a root-mapped user namespace. This is in order to benefit from fully-unprivileged FUSE operations when we start handling image mounts, plus advantages around cleanup on namespace exit. As a root user, we want to be inside a mount namespace to avoid polluting the host mount namespace with our container-specific mounts.
In this PR:
* As a non-root user, a root-mapped namespace is entered early, before   the oci …
> Enter namespaces earlier in --oci mode. 

- CHANGELOG.md
- e2e/actions/oci.go
- e2e/config/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
**fix: set correct $HOME in --oci mode when mount home = no**
When `mount home = no` is set in `singularity.conf`, we still need to
set the correct value for `$HOME` in the container... we just don't
want to mount it.
Fixes #1783
**support `--no-home` in `--oci` mode**
When `--no-home` is set on the CLI in `--oci` mode, do not mount
onto the container home directory.
Fixes #1780 …
> fix `mount home=no`, support `--no-home` in `--oci` mode

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
Stacked on #1784 - for rebase after it's merged.
Allow the `--no-mount` flag to be specified in `--oci` mode. This allows disabling the following mounts:
* proc
* sys
* devpts
* tmp
* home
Note that `dev` cannot be supported in `--oci` mode, as an OCI runtime *requires* that certain devices are present, and will include them in a `/dev` tmpfs.
We currently run similar to native mode `--compat`, so we don't mount the current working directory. Therefore, `--no-mount cwd` is not supported.
Similarly, `--compat` infers that `bind path` entries from `singularity.conf` are ignored. We may handle them in some way, in future.
- Fixes #1781 
- …
> oci: Support --no-mount, to extent possible

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux_test.go
The crun runtime supports skipping a setgroups call when entering a container. This is via an annotation on the runtime config.
Wire up the annotation to the `--no-setgroups` flag that we previously added in #1757 for native mode.
- Fixes #1550 …
> oci: support --no-setgroups with crun

- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
In the refactoring performed in a10b379bf8859ee35abca55f31a3576f202df792, the setting of the default CWD, and creation of `/etc/passwd`, was not correctly adapted.
We need to use our parsed / processed `l.homeDest` value for the container homeDir in all cases. With a nested root-mapped user namespace re-exec, the CLI passed value is not correct unless it is a custom value.
The first commit adds e2e coverage for this issue. The second commit is the fix.
- Fixes #1791  …
> fix: oci: correct $HOME -> default cwd / passwd handling

- CHANGELOG.md
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
Cherry-pick of https://github.com/apptainer/apptainer/pull/1451
Original Commit:
Fix seccomp filters to allow mknod/mknodat syscalls to create pipe/so…
…cket
and character devices with device number 0 for fakeroot builds.
> fakeroot: relax fakeroot seccomp rules (apptainer #1451)

- CHANGELOG.md
- e2e/imgbuild/imgbuild.go
- e2e/testdata/proot_multistage.def
- internal/pkg/build/assemblers/sandbox.go
- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/sources/packer_ext3.go
- internal/pkg/build/sources/packer_sandbox.go
- internal/pkg/build/stage.go
- pkg/util/archive/copy.go
- pkg/util/archive/copy_test.go
In builds, we use a wrapped `CopyWithTar` to handle `%file` copies between stages. The wrapper includes logic to perform ID mappings to ensure correct, squashed, ownership of files.
Within a `proot` build, a copy between stages has been found to hang. The ID mapping is the cause of the hang. Disable it for the particular circumstance of proot build between-stage copy.
- Fixes #1643 
- Added tests to validate this PR, …
> fix: disable IDMapping in inter-stage copy for proot builds

- CHANGELOG.md
- e2e/imgbuild/imgbuild.go
- e2e/testdata/proot_multistage.def
- internal/pkg/build/assemblers/sandbox.go
- internal/pkg/build/files/copy.go
- internal/pkg/build/files/copy_test.go
- internal/pkg/build/sources/packer_ext3.go
- internal/pkg/build/sources/packer_sandbox.go
- internal/pkg/build/stage.go
- pkg/util/archive/copy.go
- pkg/util/archive/copy_test.go
Pick #1795
In builds, we use a wrapped `CopyWithTar` to handle `%file` copies between stages. The wrapper includes logic to perform ID mappings to ensure correct, squashed, ownership of files.
Within a `proot` build, a copy between stages has been found to hang. The ID mapping is the cause of the hang. Disable it for the particular circumstance of proot build between-stage copy.
- Fixes #1643
- Added tests to validate …
> fix: disable IDMapping in inter-stage copy for proot builds (release-3.11)

- CHANGELOG.md
- e2e/security/oci.go
- e2e/security/security.go
- etc/conf/testdata/test_1.out.correct
- etc/conf/testdata/test_2.in
- etc/conf/testdata/test_2.out.correct
- etc/conf/testdata/test_3.in
- etc/conf/testdata/test_3.out.correct
- etc/conf/testdata/test_default.tmpl
- internal/pkg/runtime/engine/config/oci/config.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- pkg/util/singularityconf/config.go
**oci: Don't set inheritable/ambient caps in DefaultConfig**
The OCI DefaultConfig, used when creating a bundle from a SIF via `singularity oci mount`, no longer sets any inheritable or ambient capabilities. This matches other OCI container runtimes.
The capability set matches:
https://github.com/opencontainers/runc/blob/main/libcontainer/SPEC.md#security
**oci: set default capabilities in --oci mode**
When running in `--oci` mode, set default capabilities for the container.
When root inside the container, this means that effective / permitted / bounding match the oci.DefaultCaps set, per the oci runtime spec docs.
When non-root inside the container, this means that only bounding matches the oci.DefaultCaps set.
No other capabilities are set. `--oci` mode does not set any inheritable or …
> oci: wire up default capabilities

- CHANGELOG.md
- e2e/security/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- pkg/util/capabilities/capabilities.go
- pkg/util/capabilities/capabilities_test.go
- pkg/util/capabilities/process_linux.go
When `--keep-privs` is specified in `--oci` mode, keep effective capabilities on the container process, rather than set the default OCI capabilities.
Non-root users in the container receive the capabilities in the bounding set only.
- Fixes #1475  …
> oci: support --keep-privs

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/build.go
- cmd/internal/cli/build_linux.go
- cmd/starter/c/include/starter.h
- cmd/starter/c/starter.c
- e2e/actions/actions.go
- e2e/imgbuild/imgbuild.go
- internal/pkg/runtime/engine/config/starter/starter_linux.go
- internal/pkg/runtime/engine/fakeroot/config/config.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/options.go
- pkg/runtime/engine/singularity/config/config.go
Pick #1757
When we run in `--fakeroot` mode, the `starter` will call `setgroups` and reduce the group membership of the container process to `gid=0` only, inside the fakeroot id-mapped user namespace.
This removes supplementary group membership, and therefore prevents access to files on the host that are restricted by group ownership where the group is a supplementary group of the current user.
If, for example, `$HOME` is accessed via a supplementary group then it cannot be mounted inside the id-mapped user namespace created at the start of a `singularity build --fakeroot`. The build will then fail.
This PR adds a new flag `--no-setgroups` to skip the `setgroups` call in `--fakeroot` mode. This results in the container process *not* having its group membership changed. Host files …
> --no-setgroups option for --fakeroot (release-3.11)

- CHANGELOG.md
- pkg/util/capabilities/capabilities.go
> fix: correct capability.Name for CAP_BLOCK_SUSPEND (release-3.11)

- CHANGELOG.md
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/util/fs/files/files_linux_test.go
- internal/pkg/util/fs/files/group.go
- internal/pkg/util/fs/files/passwd.go
- internal/pkg/util/fs/files/passwd_test.go
- pkg/runtime/engine/singularity/config/config.go
Lookup and store user/group information in stage one prior to entering any namespaces to fix issue with winbind not correctly lookup user/group information when using user namespace.
This is a pick of https://github.com/apptainer/apptainer/pull/1368
Fixes: #696
> Lookup and store user/group information in stage one prior to creating namespaces (apptainer #1368)

- go.mod
- go.sum
The lack of update in the v1 branch of oras.land/oras.go for docker/docker v24 is causing issues bumping other dependencies in SingularityCE.
Switch temporarily to a sylabs fork with the update applied.
An upstream PR has been opened at:
https://github.com/oras-project/oras-go/pull/527
If merged, we can revert to upstream.
> deps: replace oras.land/oras-go with temporary fork

- e2e/imgbuild/imgbuild.go
- e2e/imgbuild/regressions.go
- internal/pkg/runtime/engine/singularity/container_linux.go
If all of the following conditions hold —
- The user inside the container is root
- The root filesystem is writable
- The root filesystem is not a tmpfs
— then writes to `/etc/passwd` or `/etc/group` are possible, and would be expected to persist from build to action stage (run/exec/shell) or across distinct actions (e.g. from one run to the next).
Under this exact combination of conditions, then, we inhibit bind-mounting modified versions of `/etc/passwd` and `/etc/group` from tmpfs storage into the container.
- Fixes #1812
> don't bind-mount /etc passwd & group when persistent writes possible

- CHANGELOG.md
- cmd/internal/cli/cache_clean_linux.go
- cmd/internal/cli/cache_list_linux.go
- internal/pkg/cache/cache.go
Add an oci-sif cache type, that will be used to store 1:1 conversions of OCI source images (e.g. docker://) into oci-sif format.
Refactor the help display for cache types, to list types programatically. This corrects and avoids incorrect/incomplete help information.
- Fixes #1857 …
> cache: Add oci-sif cache type

- .circleci/config.yml
- internal/pkg/util/bin/bin.go
- internal/pkg/util/bin/bin_no_singularity.go
- internal/pkg/util/bin/bin_singularity.go
- internal/pkg/util/bin/bin_test.go
If code in `pkg/` uses `bin.FindBin` then prior to this PR it would attempt to import `buildcfg`.
`buildcfg` is only available as part of a full build of SingularityCE, not when other code imports `pkg/`.
Add build tag gated variants of the private functions called by `bin.FindBin` that do not require `buildcfg`, to avoid this issue.
- Fixes #1823
- Added tests to validate this PR, linted with `make check`  and tested …
> ci: fix buildcfg check, and usage in bin.FindBin

- cmd/internal/cli/actions.go
- cmd/internal/cli/singularity.go
- internal/pkg/util/rootless/rootless.go
When we need to enter a mount or user namespace to begin oci-mode operation, do so as early as possible.
The CLI code has a lot of logic in it, much of which may run twice if we re-exec in `launchContainer`. This code may also cause side effects.
Re-execing much earlier, at the root command's `PersistentPreRun`, avoids these issues.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally …
> oci: re-exec as early as possible

- CHANGELOG.md
- cmd/internal/cli/actions.go
- e2e/actions/oci.go
- internal/pkg/build/oci/fetch.go
- internal/pkg/client/oci/ocisif.go
- internal/pkg/client/oci/pull.go
When a direct URI is provided for `run/shell/exec` in `--oci` mode, perform a pull through the cache to obtain an OCI-SIF image, and execute this.
`--oci` mode is no longer limited to OCI URIs or `oci-sif` as valid sources. If an `oci-sif` can be retrieved from the library/shub/oras/http/https protocols it can be run.
At this point, http/https is trivial to e2e-test so can be supported.
The barriers for the other protocols are primarily around pushing an image, rather than pulling. When push of oci-sif is supported and tested in follow-up PRs, then we can list the protocols as supported.
This PR also incorporates some small fixes for issues exposed by existing e2e-tests when the URI->oci-sif flow was enabled:
**fix: Set DockerHost in oci client sysCtx**
`DOCKER_HOST` was not being honored …
> oci: switch direct run/shell/exec from URI to oci-sif flow

- CHANGELOG.md
- e2e/actions/oci.go
- e2e/internal/e2e/env.go
- e2e/internal/e2e/image.go
- e2e/pull/pull.go
- e2e/push/push.go
- e2e/suite.go
Add e2e tests for push / pull / run against oras URIs, with OCI-SIF images.
This is a testing-only change. Because our oras code will push/pull any SIF image, it is working as of https://github.com/sylabs/singularity/pull/1882.
- Closes #1863 
- Closes #1864 
- …
> e2e: oci: oras push/pull/run

- internal/pkg/runtime/launcher/native/launcher_linux.go
- pkg/image/image.go
- pkg/image/ocisif.go
- pkg/image/ocisif_test.go
- pkg/image/sif.go
- pkg/image/sif_test.go
Add a minimal oci-sif image type to pkg/image, that does not implement any functionality other than oci-sif detection.
Ensure oci-sif detected as oci-sif, and are not detected as the existing sif type.
Modify the native launcher to return a more friendly error if a user attempts to run an oci-sif with it.
Prep work for #1861
Example...
```
$ singularity run alpine_latest.sif 
FATAL:   While checking image: native runtime does not support OCI-SIF images, use --oci mode
```
> pkg/image: Add minimal oci-sif type

- internal/pkg/client/oras/oras.go
After #1886 the check for a vaild SIF image must be relaxed to include `image.OCISIF`.
e2e-tests caught this bug on main after merge, but not on the PR CI run.
- Fixes #1890  …
> oras: fix push of oci-sif

- cmd/internal/cli/pgp.go
- cmd/internal/cli/sign.go
- cmd/internal/cli/verify.go
- internal/app/singularity/push.go
- internal/pkg/build/sources/verify_sif.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/oras/oras.go
- internal/pkg/signature/sign.go
- internal/pkg/signature/sign_test.go
- internal/pkg/signature/verify.go
- internal/pkg/signature/verify_ocsp.go
- internal/pkg/signature/verify_test.go
Implementation of SIF signing and verification was previously part of the large internal/pkg/app/singularity package.
This situation is problematic, as verification may need to be performed in builds, client pulls etc. Consequently internal/pkg/app/singularity had to be imported in lower level code.
Work on the OCI mode has exposed situations where this can result in import loops.
After recent re-writes, the Sign / Verify functions are not tied to other portions of internal/pkg/app/singularity. Therefore this PR moves them to a separate package to avoid import loops etc.
As a result, internal/pkg/app/singularity is now only imported by cmd/. …
> chore: Move i/p/a/singularity Sign/Verify functions to separate pkg

- CHANGELOG.md
- e2e/oci/oci.go
- internal/pkg/util/fs/squashfs/squashfs.go
- pkg/ocibundle/ocisif/bundle_linux.go
- pkg/ocibundle/sif/bundle_linux.go
The singularity SIF -> OCI bundle mount was previously performed with a kernel squashfs mount.
We will be using `pkg/ocibundle/sif` as the basis of `--oci` mode execution of singularity SIF (non oci-sif) images.
Switch the mount to use squashfuse for consistency. `--oci` mode does not perform kernel mounts from SIF.
- Fixes #1897
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with …
> oci: switch `oci mount` to squashfuse

- cmd/internal/cli/actions.go
- cmd/internal/cli/instance_start_linux.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/launcher.go
- internal/pkg/runtime/launcher/launcher_test.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
- pkg/image/image.go
- pkg/image/sif.go
- pkg/ocibundle/sif/bundle_linux.go
- pkg/ocibundle/sif/bundle_linux_test.go
Implement `ImageSpec()` for `ocibundle/sif`, so that it returns a usable OCI image spec. Use the OCI image config embedded in the SIF file, if it is present.
Implement basic execution of non-oci SIF images in `--oci` mode. This is acheived by calling the `/singularity.d/action/*` scripts inside the non-oci SIF container. Generation of container process args including the action script has been moved to a struct `ExecParams` in the `launcher` package, so that it can be called from the OCI launcher when needed.
e2e testing is currently minimal. As work proceeds to wire-up native runtime compatible env handling, and have the option to run in non- `--compat`, we will be adding proper tests of the behaviour of the non-oci containers.
Note that due to prior work, we already have handling of …
> oci: Execute non-oci SIF in --oci mode

- LICENSE_THIRD_PARTY.md
- cmd/internal/cli/pull.go
- cmd/internal/cli/push.go
- e2e/push/push.go
- go.mod
- internal/pkg/client/oci/auth.go
- internal/pkg/client/oci/ocisif.go
- internal/pkg/client/oci/push.go
Allow `singularity push` to push OCI-SIF images (only) to OCI registries specified by a `docker://` URI.
This code uses go-containerregistry rather than containers/image so that the implementation is simple to couple to the sylabs/oci-tools package.
- Fixes #1914  …
> push: OCI-SIF to docker:// OCI registries

- CHANGELOG.md
- cmd/internal/cli/keyserver.go
- cmd/internal/cli/loginargs.go
- cmd/internal/cli/registry.go
- cmd/internal/cli/remote.go
- docs/registry.go
- docs/remote.go
- e2e/registry/registry.go
- e2e/remote/remote.go
- e2e/suite.go
- internal/app/singularity/registry_list.go
- internal/app/singularity/registry_login.go
- internal/app/singularity/registry_logout.go
- internal/app/singularity/remote_list.go
- internal/app/singularity/remote_login.go
Moves the operations associated with OCI/Docker registries - `login`, `logout`, and `list` - from subcommands of the `remote` command (`singularity remote login [options] <registryURI>`, etc.) to their own dedicated command, `registry` (`singularity registry login [options] <registryURI>`, etc.). See the output of `singularity help registry` for more information.
Note that this does not **remove** the subcommands `login`, `logout`, and `list` from `singularity remote`, as they have separate functionality when given a remote endpoint (Singularity Cloud Services, Singularity Enterprise installs) as an argument. This former "duality" of functions of `singularity remote {login, logout, list}` is in fact a central part of the motivation for this PR. (See …
> move OCI/Docker-registry-related cmds from `remote` to their own cmd

- CHANGELOG.md
- internal/app/singularity/remote_list.go
Changes the format of the output of `singularity remote list` in accordance with option (a) outlined in https://github.com/sylabs/singularity/discussions/1639
Note that the output now includes _only_ the configured remote endpoints, to the exclusion of keyservers (see #1905) and OCI/Docker registries (see #1908).
- Fixes #1896
> clean up format of `remote list` output

- internal/pkg/remote/endpoint/client.go
- internal/pkg/remote/endpoint/client_test.go
- internal/pkg/remote/endpoint/service.go
- test/remote/config.example.json
Retrieve the `registryUri` value from the library service config for SCS/Enterprise remotes.
The concept of a service in the remote code is rather overloaded and inflexible. Add an internal use map that we can pull the `registryUri` into and out of. Hide it behind a single `RegistryURI` public fn.
Not the tidiest, but it works pending major overhaul of the remote / endpoint code. …
> remote: Make registryUri available for library

- .circleci/config.yml
- .gitmodules
- CHANGELOG.md
- INSTALL.md
- LICENSE_THIRD_PARTY.md
- internal/pkg/util/bin/bin.go
- internal/pkg/util/bin/bin_no_singularity.go
- internal/pkg/util/bin/bin_singularity.go
- mconfig
- mlocal/checks/project-post.chk
- mlocal/frags/Makefile.stub
- mlocal/frags/build_squashfuse.mk
The squashfuse project now includes a `squashfuse_ll` binary, which takes advantage of multi-threading for increased performance.
In addition, there is a bug in some older versions of squashfuse, packaged by Linux distributions, that affects execution of containers built on selinux systems.
Bundle the latest squashfuse 0.2.0 and build `squashfuse_ll` unless `--without-squashfuse` is specified.
In the case that `--without-squashfuse` is specified, prefer `squashfuse_ll` from `PATH`, falling back to `squashfuse`.
- Fixes #1910 …
> deps: Bundle squashfuse 0.2.0, prefer squashfuse_ll

- .circleci/config.yml
- INSTALL.md
- debian/control
- debian/singularity-ce.install
- dist/rpm/singularity-ce.spec.in
- mlocal/checks/project-post.chk
- mlocal/frags/build_conmon.mk
- mlocal/frags/build_squashfuse.mk
Fix builds of the rpm and deb packages after bundling of squashfuse.
* Add additional dependencies for squashfuse compilation across CI, packaging, and INSTALL.md.
* Adapt mlocal frag for CFLAGS set by distros which cause squashfuse compilation to fail.
* Use fuse3 on EL distros, as it is maintained and doesn't require the CRB repo on EL9.
* Use fuse (2) on Ubuntu, as if compiled with the fuse3 version provided by 22.04/20.04 squashfuse+overlay fails to work correctly.
- Fixes #1952  …
> fix: correct rpm/deb builds for squashfuse bundling

- cmd/internal/cli/actions.go
- cmd/internal/cli/pull.go
- cmd/internal/cli/push.go
- docs/content.go
- e2e/pull/pull.go
- internal/pkg/build/sources/conveyorPacker_library.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/library/push.go
- internal/pkg/client/library/registry.go
- internal/pkg/client/library/user_test.go
- internal/pkg/client/oci/nativesif.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/oci/push.go
- internal/pkg/client/ocisif/auth.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ociimage/fetch.go
- internal/pkg/ociimage/ociimage.go
- internal/pkg/ociimage/ociimage_test.go
- internal/pkg/ociimage/unpack.go
- pkg/ocibundle/native/bundle_linux.go
When `singularity push` is provided an OCI-SIF image file and a `library://` URI, push as a single layer squashfs OCI image to the OCI registry that backs the library service. Existing push behaviour for native SIF through the library API remains.
When `singularity pull --oci` is provided a `library://` URI with a path that points to a single layer squashfs OCI image in the backing OCI registry, pull to a local OCI-SIF image.
When `singularity pull` is provided a `library://` URI and no `--oci` flag, try a native SIF library API pull first. If that fails and the error indicates the image is an OCI image then try an OCI-SIF pull.
The push/pull process involves discovering the URI of the backing OCI registry, retrieving an authentication token, and translating `library://` URIs to OCI …
> library:// oci-sif push/pull

- e2e/keyserver/keyserver.go
- internal/app/singularity/keyserver_list.go
Adds an indicator for the in-use (="default") remote endpoint in the output of `singularity keyserver list`.
> add indicator for the default remote in `keyserver list` output

- cmd/internal/cli/oci_linux.go
- docs/content.go
- internal/app/singularity/oci_linux.go
The hidden OCI run-wrapped command has not been used since we changed the OCI mode flow to enter a user namespace as early as possible.
Remove the redundant code. …
> chore: remove unused oci run-wrapped command

- CHANGELOG.md
- e2e/actions/actions.go
- internal/pkg/runtime/engine/singularity/container_linux.go
Cherry-pick two Apptainer PRs:
Create current working directory in container
https://github.com/apptainer/apptainer/pull/1374
fix: Handle CWD symlink differences between host/container
https://github.com/apptainer/apptainer/pull/1365
The effect of these cherry-picks is that we will now create the host CWD path in the container, if it is not already present, so that it can be mounted & entered in more cases.
However, if the CWD exists on the container and inside the host with a path containing symlinks to different locations, we will not perform the mount. There is no other sensible choice in this case.
- Fixes #1726 
- Added changes to …
> Revise CWD creation / symlink handling in native mode (apptainer 1365,1374)

- .vscode/settings.json
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/util/crypt/crypt_dev_test.go
- internal/pkg/util/fs/overlay/overlay_item_linux.go
- internal/pkg/util/fs/overlay/overlay_item_linux_test.go
- internal/pkg/util/fs/squashfs/squashfs.go
- internal/pkg/util/fs/squashfs/squashfs_singularity.go
- pkg/ocibundle/tools/overlay_linux.go
In native mode, things are nosuid mounted by default, and `--allow-setuid` is available to the root user to relax this.
In OCI mode, the `nosuid` option on mounts is not security critical as when run by an unpriv user, we always perform the mounts within a root-mapped user namespace.
Regardless, match the behavior with native mode by default, and allow any user to specify `--allow-setuid` to remove the `nosuid` from appropriate mounts.
This requires making behaviour configurable for the `OverlayItem` mounts underlying an `OverlaySet`, as well as for mounts added by the launcher to the OCI runtime config.
Includes some tidy up of overlay item option handling, and adds tests to check mount options on overlay items.
- Fixes #1469 
- Read the [Guidelines for …
> oci: Implement --allow-setuid, match nosuid mount to native mode

- CHANGELOG.md
- cmd/internal/cli/pull.go
- e2e/pull/concurrency.go
- e2e/pull/pull.go
- internal/pkg/util/uri/uri.go
- internal/pkg/util/uri/uri_test.go
When a user performs a `singularity pull --oci` without specifying a specific output filename, use `.oci.sif` for the suffix of the generated filename.
- Fixes #1885  …
> pull: use .oci.sif suffix for pull --oci

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux_test.go
- internal/pkg/runtime/launcher/options.go
Add a new flag, `--no-pid` which prevents the use of a PID namespace, when running a container with `--compat` / `--containall` / `--oci` which infer `--pid`.
Allows working around potential issues with applications across parallel container executions that expect to be working in a common PID namespace.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make …
> feat: --no-pid action flag

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/options.go
**cmd: Add --no-compat flag**
Add a --no-compat flag intended to disable default --compat like behaviour for OCI mode, and revert to default native runtime behaviour.
Pass down to launchers.
**no-compat: bind $HOME /tmp /var/tmp**
When --oci mode is run with --no-compat:
* Bind $HOME into the container, unless disabled otherwise.
* Bind /tmp /var/tmp into the container, unless disabled otherwise.
- Fixes #1977 
- Added …
> --no-compat, add flag and $HOME /tmp /var/tmp binds

- CHANGELOG.md
- e2e/actions/oci.go
- e2e/config/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- pkg/util/singularityconf/config.go
When `--oci` mode is run with `--no-compat`, follow native mode default behaviour of binding the entire `/dev` from the host into the container by default.
If `mount dev = minimal` in `singularity.conf` then we don't mount the entire host `/dev`, but use the minimum for an OCI container.
If `mount dev = no` in `singularity.conf` or `--no-mount dev` supplied then report an error as we require dev. Error now, instead of warn, so it's clear we can't acheive the native mode behavior.
If `mount devpts = no` in `singularity.conf` or `--no-mount devpts` supplied then report an error as we require devpts. Error now, instead of warn, so it's clear we can't acheive the native mode behavior.
- Fixes #1981 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRI …
> no-compat: bind full /dev

- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/app/singularity/oci_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/util/rootless/rootless.go
When we are using os.exec in the OCI-mode execution flow, we must handle any signals we receive, and proxy them to the container.
For non-root users, we are using the fakeroot starter (which already proxies signals) to re-exec singularity in a userns. Proxy signals to the container via `runc/crun kill`.
For root users, we are using os.Exec to re-exec singularity in a userns, so we need to add signal proxying across this boundary in `rootless.RunInMountNS`.
Also, we need to propagate signals to exit codes correctly.
- Fixes #1779 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if …
> oci: enable signal propagation

- CHANGELOG.md
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
- pkg/util/singularityconf/config.go
When `--oci` mode is run with `--no-compat`, bind the `bind path` entries listed in `singularity.conf` into the container.
Individual entries can be disabled with `--no-mount <dest>`. All entries can be disabled with `--no-mount bind-paths`.
- Fixes #1978
- Based …
> no-compat: bind mount bind paths from singularity.conf

- CHANGELOG.md
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
When `--oci` mode is run with `--no-compat`, bind the CWD from the host, and enter the container there.
The CWD bind can be disabled with `--no-mount cwd`.
- Fixes #1988 …
> no-compat: bind and enter cwd

- CHANGELOG.md
- e2e/actions/oci.go
- e2e/config/config.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
When running in OCI-mode with `--no-compat`, the container rootfs should be read-only by default, as in native mode.
Allow `--writable-tmpfs` to re-enable the writable tmpfs behaviour.
- Fixes #1980  …
> no-compat: read-only unless --writable-tmpfs requested

- CHANGELOG.md
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
When `--oci` mode is run with `--no-compat`, propagate the host umask into the container unless `--no-umask` is also used.
This matches native mode umask behaviour.
- Fixes #1982  …
> no-compat: propagate host umask

- e2e/actions/actions.go
- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
- internal/pkg/util/fs/fuse/fuse_mount_linux.go
- internal/pkg/util/fs/overlay/overlay_item_linux.go
- internal/pkg/util/fs/overlay/overlay_item_linux_test.go
- internal/pkg/util/fs/overlay/overlay_linux.go
- internal/pkg/util/fs/overlay/overlay_set_linux.go
- pkg/ocibundle/tools/overlay_linux.go
Add support for bind-mounting bare images in OCI mode (using `-B`/`--bind`, with [identical syntax](https://docs.sylabs.io/guides/latest/user-guide/bind_paths_and_mounts.html#image-mounts) to the corresponding native-mode flag).
- Fixes #1471
> oci: support --bind of images (bare)

- CHANGELOG.md
- e2e/env/env.go
- e2e/env/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
_Stacked on #1991_ - content of this PR is in 2nd commit.
When entering a native SIF container, we apply the container-defined environment by sourcing scripts in `/.singularity.d/env` from the relevant action script.
Any environment variable set in these scripts will replace any value set from the OCI runtime config.
To allow `SINGULARITYENV_` / `--env` / `--env-file` to override container-defined env vars, we have to inject them via a script that exports them in `/singularity.d/env`.
We use the script filename `98-singularityenv.sh` as it must:
* Run *after* `95-apps.sh` which sets SCIF App specific variables (which we should be able to override).
* Run *before* `99-base.sh` which mutates `LD_LIBRARY_PATH`.
In addition, we have to consider that:
* In OCI mode, by default we emulate …
> oci: allow override of native SIF container env var

- internal/pkg/syecl/syecl.toml.example
- pkg/util/singularityconf/config.go
It is trivial for a user to bypass configured container executions restrictions if the host has unprivileged user namespace creation enabled. This is not something SingularityCE can guard against, except by making it clear to administrators at the point they would configure those limits.
Add warnings to the relevant configuration files. …
> conf: Add better warnings r.e. user namespaces & container limits

- internal/pkg/syecl/syecl.toml.example
- pkg/util/singularityconf/config.go
It is trivial for a user to bypass configured container executions restrictions if the host has unprivileged user namespace creation enabled. This is not something SingularityCE can guard against, except by making it clear to administrators at the point they would configure those limits.
Add warnings to the relevant configuration files. …
> conf: Add better warnings r.e. user namespaces & container limits (release-3.11)

- e2e/env/env.go
- e2e/env/oci.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
- internal/pkg/util/env/clean.go
- internal/pkg/util/env/clean_test.go
- internal/pkg/util/env/env.go
- internal/pkg/util/env/env_test.go
In `-oci` mode, make `--no-compat` handle host environment in the same manner as the native runtime.
Most environment variables on the host are passed into the container, as long as they haven't been overridden by the container image or the user.
For OCI-SIF images, this is handled when computing the runtime config.
For native SIF images, this is handled by injecting the variables through a shell script that runs in `/.singularity.d/env` processing.
Note that we now always set `TERM` and proxy environment variables in the container using these mechanisms, regardless of `--no-compat`. The proxy env vars are important for frictionless use of Singularity in isolated environments.
- Fixes #1979
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTIN …
> oci: host environment handling for --no-compat

- .golangci.yml
From #2024, enable the linters that don't (yet) report any lint. …
> chore: enable additional linters without lint

- CHANGELOG.md
- LICENSE_THIRD_PARTY.md
- cmd/internal/cli/actions.go
- cmd/internal/cli/build_linux.go
- cmd/internal/cli/pull.go
- cmd/internal/cli/singularity.go
- e2e/docker/docker.go
- e2e/pull/pull.go
- internal/pkg/build/sources/conveyorPacker_library.go
- internal/pkg/build/sources/conveyorPacker_library_test.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/oci/nativesif.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ociimage/digest.go
- internal/pkg/ociimage/digest_test.go
- internal/pkg/ociimage/util.go
- internal/pkg/ociplatform/cpuinfo.go
- internal/pkg/ociplatform/cpuinfo_linux.go
- internal/pkg/ociplatform/cpuinfo_linux_test.go
- internal/pkg/ociplatform/ociplatform.go
- internal/pkg/ociplatform/ociplatform_test.go
- pkg/build/types/bundle.go
When pulling from OCI sources:
* Both OCI-SIF and other pulls will now support `--platform` to specify a source image platform.
* `--arch` can be used to infer `--platform linux/<arch>`.
You can now e.g.
```
singularity pull --platform linux/arm64 docker://alpine
```
... and retrieve an arm64 SIF on a non-arm64 machine.
When pulling from library sources:
* Both OCI-SIF and native SIF pulls will now support `--platform`. When pulling a native SIF via the library native protocol, any variant is ignored.
* `--arch` can be used to infer `--platform linux/<arch>`.
The `--arch` and `--platform` flags have been made common, in anticipation that they can be added to `singularity build`, to select a platform for binfmt_misc/qemu-static assisted cross-platform builds.
- Fixes #2015 
- Read the …
> WIP - pull: Improved --arch and --platform handling

- cmd/internal/cli/keyserver.go
- cmd/internal/cli/registry.go
- docs/keyserver.go
- e2e/keyserver/keyserver.go
- e2e/remote/remote.go
- internal/app/singularity/keyserver_list.go
Add `--config` option to `keyserver` command. (This was available when keyservers were manipulated using the `remote` command, but not ported over to the `keyserver` command until this PR.) Utilize this flag in e2e testing of `keyserver` command.
Honor optional `remoteName` argument to `keyserver list` subcommand to list only the keyservers configured for a particular remote endpoint. Add e2e tests for this.
- Fixes #2034
> add --config to `keyserver` cmd, honor optional remoteName arg

- LICENSE_THIRD_PARTY.md
- internal/pkg/ociplatform/cpuinfo.go
- internal/pkg/ociplatform/database.go
- internal/pkg/ociplatform/ociplatform.go
- internal/pkg/ociplatform/ociplatform_test.go
In order to ensure that we can pull the correct image on ARM systems:
* `linux/arm64/v8` needs to be normalized to `linux/arm64`
* `linux/arm` needs to be normalized to `linux/arm/v7`
Bring across a small amount of additional code from containerd/containerd (under a compatible license) to perform the normalization.
- Fixes #2039 
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with …
> fix: normalize OCI platform arch & variant

- internal/pkg/runtime/launcher/oci/launcher_linux.go
With older versions of `crun` (e.g. 0.12.1, the version currently available on Ubuntu 20.04), specifying `"none"` as the `type` field for a bind mount (even when the `options` field includes `"bind"`) in the config.json of the OCI bundle results in undesired behavior. In particular, bind-mounts of regular files specified in the config.json result in the destinations of those mounts being created as directories (instead of files), and the actual bind-mount then failing (due to a file-vs.-dir mismatch; even though the error msg generated by crun doesn't exactly make it clear that this is the problem...).
This PR replaces `"none"` with `"bind"` in the `type` field of bind-mounts generated in internal/pkg/runtime/launcher/oci/launcher_linux.go
> replace "none" with "bind" in Type field of OCI-mode bind mounts

- internal/pkg/ociplatform/ociplatform_test.go
On non-AMD64 for arch/variant normalization occurs, Test_sysCtxToPlatform was checking for incorrect default values.
Fix the test to look for normalized values.
- Fixes #2043 …
> fix: correct Test_sysCtxToPlatform for non-AMD64

- internal/pkg/runtime/launcher/oci/launcher_linux.go
Fix propagation of errors encountered when creating the OCI-mode bundleDir in Exec() in internal/pkg/runtime/launcher/oci/launcher_linux.go
> fix: error-handling upon creation of OCI bundledir

- INSTALL.md
Provide links to locations where a `squashfs-tools` containing `sqfstar` can be found on EL and SUSE distros.
Add `squashfs-tools-ng` to Debian/Ubuntu deps to provide `tar2sqfs`.
This is still a minimal solutions - it's hoped to provide a COPR for either new `squashfs-tools` or `squashfs-tools-ng` on EL shortly.
- Fixes #1973 …
> docs: add info r.e. obtaining sqfstar / tar2sqfs

- e2e/actions/oci.go
Gate the e2e subtest "oci-sif-http" in the ociRun() function in e2e/actions/oci.go so that it only runs on the `amd64` architecture, and add a couple of missing `e2e.EnsureXYZ(t, c.env)` calls at the top of ociRun()
- Fixes #2046
> e2e: gate ociRun() oci-sif-http subtest for amd64 only

- debian/control
Require `crun` only when >=1.5.0 is available. Otherwise use `runc`.
Add `squashfs-tools-ng` as a `Recommends`. It is not a `Requires` in case someone cannot enable the Ubuntu universe repos, and does not want to use `--oci` mode.
Add missing conflicts for singularitypro311 while we are here.
Note - I temporarily enabled the deb build CI on this PR to verify it succeeds:
The checks on the commit for review will not show this.
- Fixes #1974 …
> deb: update dependencies

- internal/pkg/test/tool/require/require.go
- internal/pkg/util/bin/bin.go
- internal/pkg/util/fs/overlay/overlay_set_linux_test.go
Change how we search for the external tool `fusermount` so that we first look for `fusermount3` and then search for `fusermount` as a fallback.
Also updates the require.Command() function in internal/pkg/test/tool/require/require.go so that it first tries to find the command using the bin.FindBin() function, and only if that fails, tries exec.LookPath(). This allows us to implicitly incorporate the fallback logic of bin.FindBin() when gating tests using require.Command() (so, for example, after this PR, `require.Command("fusermount")` will allow the test to run even if only `fusermount3` is installed, and vice versa).
- Fixes #2047
> fuse: look for "fusermount3" first, w/"fusermount" as fallback

- e2e/actions/oci.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
runc will fail when run unprivileged, with `/dev` is specified as a bind mount in the `config.json`.
At this point I don't see an easy route to making the `/dev` bind mount work.
Fall back to a minimal dev with `--no-compat` and runc to avoid the issue.
- Fixes #2058 …
> oci: fall back to minimal /dev with --no-compat & runc

- .golangci.yml
- cmd/internal/cli/actions.go
- cmd/internal/cli/build.go
- cmd/internal/cli/inspect.go
- docs/remote.go
- e2e/cgroups/cgroups.go
- e2e/config/config.go
- e2e/internal/e2e/imageverify.go
- internal/app/singularity/plugin_list_linux.go
- internal/app/starter/master_linux_test.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/plugin/meta.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/signature/verify_ocsp.go
- internal/pkg/test/tool/doc.go
- internal/pkg/util/crypt/crypt_dev.go
- internal/pkg/util/interactive/interactive_test.go
- pkg/util/capabilities/process_linux.go
- pkg/util/fs/proc/proc_linux_test.go
Enable the `dupword` linter in golangci-lint, and perform fixes / add `nolint:` directives, as appropriate, in code.
> lint: enable dupword + corresponding fixes

- .golangci.yml
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/syecl/syecl.go
Enable the `exportloopref` linter in golangci-lint, and perform fixes, as appropriate, in code.
> lint: enable exportloopref + corresponding fixes

- dist/rpm/singularity-ce.spec.in
Use fuse instead of fuse3 on SLES12.
Use explicit make instead of macros that do not exist on SLES12.
Was run through CI to check no regression for EL rpm builds:
- Fixes #2036 …
> rpm: fix rpm build on SLES12

- .golangci.yml
- internal/pkg/plugin/binary.go
- internal/pkg/runtime/engine/config/oci/generate/generate.go
- pkg/build/types/parser/deffile.go
- pkg/image/sif_test.go
Enable the `prealloc` linter in golangci-lint, and perform fixes, as appropriate, in code.
> lint: enable prealloc + corresponding fixes

- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
When `/sys` or `/proc` are requested to be bind mounted into a container, the bind mount options must be at least as restrictive as on the host.
`/sys` and `/proc` filesystems are generally `nosuid,nodev,noexec`.
`runc` doesn't try more restrictive options on a failed mount, so we have to ensure `nosuid,nodev,noexec` are always set when a bind source is `/sys` or `/proc`.
Tested with `runc` on Fedora - which exhibits the failures shown in the issues.
- Fixes #2069 
- Fixes #2070 …
> fix: oci: explicit bind options for /sys /proc sources

- .golangci.yml
- cmd/internal/cli/singularity.go
- e2e/e2e_test.go
- e2e/suite.go
- internal/pkg/runtime/engine/fakeroot/engine_linux.go
- internal/pkg/runtime/engine/singularity/cleanup_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/runtime/engine/singularity/monitor_linux.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/engine/singularity/process_linux.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- internal/pkg/util/fs/helper.go
- internal/pkg/util/fs/layout/manager.go
- internal/pkg/util/passwdfile/passwdfile_unix.go
- internal/pkg/util/rootless/rootless.go
- pkg/cmdline/flag.go
- pkg/image/image.go
- pkg/network/network_linux.go
- pkg/util/fs/proc/proc.go
- pkg/util/loop/loop.go
- pkg/util/loop/loop_test.go
- test/certs/gen_certs.go
Enable the `forcetypeassert` linter in golangci-lint, and perform fixes / add `nolint:` directives, as appropriate, in code.
> lint: enable forcetypeassert + corresponding fixes

- dist/rpm/singularity-ce.spec.in
Use `@PACKAGE_VERSION@-@PACKAGE_RELEASE@` as the version specifier in the call to `mconfig -V` in our rpm spec.
The RPM spec's own `%{release}`, which will still be used for the name of the RPM package itself, includes `%{?dist}` which may not be semver compliant.
Additionally, using `@PACKAGE_VERSION@` instead of `%{version}` preseves semver style `-` for pre-releases instead of rpm style `~` for pre-releases in the `singularity --version / version`.
We are aiming for semver compliance - our reported version number should be semver compliant.
- Fixes #2073 …
> fix: rpm: use semver version-release for mconfig -V

- .golangci.yml
- e2e/docker/docker.go
- e2e/gpu/gpu.go
- e2e/imgbuild/imgbuild.go
- internal/app/singularity/keyserver_list.go
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/cgroups/manager_linux_v1_test.go
- internal/pkg/cgroups/manager_linux_v2_test.go
- internal/pkg/client/progress.go
- internal/pkg/remote/endpoint/client_test.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/util/fs/squashfs/squashfs.go
- pkg/build/types/parser/deffile.go
- pkg/build/types/parser/deffile_test.go
- pkg/util/archive/copy.go
- pkg/util/capabilities/capabilities.go
- pkg/util/unix/socket_test.go
Enable the `nolintlint` linter in golangci-lint, and perform fixes, as appropriate, in code.
> lint: enable nolintlint + corresponding fixes

- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
Replace use of `[]string` with `map[string]bool` for keeping track of mount options in the addBindMount() method in internal/pkg/runtime/launcher/oci/mounts_linux.go
> oci: use map for mount options in addBindMount()

- e2e/inspect/inspect.go
Use bin.FindBin() to locate the `unsquashfs` command in e2e/inspect/inspect.go
- Fixes #2079
> fix: e2e: use FindBin() to locate unsquashfs in inspect.go

- e2e/inspect/inspect.go
Pick #2085 
Use bin.FindBin() to locate the `unsquashfs` command in e2e/inspect/inspect.go
- Fixes #2079
> fix: use FindBin() to locate unsquashfs (release-4.0)

- .golangci.yml
- e2e/docker/regressions.go
- internal/pkg/test/privilege_linux.go
- internal/pkg/util/bin/bin_test.go
Enable the `tenv` linter in golangci-lint, and perform fixes / add `nolint:` directives, as appropriate, in code.
> lint: enable tenv + corresponding fixes

- .golangci.yml
- e2e/docker/regressions.go
- internal/pkg/test/privilege_linux.go
- internal/pkg/util/bin/bin_test.go
Pick #2088 
Enable the `tenv` linter in golangci-lint, and perform fixes / add `nolint:` directives, as appropriate, in code.
> lint: enable tenv + corresponding fixes (release-4.0)

- .golangci.yml
- e2e/instance/instance_utils.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/util/fs/mount/system_linux_test.go
Enable the `unparam` linter in golangci-lint, and add `nolint:` directives, as appropriate, in code.
> lint: enable unparam + corresponding fixes

- internal/pkg/util/fs/squashfs/squashfs.go
This PR improves the way the output of external commands is handled inside internal/pkg/util/fs/squashfs/squashfs.go - in particular, if an external command exits with an error, the error propagated to the caller will include the stdout and stderr output the command.
> add better handling of cmd output in squashfs code

- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/config/config.go
- e2e/inspect/inspect.go
Use bin.FindBin() to locate the `mkfs.ext3` command in e2e tests.
- Fixes #2078
> e2e: look for mkfs.ext3 using FindBin()

- internal/pkg/util/fs/squashfs/squashfs.go
Pick #2105 
This PR improves the way the output of external commands is handled inside internal/pkg/util/fs/squashfs/squashfs.go - in particular, if an external command exits with an error, the error propagated to the caller will include the stdout and stderr output the command.
> add better handling of cmd output in squashfs code (release-4.0)

- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/config/config.go
- e2e/inspect/inspect.go
Pick #2106 
Use bin.FindBin() to locate the `mkfs.ext3` command in e2e tests.
- Fixes #2078
> e2e: look for mkfs.ext3 using FindBin() (release-4.0)

- CHANGELOG.md
- docs/plugin.go
Pick #2120 
Add note to the help messages of the `plugin compile` and `plugin install` subcommands, emphasizing that plugins should only be compiled/installed if they are from a trusted source
> plugin: add clarification about plugin trust (release-3.11)

- CHANGELOG.md
- docs/plugin.go
Pick #2120 
Add note to the help messages of the `plugin compile` and `plugin install` subcommands, emphasizing that plugins should only be compiled/installed if they are from a trusted source
> plugin: add clarification about plugin trust (release-4.0)

- mlocal/frags/go_common_opts.mk
The `-race` to `go test` is not supported on `i686` (on platforms like Raspberry Pi OS).
This PR changes the test that suppresses `-race` in mlocal/frags/go_common_opts.mk so it includes not only `ppc64le` but also, disjunctively, `i386' and `i686` as well.
> fix: make: change cond for setting GO_RACE to handle i386 & i686

- cmd/internal/cli/singularity.go
- e2e/actions/oci.go
The check for --oci and --no-oci being incorrectly used together was incorrect.
Fix the logic, and add an e2e test that catches this.
- Fixes #2133 …
> oci: correct check for --oci and --no-oci together

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/singularity.go
- e2e/actions/actions.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/options.go
- pkg/ocibundle/ocisif/bundle_linux.go
- pkg/runtime/engine/singularity/config/config.go
- pkg/util/singularityconf/config.go
In OCI-mode, if using OCI-SIF fails (e.g. `squashfuse`/`squashfuse_ll` missing or don't work, `sqfstar`/`tar2sqfs` missing, etc.), fall back to a filesystem-based strategy: unpack the OCI container into a temporary directory, and run it from there.
Add an `tmp sandbox` configuration option to `singularity.conf` (default: `yes`) to control whether unpacking containers to temporary sandbox dirs is allowed, as well as a `--no-tmp-sandbox` flag to disable this behavior via the command-line. NOTE: This configuration option & flag also control whether unpacking the container to a temporary sandbox dir is allowed in the native user-namespace flow.
- Fixes #2095
> oci: fallback to temp dir if OCI-SIF unsupported

- internal/pkg/runtime/launcher/oci/launcher_linux.go
Adds explicit code to internal/pkg/runtime/launcher/oci/launcher_linux.go:696 that will block unpacking of image to temporary sandbox dir in OCI mode, based on `tmp sandbox` option in `singularity.conf` as well as `--no-tmp-sandbox` flag (and corresponding `SINGULARITY_NO_TMP_SANDBOX` env var).
This mirrors the native-mode code found at internal/pkg/runtime/launcher/native/launcher_linux.go:996 and internal/pkg/runtime/launcher/native/launcher_linux.go:1072
Currently, this is strictly speaking redundant, as the image-extracting code will only happen in OCI mode if fallback flow is chosen in cmd/internal/cli/actions.go, and that code itself consults the aforementioned option / flag / env var (in the interest of producing more informative warnings/errors). But adding this code here ensures …
> oci: explicitly gate unpacking of OCI image with appropriate options

- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #2139 
Adds explicit code to internal/pkg/runtime/launcher/oci/launcher_linux.go:696 that will block unpacking of image to temporary sandbox dir in OCI mode, based on `tmp sandbox` option in `singularity.conf` as well as `--no-tmp-sandbox` flag (and corresponding `SINGULARITY_NO_TMP_SANDBOX` env var).
This mirrors the native-mode code found at internal/pkg/runtime/launcher/native/launcher_linux.go:996 and internal/pkg/runtime/launcher/native/launcher_linux.go:1072
Currently, this is strictly speaking redundant, as the image-extracting code will only happen in OCI mode if fallback flow is chosen in cmd/internal/cli/actions.go, and that code itself consults the aforementioned option / flag / env var (in the interest of producing more informative warnings/errors). But adding this code …
> oci: explicitly gate unpacking of OCI image with appropriate options (release-4.0)

- cmd/starter/main_linux.go
- mconfig
Pick https://github.com/apptainer/apptainer/pull/719
Building with a custom build dir was broken due to removal of custom $builddir include from CGO_CFLAGS in `mconfig` in PR #100 
This PR adds that custom include back in `mconfig`, while retaining the change to cmd/starter/main_linux.go from PR #100 which facilitates code traversal by linters, IDEs, etc.
- Fixes #2012
> mconfig: add custom $builddir include back into CGO_CFLAGS

- cmd/starter/main_linux.go
- mconfig
Pick #2141 
Pick https://github.com/apptainer/apptainer/pull/719
Building with a custom build dir was broken due to removal of custom $builddir include from CGO_CFLAGS in `mconfig` in PR #100 
This PR adds that custom include back in `mconfig`, while retaining the change to cmd/starter/main_linux.go from PR #100 which facilitates code traversal by linters, IDEs, etc.
- Fixes #2012
> mconfig: add custom $builddir include back into CGO_CFLAGS (release-3.11)

- cmd/starter/main_linux.go
- mconfig
Pick #2141 
Pick https://github.com/apptainer/apptainer/pull/719
Building with a custom build dir was broken due to removal of custom $builddir include from CGO_CFLAGS in `mconfig` in PR #100 
This PR adds that custom include back in `mconfig`, while retaining the change to cmd/starter/main_linux.go from PR #100 which facilitates code traversal by linters, IDEs, etc.
- Fixes #2012
> mconfig: add custom $builddir include back into CGO_CFLAGS (release-4.0)

- cmd/internal/cli/build.go
Rephrases the help string for the `--build-arg` flag (to the `build` command) to make the part about _variable=value_ format more salient.
> improve help string for --build-arg

- examples/lima/README.md
Fix discussion of homedir mounting into `singularity` running inside a lima VM to address macOS `/Users` vs. Linux `/home` distinction.
> fix discussion of homedir mounting

- internal/pkg/runtime/launcher/native/launcher_linux.go
- pkg/image/image.go
- pkg/image/ocisif.go
- pkg/image/ocisif_test.go
- pkg/image/sif.go
- pkg/image/sif_test.go
- pkg/ocibundle/native/bundle_linux.go
Detect OCI-SIF images and advise the user that they are only supported on Singularity versions 4.0 and above.
This PR cherry-picks https://github.com/sylabs/singularity/pull/2183/commits/084fed552decb9f92ddaea10892353896aed8aa9 ("pkg/image: Add minimal oci-sif type") from 4.0, and then adds code specific to the `release-3.11` branch in a second commit.
In that second commit, the changes in internal/pkg/runtime/launcher/native/launcher_linux.go are not strictly speaking necessary, as the changes to pkg/ocibundle/native/bundle_linux.go would be sufficient to catch the relevant condition as it stands in the `release-3.11` branch right now. But the changes to internal/pkg/runtime/launcher/native/launcher_linux.go are there to guard against potential future scenarios in which we add new code …
> detect and advise re:OCI-SIF images on older versions (release-3.11)

- .circleci/config.yml
Bump Go version in CircleCI config to 1.21.1 (done ahead of release 3.11.5).
> bump Go version in CircleCI config to 1.21.1 (release-3.11)

- README.md
At some point, our zenodo all versions DOI changed, so that 3.9.0 and above are not at the DOI for older versions.
Update to the newer all-versions DOI.
Fixes #2119
> docs: Fix zenodo link.

- README.md
At some point, our zenodo all versions DOI changed, so that 3.9.0 and above are not at the DOI for older versions.
Update to the newer all-versions DOI.
Fixes #2119
> docs: Fix zenodo link (release-4.0)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/regressions.go
- e2e/testdata/regressions/issue_1950.def
- internal/pkg/runtime/engine/singularity/container_linux.go
Pick #2213 to release-4.0
It is not uncommon for `/var/tmp` in a container to be a symlink onto `/tmp`. In this case, singularity will currently:
* Mount host `/tmp` onto the container `/tmp`
* Mount host `/var/tmp` onto the container `/tmp` through the symlink.
Check whether `/var/tmp` resolves to the same place as `/tmp` in the container, and do not mount it if this is the case.
We have to move `addTmpMount` to run under a `RunBeforeTag` call because we need to have the container rootfs in place to to inspect for symlinks. Because the sources of the mounts may be a tmpfs (--contain), or inside a --workdir, we still have to handle creation of the source dirs earlier.
- Fixes #1950
- Fixes #1331
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRI …
> fix: Don't mount /var/tmp pointing to /tmp in container (release-4.0)

- e2e/actions/regressions.go
Corrects the `profile` field of the "native binds" subtest of the issue1950() e2e regression test.
> e2e: fix profile in issue1950() regression "native binds" subtest

- e2e/actions/regressions.go
Pick #2223 
Corrects the `profile` field of the "native binds" subtest of the issue1950() e2e regression test.
> e2e: fix profile in issue1950() regression "native binds" subtest (release-4.0)

- CHANGELOG.md
- e2e/registry/registry.go
- e2e/suite.go
- internal/pkg/remote/credential/login_handler.go
Changes creation of JSON-encoded OCI credential files so that they encode the `"auth"` field, rather than `"username"`/`"password"`.
- Fixes #2226
> OCI credentials storage: only store "auth" field

- CHANGELOG.md
- e2e/registry/registry.go
- e2e/suite.go
- internal/pkg/remote/credential/login_handler.go
Pick #2227 
Changes creation of JSON-encoded OCI credential files so that they encode the `"auth"` field, rather than `"username"`/`"password"`.
- Fixes #2226
> OCI credentials storage: only store "auth" field (release-4.0)

- e2e/actions/oci.go
The `TestE2E/PAR/ACTIONS/ociCdi/OCIUser/KmsgDevice/KmsgDevice` test in e2e/actions/oci.go requires cgroups v2. This PR adds appropriate gating so that this test only runs if cgroups v2 is available.
- Fixes #2245
> e2e: gate KmsgDevice OCI-CDI test to cgroups v2 only

- cmd/internal/cli/singularity.go
- e2e/actions/actions.go
- e2e/docker/docker.go
- e2e/instance/instance.go
The goal of this PR is to work out the relationship between the recently added `--authfile` facility (#2225) and the `DOCKER_xyz` env vars (currently, `DOCKER_USERNAME`, `DOCKER_PASSWORD`, and `DOCKER_HOST`; but will ponder whether adding a `DOCKER_AUTHFILE` makes sense).
In parallel, PR also adds `SINGULARITY_AUTHFILE` env var as alternative to passing `--authfile <path>` via command line.
_More complete PR description TBD._
> clear up relationship btw `--authfile` facility & `DOCKER_xyz` env vars

- e2e/actions/oci.go
Pick #2246 
The `TestE2E/PAR/ACTIONS/ociCdi/OCIUser/KmsgDevice/KmsgDevice` test in e2e/actions/oci.go requires cgroups v2. This PR adds appropriate gating so that this test only runs if cgroups v2 is available.
- Fixes #2245
> e2e: gate KmsgDevice OCI-CDI test to cgroups v2 only (release-4.0)

- .github/dependabot.yml
The 3.11 version of SingularityCE is packaged, by ourselves (Sylabs), in EPEL.
Our intention is to minimally maintain it until a 3.11 version of SingularityCE falls out of current supported Fedora releases in approx. 1 year.
Re-enable dependabot to make it easier to track security related dependency updates.
Note that this branch remains under the `vault/` prefix, because:
* We will not be backporting bugfixes, outside of anything required through Fedora/EPEL.
* We will not be tagging or performing any further releases from GitHub.
* We will only be modifying code to deal with security issues, propagating the changes to EPEL packages.
> chore: re-enable dependabot on vault/release-3.11

- CHANGELOG.md
- internal/pkg/build/sources/conveyorPacker_yum.go
On EL systems below version 8, the `_db_backend` rpm macro isn't defined. We must accommodate this, and not error out in a yum bootstrap.
- Fixes #2237 …
> fix: don't fail yum bootstrap when _db_backend rpm macro missing

- CHANGELOG.md
- internal/pkg/build/sources/conveyorPacker_yum.go
Pick #2256 
On EL systems below version 8, the `_db_backend` rpm macro isn't defined. We must accommodate this, and not error out in a yum bootstrap.
- Fixes #2237 …
> fix: don't fail yum bootstrap when _db_backend rpm macro missing (release-4.0)

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/nvliblist.conf
Pick of https://github.com/apptainer/apptainer/pull/1716
Upcoming versions of the NVIDIA driver will include a new component:
https://forums.developer.nvidia.com/t/new-driver-component-libnvidia-gpucomp/267060
Update the list of NVIDIA driver libraries so that it can be included in the runtime environment along with the others. …
> Add libnvidia-gpucomp to the list of NVIDIA driver libraries

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/nvliblist.conf
Pick of #2258
Upcoming versions of the NVIDIA driver will include a new component:
https://forums.developer.nvidia.com/t/new-driver-component-libnvidia-gpucomp/267060
Update the list of NVIDIA driver libraries so that it can be included in the runtime environment along with the others.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible …
> Add libnvidia-gpucomp to the list of NVIDIA driver libraries (release-4.0)

- cmd/internal/cli/actions.go
- internal/pkg/client/ocisif/ocisif.go
- pkg/ocibundle/ocisif/bundle_linux.go
In pkg/ocibundle/ocisif an UnavailableError type was provided to hold an underlying error, effectively performing error wrapping. The error was used:
* In pkg/ocibundle/ocisif to wrap errors from a failed squashfs mount.
* In internal/pkg/client to wrap errors from a failed tar -> squashfs conversion.
The underlying intent was to use this error type to implement fallback in the actions flows from OCI-SIF create/execution to a directory bundle.
Sharing a generic error across the packages isn't ideal, and we should be able to use Go's native error wrapping.
However, we shouldn't change `pkg/ocibundle/ocisif` until a major version bump, as this modifies a public API.
This PR replaces the UnavailableError type in the client case with a specific error, and the use of error wrapping.
It was …
> chore: replace UnavailableError with wrapping for i/p/client/ocisif

- cmd/internal/cli/actions.go
- internal/pkg/client/ocisif/ocisif.go
- pkg/ocibundle/ocisif/bundle_linux.go
In pkg/ocibundle/ocisif an UnavailableError type was provided to hold an underlying error, effectively performing error wrapping. The error was used:
* In pkg/ocibundle/ocisif to wrap errors from a failed squashfs mount.
* In internal/pkg/client to wrap errors from a failed tar -> squashfs conversion.
The underlying intent was to use this error type to implement fallback in the actions flows from OCI-SIF create/execution to a directory bundle.
Sharing a generic error across the packages isn't ideal, and we should be able to use Go's native error wrapping.
However, we shouldn't change `pkg/ocibundle/ocisif` as this modifies a public API.
This PR replaces the UnavailableError type in the client case with a specific error, and the use of error wrapping.
It was also noted that in actions.go …
> chore: replace UnavailableError with wrapping for i/p/client/ocisif (release4.0)

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/nvliblist.conf
Cherry pick https://github.com/apptainer/apptainer/pull/1753
Original commit message:
Adding libnvidia-nvvm.so to nvliblist.conf to accomodate changes in CUDA12 and NVIDIA Drivers > 530
> gpu: Add libnvidia-nvvm.so to nvliblist.conf

- CHANGELOG.md
- CONTRIBUTORS.md
- etc/nvliblist.conf
Cherry pick https://github.com/apptainer/apptainer/pull/1753
Original commit message:
Adding libnvidia-nvvm.so to nvliblist.conf to accomodate changes in CUDA12 and NVIDIA Drivers > 530
> gpu: Add libnvidia-nvvm.so to nvliblist.conf (release-4.0)

- internal/pkg/runtime/launcher/oci/oci_overlay.go
- pkg/ocibundle/tools/overlay_linux.go
When a user specifies a read-only `--overlay` but no writable '--overlay', successful container startup requires that we add an ephemeral writable-tmpfs that runc / crun can write into.
Prior to this PR, '--overlay' overlays were handled and then the ephemeral writable-tmpfs was added in a separate overlayfs mount.
We can avoid 2 stacked overlayfs mounts by adding the ephemeral writable-tmpfs directly within 'WrapWithOverlays'.
This flattening is required so we don't exceed the 2 overlayfs stacking limit with multi-layer OCI-SIF images, which require an overlayfs mount to assemble the initial rootfs. …
> fix: flatten overlay mounts in OCI launcher

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/pull.go
- cmd/internal/cli/singularity.go
- e2e/docker/docker.go
- e2e/internal/e2e/env.go
- e2e/pull/pull.go
- e2e/suite.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- pkg/ocibundle/ocisif/bundle_linux.go
- pkg/ocibundle/tools/oci.go
When an OCI-SIF is created explicitly with `pull`, or implicitly with `run/shell/exec/instance start`, permit the image layers to be kept intact.
The new `--keep-layers` flag for these commands skips squashing images to a single layer when an OCI-SIF is created from an OCI source.
To allow execution of the resulting multi-layer oci-sif files:
* Mount each layer from an oci-sif using squashfuse, onto a `layer/n` directory in the bundle.
* Mount a read-only overlay using all layers onto the `rootfs` directory in the bundle.
* Keep track of the mounts so they can be unmounted on `.Delete()`.
- Fixes #2266
- Fixes #2267
- Added changes to …
> oci: pull and run multi-layer OCI-SIF images

- CONTRIBUTORS.md
- LICENSE_DEPENDENCIES.md
- e2e/actions/oci.go
- go.mod
- go.sum
- internal/pkg/runtime/launcher/oci/cdi_linux.go
- internal/pkg/runtime/launcher/oci/cdi_linux_test.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Updated the CDI (container-orchestrated-devices) dependency to v0.6.2 which includes moving the CDI specs to a separately versioned go submodule. To do this I replaced the `github.com/container-orchestrated-devices/container-device-interface` imports and module entries with `tags.cncf.io/container-device-interface` and bumped version to `v0.6.2`.
> Update container-device-interface to v0.6.2

- .golangci.yml
Increases the timeout for `golangci-lint` from `3m` to `5m` to avoid sporadic CircleCI failures.
> increase golangci-lint timeout to avoid sporadic CircleCI failures

- .golangci.yml
Pick #2320 
Increases the timeout for `golangci-lint` from `3m` to `5m` to avoid sporadic CircleCI failures.
> increase golangci-lint timeout to avoid sporadic CircleCI failures (release-4.0)

- cmd/internal/cli/build.go
- cmd/internal/cli/build_linux.go
- internal/pkg/build/buildkit/client/client.go
In Dockerfile build (using `buildkit`), honor `--keep-layers` command-line flag to create multilayer OCI-SIF image if requested.
> support multilayer Dockerfile build

- cmd/internal/cli/build_linux.go
- cmd/internal/cli/singularity.go
Move the check for OCI-mode if `--keep-layers` is set to the root command `persistentPreRun`. This ensures it applies to `pull` `actions` as well as to `build`.
- Fixes #2327  …
> fix: check for --oci with --keep-layers on all commands

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
When a user requests a bind of all of `/dev`, or a single `/dev/xxx` device, into the container it is because they wish to use a device.
Prior to this PR, OCI-mode was binding `/dev` sources into the container with `nodev` set as a flag. Therefore e.g. `-B /dev/fuse` did not result in a usable FUSE device in the container.
Modify the code so it behaves like native mode. A user request to bind all of `/dev` is treated in the same way as the full `/dev` mount with `--no-compat`. A user request to bind a single `/dev/xxx` entry is performed with logic and flags for dev entries specifically.
This allows FUSE mounts inside OCI-Mode containers to work:
```
$ singularity run --keep-privs --oci -B .:/root -B /dev/fuse --fakeroot  docker://ubuntu
INFO:    Using cached OCI-SIF image
root@mini:~# …
```
> fix: oci: use correct bind options for user /dev[/xxx] binds

- internal/pkg/build/buildkit/client/client.go
- internal/pkg/build/buildkit/daemon/daemon.go
This PR is a grab-bag of fixes for problems uncovered in the course of working on #2331 
Includes:
- exit ephemeral `buildkitd` gracefully if context canceled
- honor BUILDKIT_HOST env var (for setting custom socket address for `buildkitd`) if set
> fixes for Dockerfile-based build

- LICENSE_DEPENDENCIES.md
- e2e/docker/docker.go
- e2e/imgbuild/imgbuild.go
- go.mod
- go.sum
In the course of modifying #2331, the flow of calling verifyImgArch() to verify the success of cross-architecture `buildkitd`-based builds was not properly moved over from buildDockerfile() in e2e/imgbuild/imgbuild.go to testDockerCrossArchBk in e2e/docker/docker.go. This PR fixes that.
> e2e: add back verifyImgArch()

- LICENSE_DEPENDENCIES.md
- go.mod
- go.sum
- internal/pkg/build/remotebuilder/remotebuilder.go
This PR resolves an issue where uploading a build context as part of a remote build would timeout if the build context was large and/or the uplink speed was low.
Network timeout logic has been moved to github.com/sylabs/scs-build-client for build service requests only, while removing the timeout for operations related to the build context.
> Upgrade github.com/sylabs/scs-build-client

- cmd/internal/cli/build_linux.go
- e2e/imgbuild/imgbuild.go
- internal/pkg/build/buildkit/client/client.go
- test/defs/Dockerfile.add.tmpl
Two more fixes to Dockerfile builds (a.k.a. `buildkitd`-based builds):
1. Code in newSolveOpt() in internal/pkg/build/buildkit/client/client.go was not setting the `"context"` key of the `LocalDirs` field of `SolveOpt` correctly, causing `ADD` statements in Dockerfiles to fail. This PR fixes this (setting `LocalDirs["context"]` to the current working dir), and adds e2e code to verify it's working.
2. A leftover piece of debugging code hard-coded in internal/pkg/build/buildkit/client/client.go was disabling all build caching. This PR removes that code, and instead hooks up the toggling of `buildkitd`'s internal caching mechanism to the Singularity `--disable-cache` CLI option.
> build: more fixes to Dockerfiles build

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/mounts_linux_test.go
Cherry-pick #2328
When a user requests a bind of all of `/dev`, or a single `/dev/xxx` device, into the container it is because they wish to use a device.
Prior to this PR, OCI-mode was binding `/dev` sources into the container with `nodev` set as a flag. Therefore e.g. `-B /dev/fuse` did not result in a usable FUSE device in the container.
Modify the code so it behaves like native mode. A user request to bind all of `/dev` is treated in the same way as the full `/dev` mount with `--no-compat`. A user request to bind a single `/dev/xxx` entry is performed with logic and flags for dev entries specifically.
- Fixes #2326
- Added changes …
> fix: oci: use correct bind options for user /dev[/xxx] binds (release-4.0)

- internal/pkg/build/sources/conveyorPacker_arch.go
- internal/pkg/build/sources/conveyorPacker_busybox.go
- internal/pkg/build/sources/conveyorPacker_yum.go
- internal/pkg/build/sources/conveyorPacker_zypper.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/client/oras/oras.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_runc_linux.go
- pkg/ocibundle/native/bundle_linux.go
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.
In the process of satisfying the linters in #2026 a number of 'FIXME' items were added. The majority of these deal with contexts that are not being used.
internal/pkg/build/sources/conveyorPacker_arch.go
internal/pkg/build/sources/conveyorPacker_yum.go
internal/pkg/build/sources/conveyorPacker_zypper.go
internal/pkg/build/sources/conveyorPacker_busybox.go
internal/pkg/runtime/launcher/oci/oci_runc_linux.go
internal/pkg/client/ocisif/ocisif.go
internal/pkg/client/oras/oras.go
pkg/ocibundle/native/bundle_linux.go
> chore: address context-related FIXMEs

- e2e/internal/e2e/image.go
As part of #2225, a function `EnsureORASPrivImage()` was added to e2e/internal/e2e/image.go which was never used, and which would not work as intended if used.
The functionality in question - interacting with an image in a private repository via the oras protocol - is already covered by other e2e tests; see, in particular: [here](https://github.com/sylabs/singularity/blob/f061a92402edfee242308b0de66614584f73c795/e2e/registry/registry.go#L389), and [here](https://github.com/sylabs/singularity/blob/f061a92402edfee242308b0de66614584f73c795/e2e/actions/actions.go#L2755).
This PR removes the `EnsureORASPrivImage()` function.
> remove EnsureORASPrivImage()

- go.mod
- internal/pkg/cache/cache.go
- internal/pkg/cache/cache_test.go
- internal/pkg/client/oci/nativesif.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ociimage/digest.go
- internal/pkg/ociimage/digest_test.go
- internal/pkg/ociimage/fetch.go
- internal/pkg/ociimage/transport.go
Re-implement the OCI image digest flows using ggcr instead of containers/image/v5.
When obtaining the ImageDigest for an image in a remote registry we need to try to use a `HEAD` request that doesn't count against Docker Hub API limits.
Unfortunately, the `Docker-Content-Digest` returned by `HEAD` is for the image index when a repository is multi-arch. We have to locally cache the manifest or image index so that we can always resolve the digest we get back from `HEAD` requests to a true image digest.
- Fixes #2383 
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to …
> refactor: use ggcr for ociimage.ImageDigest

- .golangci.yml
- .vscode/settings.json
- mlocal/frags/go_common_opts.mk
Now we don't use containers/image (except for types for backward compatibility through to 5.0), remove the build tags related to containers/image and containers/storage that are no longer required. …
> chore: drop containers/image related build tags

- e2e/internal/e2e/image.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/client/oras/oras.go
- internal/pkg/client/oras/pull.go
- internal/pkg/client/progress/progress.go
- internal/pkg/client/progress/progress_roundtripper.go
- internal/pkg/ociimage/digest.go
- internal/pkg/ociimage/fetch.go
- internal/pkg/ociimage/sourcesink.go
Add back progress bars when remote OCI images are fetch via the new ggcr code.
Because ggcr doesn't have its own progress functionality for reads from a remote, we implement bars on GET requests through a RoundTripper.
The existing RoundTripper code that was implemented for ORAS fetch only has been revised to accommodate multiple bars for multiple GETs, and ensure a more graceful exit.
- Fixes #2385 …
> Re-implement bars when fetching remote OCI images via ggcr

- cmd/internal/cli/oci_linux.go
- e2e/config/config.go
- internal/pkg/build/apps/apps.go
- internal/pkg/runtime/launcher/oci/oci_attach_linux.go
- internal/pkg/util/crypt/crypt_dev_test.go
**e2e: enable configGlobal SystemdCgroupsYes**
This test was disabled as it wasn't possible to run it within a PID namespace. Our e2e tests have not used a PIDn amespace for some time now, so we can enable it again.
**chore: drop FIXME from copyWithflr**
There isn't an easy way to replace `cp -fLr` with go code and be 100% certain that it has the exact same behaviour across all possible source / dest we could encounter when building a SCIF container.
Drop the FIXME. We'll keep using `cp -fLr`.
**crypt: enable emptyFile test**
Not clear exactly why this was disabled / what 'too much variability in test results with CI' means.
Possibly due to an issue on older distros? It is passing for me.
**oci: Drop ctx / FIXME from oci.Attach func**
Remove the FIXME note and the ctx parameter from …
> Address further FIXMEs

- CHANGELOG.md
- e2e/instance/instance.go
- e2e/instance/instance_utils.go
- e2e/testdata/Singularity
- internal/pkg/util/fs/files/action_scripts.go
Add an e2e test for `instance start --app`. Use the same echo server pattern that's implemented for testing `instance start`, but make `%appstart foo` a string reversing echo server, so we can tell that we started the right thing.
This uncovered issue #2410 - so we also have a fix to run the correct `%appscript` instead of the generic `%startscript` for `instance start --app`.
- Fixes #1944
- Fixes #2410  …
> fix: Execute correct %appscript and add test for instance start --app

- debian/singularity-ce.install
- dist/rpm/singularity-ce.spec.in
Fix RPM and Deb by adding singularity-buildkitd binary to installed files. …
> fix: add singularity-buildkitd to packaging

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/actions.go
- cmd/internal/cli/singularity.go
- e2e/actions/actions.go
- e2e/config/config.go
- internal/app/starter/host.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/options.go
- pkg/util/singularityconf/config.go
Deprecate the explicit `--sif-fuse` flag and `sif fuse` directive for `singularity.conf`. These were previously used to enable experimental FUSE mount of SIF/SquashFS containers.
Modify image handling so that we now try squashfuse mounts automatically, with fall back to temporary sandbox extraction, when:
* squashfs kernel mounts have been disabled in `singularity.conf` -or-
* we are running in a non-setuid / user namespace flow.
Add a `--tmp-sandbox` flag to allow forcing extraction to a temporary sandbox when a kernel mount or FUSE mount would otherwise be used / attempted.
This change exposed an issue via the e2e tests - where there is a failure after the starter is called, but before the container is entered successfully, the host cleanup may not be called. To address this, added the …
> fuse: automatically use squashfuse for images, deprecate --sif-fuse

- .circleci/config.yml
- CHANGELOG.md
- e2e/config/config.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
If the container image is a bare extfs image, and extfs kernel mounts have been disabled, use fuse2fs to mount the image.
- Fixes #2217  …
> fuse: Add fuse2fs mount for  bare extfs images

- INSTALL.md
- examples/lima/singularity-ce.yml
squashfs-tools-ng is now available in EPEL. We should direct people to that, and not the COPR - which will not be maintained in future. …
> docs: install squashfs-tools-ng from EPEL, not COPR

- e2e/build/build.go
- e2e/docker/docker.go
- e2e/internal/e2e/profile.go
We require FUSE in userns for OCI-mode and our singularity-buildkitd (which uses a fuse-overlayfs snapshotter on kernel <5.11). FUSE in userns is supported on kernel >=4.18.
Add the kernel requirement to the OCI profile.
Modify the buildkit / Dockerfile build tests to use the OCI profile instead of specifying the `--oci` flag directly.
- Fixes #2494 
- Fixes #2493  …
> e2e: gate OCI-mode / buildkitd on kernel >=4.18

- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/config/config.go
- e2e/verify/verify.go
**e2e: change OCSPResponder gating for SLES12**
As well as EL7, SLES12 doesn't support some of the algorithms in the OCSP chain that is tested.
Adjust the kernel requirement, so that it exclude SLES12 as well as EL7.
Using a kernel requirement is an inexact / indirect method of checking for algorithm support, but is simple and works across our target supported distros.
**e2e: gate --fusemount tests with userns on kernel 4.18**
Avoids failures on SLES12 where there is no kernel support for FUSE mounts in conjunction with a userns.
**e2e: fix: use bin.FindBin for path to mksquashfs**
In recent work the require.Command test helper was modified to use `bin.Findbin` ahead of `exec.LookPath`.
Since `mksquashfs` has handling via `singularity.conf` in `bin.FindBin` we need to use this to invoke …
> e2e: EL7 / SLES12 assorted fixes

- CHANGELOG.md
- internal/pkg/util/fs/overlay/overlay_set_linux.go
When running as host root, we can use kernel overlayfs instead of fuse-overlayfs without kernel unprivileged overlay support.
This commit fixes the regression from 3.x -> 4.0 on systems without unprivileged kernel overlay support, which is caught by existing OCI e2e tests on these systems.
- Fixes #2512
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make …
> fix: use kernel overlayfs as root, regardless of unpriv support

- CHANGELOG.md
- internal/pkg/util/fs/overlay/overlay_set_linux.go
Pick #2513 
When running as host root, we can use kernel overlayfs instead of fuse-overlayfs without kernel unprivileged overlay support.
This commit fixes the regression from 3.x -> 4.0 on systems without unprivileged kernel overlay support, which is caught by existing OCI e2e tests on these systems.
- Fixes #2512
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, …
> fix: use kernel overlayfs as root, regardless of unpriv support (release-4.0)

- CHANGELOG.md
- e2e/instance/instance.go
- e2e/instance/instance_utils.go
- e2e/testdata/Singularity
- internal/pkg/util/fs/files/action_scripts.go
Pick #2408
Add an e2e test for `instance start --app`. Use the same echo server pattern that's implemented for testing `instance start`, but make `%appstart foo` a string reversing echo server, so we can tell that we started the right thing.
This uncovered issue #2410 - so we also have a fix to run the correct `%appscript` instead of the generic `%startscript` for `instance start --app`.
- Fixes #1944
- Fixes #2410 
- …
> fix: Execute correct %appscript and add test for instance start --app  (release-4.0)

- CHANGELOG.md
- LICENSE.md
- e2e/cgroups/cgroups.go
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/cgroups/util.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Rework the location of checks for cgroup management support, and add fall-back logic, so that when all of the following apply:
* A system is using cgroups v2
* Singularity is configured to use systemd for cgroups management
* The system configuration / environment doesn't set usable XDG_RUNTIME_DIR / DBUS_SESSION_BUS_ADDRESS env vars
* The user has not explicitly requested resource limits (e.g --cpus)
... It is still possible to:
* Start an instance as non-root (without the cgroup needed for instance stats)
* run / shell / exec a container as non-root in OCI-Mode
Fixes #2529
Fixes #2568
- Fixes #2529 
- Fixes #2568 
- Added changes to …
> cgroups: rework checks for cgroup support

- CHANGELOG.md
- LICENSE.md
- e2e/cgroups/cgroups.go
- internal/pkg/cgroups/manager_linux.go
- internal/pkg/cgroups/util.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #2569 
Rework the location of checks for cgroup management support, and add fall-back logic, so that when all of the following apply:
* A system is using cgroups v2
* Singularity is configured to use systemd for cgroups management
* The system configuration / environment doesn't set usable XDG_RUNTIME_DIR / DBUS_SESSION_BUS_ADDRESS env vars
* The user has not explicitly requested resource limits (e.g --cpus)
... It is still possible to:
* Start an instance as non-root (without the cgroup needed for instance stats)
* run / shell / exec a container as non-root in OCI-Mode
Fixes #2529
Fixes #2568 …
> cgroups: rework checks for cgroup support (release-4.1)

- internal/app/starter/host.go
- internal/app/starter/stage_linux.go
- internal/pkg/runtime/engine/engine_linux.go
- internal/pkg/runtime/engine/singularity/host_linux.go
Pick #2573
If container creation fails early, while preparing configuration in `StageOne`, our `CLEANUP_HOST` process forked from starter may not have started yet, and won't be trapping `SIGTERM`... in which case any required host cleanup of FUSE mounts etc. will not happen.
Call the host cleanup directly from `StageOne`, on error, to avoid this issue.
While we are in this code...
* Change `SIGHUP` -> `SIGUSR1` for our own signal in the CleanupHost code, so it's obviously our own signal and not from the system.
* Add a return to the go routine receiving `SIGUSR1` to avoid a spurious log message.
* Clarify some comments that discuss the flow of execution
Fixes #2520
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR …
> engine: cleanup host directly on StageOne failure (release-4.1)

- internal/app/starter/host.go
- internal/app/starter/stage_linux.go
- internal/pkg/runtime/engine/engine_linux.go
- internal/pkg/runtime/engine/singularity/host_linux.go
If container creation fails early, while preparing configuration in `StageOne`, our `CLEANUP_HOST` process forked from starter may not have started yet, and won't be trapping `SIGTERM`... in which case any required host cleanup of FUSE mounts etc. will not happen.
Call the host cleanup directly from `StageOne`, on error, to avoid this issue.
While we are in this code...
* Change `SIGHUP` -> `SIGUSR1` for our own signal in the CleanupHost code, so it's obviously our own signal and not from the system.
* Add a return to the go routine receiving `SIGUSR1` to avoid a spurious log message.
* Clarify some comments that discuss the flow of execution
- Fixes #2520 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to …
> engine: cleanup host directly on StageOne failure

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/spec_linux.go
See: https://github.com/containers/crun/issues/1402
When there is no `Linux.Resources` in `config.json`, `crun` v1.11 and above segfault.
To work around this, ensure that `Linux.Resources` is present but empty when no resource limits have been requested.
- Fixes #2596 …
> fix: workaround for crun 1.11+ segv with no Linux.Resources

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/spec_linux.go
Pick https://github.com/sylabs/singularity/pull/2597
See: https://github.com/containers/crun/issues/1402
When there is no `Linux.Resources` in `config.json`, `crun` v1.11 and above segfault.
To work around this, ensure that `Linux.Resources` is present but empty when no resource limits have been requested.
- Fixes #2596 
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make …
> fix: workaround for crun 1.11+ segv with no Linux.Resources (release-4.1)

- .github/dependabot.yml
> chore: disable 3.11 dependabot

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
Pick #2669
The image-spec conversion document specifies which annotations MUST be set when converting an image-spec into a runtime-spec. Adhere to these.
- Fixes #2664  …
> fix: oci: set MUST image-spec -> runtime spec annotations (4.1)

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
The image-spec conversion document specifies which annotations MUST be set when converting an image-spec into a runtime-spec. Adhere to these.
- Fixes #2664 …
> fix: oci: set MUST image-spec -> runtime spec annotations

- CHANGELOG.md
- e2e/docker/docker.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #2661 
In OCI mode, as an unprivileged user, we have an outer UID/GID mapping from the host UID/GID to 0:0 and an inner UID/GID mapping back to the host UID.
The code was erroneously using the targetUID/GID for the container process rather than the host UID/GID for the inner mapping. This meant that when a container specifying an Dockerfile `USER` was run the mapping and file owneship in the container was incorrect.
Fix the mapping and add e2e-tests that verify correct file ownership for a container with a `USER`.
- Fixes #2623
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if …
> fix: oci: always use rootless uid for inner uid map (release-4.1)

- CHANGELOG.md
- e2e/docker/docker.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
In OCI mode, as an unprivileged user, we have an outer UID/GID mapping from the host UID/GID to 0:0 and an inner UID/GID mapping back to the host UID/GID.
The code was erroneously using the targetUID/GID for the container process rather than the host UID/GID for the inner mapping. This meant that when a container specifying an Dockerfile `USER` was run the mapping and file owneship in the container was incorrect.
Fix the mapping and add e2e-tests that verify correct file ownership for a container with a `USER`.
- Fixes #2623 …
> fix: oci: always use rootless uid for inner uid map

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Provide warning / info message for OCI image-spec features (volumes, exposed ports) that are not supported by singularity.
- Fixes #2665 …
> oci: warning / info for unsupported image-spec features

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/launcher_linux.go
Pick #2673
Provide warning / info message for OCI image-spec features (volumes, exposed ports) that are not supported by singularity.
- Fixes #2665 …
> oci: warning / info for unsupported image-spec features (4.1)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
Pick #2691
Restore the long standing previous behaviour of singularity's native runtime, where `--writable` can be used when running a SIF / SquashFS container image in userns (`-u`) mode.
In this situation:
- The image is extracted to a temporary sandbox.
- The resulting container run from the sandbox is writable.
This behaviour has always been a bit confusing / inconsistent, because no writes happen to the actual image that the user specified. Only the temporary sandbox, which is deleted when the container exits, is written to. The PR adds awarning to this effect.
We may want to revisit this behaviour at a future major version, because it is inconsistent with other flows. However, this PR is needed because not honoring `--writable` in this manner was a behaviour change regression within …
> fix: honor --writable for userns temp sandbox (4.1)

- CHANGELOG.md
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
Restore the long standing previous behaviour of singularity's native runtime, where `--writable` can be used when running a SIF / SquashFS container image in userns (`-u`) mode.
In this situation:
- The image is extracted to a temporary sandbox.
- The resulting container run from the sandbox is writable.
This behaviour has always been a bit confusing / inconsistent, because no writes happen to the actual image that the user specified. Only the temporary sandbox, which is deleted when the container exits, is written to. The PR adds a warning to this effect.
We may want to revisit this behaviour at a future major version, because it is inconsistent with other flows. However, this PR is needed because not honoring `--writable` in this manner was a behaviour change regression within a major …
> fix: honor --writable for userns temp sandbox (regression)

- CHANGELOG.md
- internal/pkg/ociimage/unpack.go
The ggcr module has a bug in its `mutate.Extract` function, due to optimisations that do not correctly track hard links that are manipulated in specific ways across layers:
https://github.com/google/go-containerregistry/issues/977
Prior to this PR, we were using `mutate.Extract` to flatten an image so that we were only extracting a single tar into a rootfs with umoci. This meant that the bug above could cause umoci to fail, as the flattened tar is invalid in certain circumstances.
Fix the issue by avoiding `mutate.Extract`. Instead extract each layer, in order, using umoci.
- Fixes #2684 (native mode) …
> fix: don't flatten layers with ggcr before extracting

- CHANGELOG.md
- internal/pkg/ociimage/unpack.go
Pick #2685
The ggcr module has a bug in its `mutate.Extract` function, due to optimisations that do not correctly track hard links that are manipulated in specific ways across layers:
https://github.com/google/go-containerregistry/issues/977
Prior to this PR, we were using `mutate.Extract` to flatten an image so that we were only extracting a single tar into a rootfs with umoci. This meant that the bug above could cause umoci to fail, as the flattened tar is invalid in certain circumstances.
Fix the issue by avoiding `mutate.Extract`. Instead extract each layer, in order, using umoci.
- Fixes #2684 (native mode) …
> fix: don't flatten layers with ggcr before extracting (4.1)

- internal/pkg/util/crypt/crypt_dev_test.go
Pick #2696
On RHEL7 & SLES12 the cryptsetup call succeeds, which the test does not expect. On kernel >=4.18 the test will pass.
- Fixes #2695 …
> e2e: gate TestEncrypt/empty_file on kernel 4.18 (4.1)

- internal/pkg/util/crypt/crypt_dev_test.go
On RHEL7 & SLES12 the cryptsetup call succeeds, which the test does not expect. On kernel >=4.18 the test will pass.
- Fixes #2695 …
> e2e: gate TestEncrypt/empty_file on kernel 4.18

- CHANGELOG.md
- internal/pkg/build/sources/packer_sif.go
- internal/pkg/build/sources/packer_squashfs.go
- internal/pkg/image/unpacker/squashfs.go
- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_test.go
- internal/pkg/ociimage/unpack.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- pkg/image/image_test.go
Note - there are no e2e tests for the nested containers / nested namespaces situations that are fixed by the commits in this PR. However, our e2e tests do confirm the changes don't cause regressions in non-nested cases.
The e2e framework doesn't offer a great way of executing singularity nested, and I've opened an issue (#2700) to address this to verify functionality more generally than a messy one-off for this PR would handle.
**fix: use rootless umoci inside user namespace**
If we are running from within a user namespace, then use rootless OCI layer extrraction with umoci.
This permits the extraction to complete when singularity is run under `unshare -r`.
**fix: honor --userns in unsquashfs wrapping**
If singularity is executed with `--userns/-u` then it should also use a user namespace …
> fix: Address layer / image extraction issues in user namespaces

- CHANGELOG.md
- internal/pkg/build/sources/packer_sif.go
- internal/pkg/build/sources/packer_squashfs.go
- internal/pkg/image/unpacker/squashfs.go
- internal/pkg/image/unpacker/squashfs_singularity.go
- internal/pkg/image/unpacker/squashfs_test.go
- internal/pkg/ociimage/unpack.go
- internal/pkg/runtime/launcher/native/launcher_linux.go
- pkg/image/image_test.go
Pick #2699 
Note - there are no e2e tests for the nested containers / nested namespaces situations that are fixed by the commits in this PR. However, our e2e tests do confirm the changes don't cause regressions in non-nested cases.
The e2e framework doesn't offer a great way of executing singularity nested, and I've opened an issue (#2700) to address this to verify functionality more generally than a messy one-off for this PR would handle.
**fix: use rootless umoci inside user namespace**
If we are running from within a user namespace, then use rootless OCI layer extrraction with umoci.
This permits the extraction to complete when singularity is run under `unshare -r`.
**fix: honor --userns in unsquashfs wrapping**
If singularity is executed with `--userns/-u` then it should also use a …
> fix: Address layer / image extraction issues in user namespaces (4.1)

- e2e/internal/e2e/profile.go
- internal/pkg/test/tool/require/require.go
- internal/pkg/util/bin/bin.go
OCI-mode profiles require `tar2sqfs` or `sqfstar` to create an OCI-SIF.
OCI-mode can use either `crun` or `runc`.
- Fixes #2472 …
> e2e: fix OCI profile requirements

- e2e/internal/e2e/profile.go
- internal/pkg/test/tool/require/require.go
- internal/pkg/util/bin/bin.go
OCI-mode profiles require `tar2sqfs` or `sqfstar` to create an OCI-SIF.
OCI-mode can use either `crun` or `runc`.
- Fixes #2472 …
>  e2e: fix OCI profile requirements (4.1)

- .circleci/config.yml
- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
OCI images almost always set `PATH` in their config. However, some don't. Most recently, `docker://busybox:latest` changed and the new version:
* Doesn't set `PATH` in its config.
* Has a CMD of `sh` which has to be found on a `PATH`.
Singularity's OCI mode was failing to find `sh`. Other runtimes set a default `PATH` in the container, so running `busybox:latest` still works.
This PR ensures we set a default `PATH` in the container where the image does not provide one.
In addition - the new docker://busybox:latest image layers have some entries that trigger a bug in `sqfstar`, related to symlink paths being stripped and rejected in error. This bug is present in  >=4.5 <=4.6. Because Ubuntu 22.04 is stuck on 4.5.x, add `squashfs-tools-ng` to the CI environment to use `tar2sqfs`. This is …
> fix: oci: set default PATH if image does not

- .circleci/config.yml
- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/process_linux.go
- internal/pkg/runtime/launcher/oci/process_linux_test.go
Pick 2722
OCI images almost always set `PATH` in their config. However, some don't. Most recently, `docker://busybox:latest` changed and the new version:
* Doesn't set `PATH` in its config.
* Has a CMD of `sh` which has to be found on a `PATH`.
Singularity's OCI mode was failing to find `sh`. Other runtimes set a default `PATH` in the container, so running `busybox:latest` still works.
This PR ensures we set a default `PATH` in the container where the image does not provide one.
In addition - the new docker://busybox:latest image layers have some entries that trigger a bug in `sqfstar`, related to symlink paths being stripped and rejected in error. This bug is present in  >=4.5 <=4.6. Because Ubuntu 22.04 is stuck on 4.5.x, add `squashfs-tools-ng` to the CI environment to use `tar2sqfs`. …
> fix: oci: set default PATH if image does not (4.1)

- e2e/internal/e2e/image.go
- e2e/pull/pull.go
- e2e/registry/registry.go
In some e2e tests we still had code that was specifying `--oci` explicitly, with `e2e.UserProfile`. This bypasses the requirements checking that is in place for `e2e.OCIUserProfile`.
Use OCIUserProfile instead of `--oci`.
- Fixes #2723
- Based this PR against the …
> e2e: use OCI profile, not `--oci`

- mconfig
Bump `mconfig` Go version check to 1.21, to correspond with changes in #2767.
> fix: bump mconfig Go version check to 1.21

- go.mod
We should use a full version `x.y.z` in the `go.mod` `go` statement from 1.21 and onward.
See: https://github.com/golang/go/issues/62278 …
> fix: use 1.21.0 full version in go statement

- CHANGELOG.md
- e2e/internal/e2e/dockerhub_auth.go
- internal/pkg/remote/credential/ociauth/ociauth.go
For historical reasons, the auth file key for docker hub (which can be accessed as index.docker.io or docker.io) is stored by docker as:
https://index.docker.io/v1/
We were successfully doing this for logins to `index.docker.io`, but `docker.io` can also be used as an alias... and was not being mutated to the above string.
When a ggcr Registry struct is created, against which operations will be performed, the NewRegistry func modifyies a `docker.io` address to `index.docker.io`. This means we need to have a `docker.io` credential stored against the correct mutated `https://index.docker.io/v1/` key in the auth file for it to be effective as intended.
(ref.. https://github.com/google/go-containerregistry/blob/8b3c3036d612bcb3c1147fe11c2d1818dc432329/pkg/name/registry.go#L127)
We now have …
> fix: store docker.io credential like index.docker.io

- CHANGELOG.md
- e2e/internal/e2e/dockerhub_auth.go
- internal/pkg/remote/credential/ociauth/ociauth.go
For historical reasons, the auth file key for docker hub (which can be accessed as index.docker.io or docker.io) is stored by docker as:
https://index.docker.io/v1/
We were successfully doing this for logins to `index.docker.io`, but `docker.io` can also be used as an alias... and was not being mutated to the above string.
When a ggcr Registry struct is created, against which operations will be performed, the NewRegistry func modifyies a `docker.io` address to `index.docker.io`. This means we need to have a `docker.io` credential stored against the correct mutated `https://index.docker.io/v1/` key in the auth file for it to be effective as intended.
(ref.. https://github.com/google/go-containerregistry/blob/8b3c3036d612bcb3c1147fe11c2d1818dc432329/pkg/name/registry.go#L127)
We now have …
> fix: store docker.io credential like index.docker.io (release-4.1)

- CHANGELOG.md
- docs/remote.go
Update online documentation to reflect the fact that '✓' is used instead of 'YES' in 'remote list' output since https://github.com/sylabs/singularity/pull/1919.
> docs: improve 'remote list' documentation

- CHANGELOG.md
- docs/remote.go
Update online documentation to reflect the fact that '✓' is used instead of 'YES' in 'remote list' output since https://github.com/sylabs/singularity/pull/1919.
> docs: improve 'remote list' documentation (release-4.1)

- .circleci/config.yml
- INSTALL.md
Bump recommended go version to 1.21.9.
> chore: use latest go1.21 patch release

- .circleci/config.yml
- .gitignore
- INSTALL.md
- debian/apparmor-placeholder
- debian/apparmor-userns
- debian/control
- debian/rules
- debian/singularity-ce.install
- mlocal/frags/build_squashfuse.mk
* Document manual apparmor profile install in INSTALL.md for source builds
* Add Ubuntu 24.04 to the CI matrix.
* Add an apparmor profile for Ubuntu >=24 that enables unprivileged user namespace creation in the non-setuid starter.
* Add a placeholder apparmor profile for Ubuntu <24 that just marks the non-setuid starter as unconfined. Avoids version-dependent use of dh_apparmor.
* Strip -D_FORTIFY_SOURCE=3 from CPPFLAGS in squashfuse build, if present (Ubuntu 24.04). This prevents a clash with the -D_FORTIFY_SOURCE=2 that we set explicitly. Squashfuse build already needs some hardening disabled. We should revisit in depth in future.
Closes #2275
> deb: packaging for Ubuntu 24.04

- INSTALL.md
- debian/apparmor-placeholder
- debian/apparmor-userns
The starter-setuid process doesn't run all of its code privileged. In the fakeroot hybrid workflow we need to allow it to create an unprivileged user namespace.
Modify the apparmor profile to permit this.
- Fixes #2861
- Based this PR against the appropriate …
> fix: include starter-setuid in apparmor profile

- e2e/verify/verify.go
> Remove kernel version requirement for OCSP test

- LICENSE_DEPENDENCIES.md
- go.mod
- go.sum
- internal/pkg/runtime/engine/config/oci/config.go
- internal/pkg/runtime/launcher/oci/oci_attach_linux.go
- internal/pkg/security/seccomp/seccomp_supported.go
deps: drop containers/common/config
deps: switch to docker/docker/profile/seccomp
In order to drop container/common as a direct dependency, switch seccomp profile loading & the default profile to use docker/docker code. Note that the containers/common code has origins in the docker/docker code... and we happen to use functions that are still common.
Also hard code a constant we were importing related to a conmon detach key combination.
We are committed to docker/docker as a dependency given we are now using buildkit etc. so we will always need to deal with breaking changes and security issues in that ecosystem.
Dropping containers/common avoids us being tied to breaking changes / security issues in the podman dependency ecosystem as well.
We still import some types from containers/image …
> deps: Drop containers/common

- e2e/docker/docker.go
- e2e/docker/regressions.go
- e2e/registry/registry.go
- e2e/suite.go
Using alpine:latest can cause issues when things change in a new alpine release, e.g. #2944 due to a change in the root shell path in /etc/passwd.
Our main test images, obtainer in suite.go, and used throughout the e2e suite should be stable. We have specific tests for `alpine:latest` in e2e/Docker that ensure the latest alpine version generally works.
- Fixes #2944  …
> e2e: use alpine:3.18 instead of latest for main e2e images

- CHANGELOG.md
- LICENSE_THIRD_PARTY.md
- e2e/build/build.go
- e2e/build/regressions.go
- e2e/testdata/regressions/issue_2607.def
- go.mod
- internal/pkg/build/files/copy.go
- pkg/util/archive/archive.go
- pkg/util/archive/copy.go
- pkg/util/archive/copy_test.go
In a build stage, a valid relative symlink can be created that points to a location in the rootfs that is above the location of the symlink. E.g.:
/usr/mydir/mysubdir/true -> ../../../bin/true
This symlink is valid in the rootfs. It resolves to `/bin/true`.
If we attempt to copy `/usr/mydir` into a new build stage, then prior to this PR the symlink would cause the copy to fail.
We have been using `CopyFromTar` to copy from src `<stage1>/usr/mydir`, to `<stage2>/usr/mydir`. The `CopyFromTar` routines enforce that the target of a hard link or symlink must be under dst, or a fatal error is raised to avoid a breakout attack.
When copying between stages our boundary is not dst, but the top level of the destination stage's rootfs. We must allow links to be created that are above dst, but within …
> fix: copy relative symlinks correctly between stages

- e2e/data/data.go
- e2e/suite.go
- internal/pkg/ocisif/datacontainer.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/util/fs/fuse/fuse_mount_linux.go
Allow OCI-SIF data container created with `singularity data package` to be mounted using the `--bind` and `--mount` flags.
An `image-source=/` option is required on the bind to mount from the root of the data container layer. A shortcut `--data` flag that does not require this will be added in future.
- Fixes #2873
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, …
> oci: --bind / --mount for data containers

- .circleci/config.yml
- internal/pkg/build/buildkit/client/client.go
Bump Go version to latest, CircleCI Ubuntu 22.04 machine image, golangci-lint version. …
> chore: ci: bump Go, CircleCI machine, linter

- pkg/image/sif_test.go
When a host is configured such that there is s390x binfmt_misc emulation support, then the PrimaryPartitionOtherArchSIF test will succeed, rather than fail.
- Fixes #2986 …
> fix: accommodate binfmt_misc in pkg/image tests

- internal/pkg/build/sources/conveyorPacker_oci_test.go
We must provide platform when retrieving an OCI image.
- Fixes #2987 …
> fix: set missing platform in TestOCIConveyor/Packer

- internal/pkg/build/assemblers/sif_test.go
We must provide platform when retrieving an OCI image.
- Fixes #2989 …
> fix: set missing platform in TestSIFAssembler

- pkg/ocibundle/ocisif/bundle_linux_test.go
Fix a potential panic where part of a test fails.
If the bundle cannot be created that's a fatal error. We cannot go on to validate it, as the validator will fail with a panic.
- Fixes #2985 …
> fix: panic in ocibundle TestFromImageRef

- CHANGELOG.md
- debian/apparmor-placeholder
- debian/apparmor-userns
- debian/rules
Our placeholder policy for AppArmor must use ABI 3, as ABI 4 isn't available on Ubuntu <23.10.
We can install the actual userns policy with ABI 4 on 23.10 and above.
- Fixes #2970 …
> fix: use Apparmor ABI 3 on Ubuntu <23.10

- CHANGELOG.md
- debian/apparmor-placeholder
- debian/apparmor-userns
- debian/rules
Our placeholder policy for AppArmor must use ABI 3, as ABI 4 isn't available on Ubuntu <23.10.
We can install the actual userns policy with ABI 4 on 23.10 and above.
- Fixes #2970 …
> fix: use Apparmor ABI 3 on Ubuntu <23.10 (release-4.1)

- CHANGELOG.md
- cmd/internal/cli/push.go
- e2e/push/push.go
- internal/pkg/client/library/push.go
- internal/pkg/client/oci/push.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ocisif/imagewriter.go
Add a `--layer-format` flag for the `singularity push` command. This applies only to pushes of OCI-SIF images (including data containers).
When `--layer-format` is not set, or is set to `squashfs` then the OCI-SIF image is pushed with layers in squashfs format. These can only be used by Singularity.
When `--layer-format` is set to `tar` then the OCI-SIF image is pushed with its layers converted on-the-fly to TAR format. The resulting pushed image can be used by other OCI runtimes.
- Fixes #2848 …
> feat: push --layer-format tar

- CHANGELOG.md
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ociimage/digest.go
- internal/pkg/ociimage/fetch.go
- pkg/ocibundle/native/bundle_linux.go
cherry-pick #2935
When an OCI image is already available as an OCI layout directory, or a docker tarball, ggcr can read it directly. We can avoid additionally fetching it into the cache or a temporary OCI layout directory. This saves time, disk space, and I/O.
- Fixes #2934 …
> fix: do not copy local OCI images to layout (release-4.1)

- CHANGELOG.md
- internal/pkg/build/buildkit/client/client.go
cherry pick #2936
With #2935 in place we can now translate a Docker archive tarball into an OCI-SIF without creating a redundant copy of the image as a temporary OCI layout.
We've previously been processing the buildkit tarball as an oci-archive, which still requires extraction to a temporary layout, as ggcr's tarball package doesn't accept an archived layout without a manifest.json.
Because the buildkit output tarball includes the Docker specific manifest.json, in addition to the standard OCI layout files, it can be treated as a docker-archive - now avoiding the need for the temporary layout.
Significantly reduces disk space needed by `build --oci`, and the associated I/O.
Fixes #2308
> fix: avoid unneccesary temporary layout during build --oci (release-4.1)

- CHANGELOG.md
- LICENSE_THIRD_PARTY.md
- e2e/build/build.go
- e2e/build/regressions.go
- e2e/testdata/regressions/issue_2607.def
- go.mod
- internal/pkg/build/files/copy.go
- pkg/util/archive/archive.go
- pkg/util/archive/copy.go
- pkg/util/archive/copy_test.go
cherry pick #2924
In a build stage, a valid relative symlink can be created that points to a location in the rootfs that is above the location of the symlink. E.g.:
/usr/mydir/mysubdir/true -> ../../../bin/true
This symlink is valid in the rootfs. It resolves to `/bin/true`.
If we attempt to copy `/usr/mydir` into a new build stage, then prior to this PR the symlink would cause the copy to fail.
We have been using `CopyFromTar` to copy from src `<stage1>/usr/mydir`, to `<stage2>/usr/mydir`. The `CopyFromTar` routines enforce that the target of a hard link or symlink must be under dst, or a fatal error is raised to avoid a breakout attack.
When copying between stages our boundary is not dst, but the top level of the destination stage's rootfs. We must allow links to be created that are …
> fix: copy relative symlinks correctly between stages (release-4.1)

- cmd/internal/cli/overlay_create.go
- internal/app/singularity/overlay_create.go
Refactor the OverlayCreate routines ahead of work to add overlay creation for OCI-SIF.
* Don't duplicate utility functions from the image package.
* Split up command checks / image checks / ext overlay file create / addition to SIF into separate functions.
Should allow OCI-SIF overlay creation to be added in a neater commit. …
> chore: Refactor OverlayCreate

- e2e/build/build.go
- e2e/build/regressions.go
- e2e/testdata/regressions/issue_5250.def
CentOS 7 has gone end of life. Various infrastructure like the mirrorlist is no longer available:
https://lists.centos.org/hyperkitty/list/devel@lists.centos.org/thread/EGOA27SGN7W7ASFFFBNUZJ5BXSFT4NKX/
Drop the regression test for 5250, which depends on CentOS7 and is failing due to the retirement of the mirrorlist.
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make …
> e2e: drop test depending on CentOS 7

- CHANGELOG.md
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- pkg/ocibundle/native/bundle_linux.go
- pkg/ocibundle/native/bundle_linux_test.go
- pkg/ocibundle/tools/oci.go
1 - When FUSE mount fails, ensure fallback to a temporary sandbox bundle (using pkg/ocibundle/native) is successful for OCI URI image sources (e.g. docker://...)
A selection of small fixes accomplishes this...
* Ensure platform is set in the transport options used during fallback.
* Use a new launcher instance for fallback Exec, as launcher has some state.
* Correctly set the image config for native bundles.
Also:
* Remove unused imgcache handle in actions code.
* Remove unused manifest obtained in native bundle code.
2- If a user asked to run an OCI-SIF file directly, do not fall-back. We don't currently have any code to create a tmp-sandbox rootfs out of an OCI-SIF file.
Additionally, fix the `ocibundle.Delete` function so that it will delete a partial bundle (that has not been fully …
> fix: oci: fallback to tmp-sandbox issues

- CHANGELOG.md
- cmd/internal/cli/actions.go
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- pkg/ocibundle/native/bundle_linux.go
- pkg/ocibundle/native/bundle_linux_test.go
- pkg/ocibundle/tools/oci.go
Cherry pick #3102 
1 - When FUSE mount fails, ensure fallback to a temporary sandbox bundle (using pkg/ocibundle/native) is successful for OCI URI image sources (e.g. docker://...)
A selection of small fixes accomplishes this...
* Ensure platform is set in the transport options used during fallback.
* Use a new launcher instance for fallback Exec, as launcher has some state.
* Correctly set the image config for native bundles.
Also:
* Remove unused imgcache handle in actions code.
* Remove unused manifest obtained in native bundle code.
2- If a user asked to run an OCI-SIF file directly, do not fall-back. We don't currently have any code to create a tmp-sandbox rootfs out of an OCI-SIF file.
Additionally, fix the `ocibundle.Delete` function so that it will delete a partial bundle (that …
> fix: oci: fallback to tmp-sandbox issues (release-4.1)

- .circleci/config.yml
Update CI to use the Ubuntu 24.04 VM image.
This requires adding an apparmor configuration file to permit use of unprivileged user namespaces. …
> chore: ci: bump VM to Ubuntu 24.04 image

- e2e/actions/actions.go
- e2e/actions/oci.go
- e2e/build/build.go
- e2e/build/regressions.go
- e2e/suite.go
e2e.Privileged returns a function that must be called with `(t)`. Some instances were not calling the privileged function. Fix these.
- Fixes #3103 …
> e2e: fix: ensure e2e.Privileged funcs are called

- e2e/overlay/overlay.go
- go.mod
- go.sum
- internal/app/singularity/overlay_create.go
- internal/pkg/ocisif/overlay.go
- internal/pkg/ocisif/overlay_test.go
Support `singularity overlay create` for OCI-SIF images.
An extfs overlay file is created, and then appended to the image encapsulated in the OCI-SIF, as an additional layer.
- Fixes #2867  …
> feat: singularity overlay create for OCI-SIF

- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/oci_overlay.go
After #3092 OCI-SIF images cannot be executed from a relative path.
Correctly use an absolute path in `imageOverlaySet()`, and add an e2e test.
- Fixes #3129 …
> fix: ensure OCI-SIF image can be executed from rel path

- CHANGELOG.md
- cmd/internal/cli/action_flags.go
- cmd/internal/cli/instance_actions_linux.go
- cmd/internal/cli/instance_linux.go
- docs/content.go
- e2e/instance/instance.go
- internal/pkg/runtime/launcher/launcher.go
- internal/pkg/runtime/launcher/launcher_test.go
Cherry-pick and adapt Apptainer PR: https://github.com/apptainer/apptainer/pull/1401
Added a new subcommand called `run` to the `instance` command group. This command will behave in the same manner as the `start` command, but it will run the runscript instead of the startscript. This will help with OCI container compatability since OCI containers have no concept of a startscript.
- Fixes #3083
> Cherry-pick and adapt Apptainer PR: https://github.com/apptainer/apptainer/pull/1401

- CHANGELOG.md
- cmd/internal/cli/overlay.go
- cmd/internal/cli/overlay_seal.go
- docs/content.go
- e2e/overlay/overlay.go
- internal/pkg/ocisif/overlay.go
- internal/pkg/ocisif/overlay_test.go
Add a `singularity overlay seal` command, which will convert an ext3 writable overlay into a read-only squashfs layer, 'sealing' the image and making changes stored in the overlay permanent.
- Fixes #2870
- Based this PR against the appropriate branch according …
> feat: OCI-SIF overlay seal

- cmd/internal/cli/push.go
- e2e/push/push.go
- internal/pkg/client/ocisif/ocisif.go
When pushing an OCI-SIF to an OCI registry:
* If the image contains an overlay, and we are pushing without an explicit --layer-format, then synchronize the overlay digest and push it as an ext3 layer.
* If the image contains an overlay, and we are pushing with the explicit 'squashfs' or 'tar' layer format, refuse to push. Instruct the user to seal the overlay before pushing.
- Fixes #2871 
- Fixes #3119 …
> feat: basic overlay handling on OCI-SIF push

- e2e/pull/pull.go
- internal/pkg/ocisif/imagewriter.go
When we are pulling an OCI image to an OCI-SIF then by default we squash the image layers down to a single layer for the OCI-SIF file.
This doesn't make sense when the last layer is an overlay - users will generally expect an image pushed with a writable overlay remains writable when pulled.
When pulling to OCI-SIF without `--keep-layers` squash all the squashfs layers, but preserve a separate final overlay layer.
- Fixes #3135
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTIN …
> feat: pull OCI-SIF with overlay, without --keep-layers

- CHANGELOG.md
- CONTRIBUTORS.md
- e2e/build/build.go
- e2e/build/regressions.go
- internal/pkg/build/sources/conveyorPacker_local.go
- internal/pkg/build/sources/conveyorPacker_local_test.go
A SquashFS image might contain directory symlinks such as `/var/tmp -> /tmp`. Before extraction a base environment is created (`makeBaseEnv`) by pre-creating some directories. Among them `/var/tmp`. Although unsquashfs is called with `-force` it fails to replace that by the symlink in the image as it removes only directories.
As per suggestion from @dtrudg the base environment causing the trouble is created after the extraction as done for e.g. OCI images.
- Fixes #3084
> Fix SquashFS extraction when it contains directory symlinks

- CHANGELOG.md
- CONTRIBUTORS.md
- e2e/build/build.go
- e2e/build/regressions.go
- internal/pkg/build/sources/conveyorPacker_local.go
- internal/pkg/build/sources/conveyorPacker_local_test.go
Backport #3151 
A SquashFS image might contain directory symlinks such as `/var/tmp -> /tmp`. Before extraction a base environment is created (`makeBaseEnv`) by pre-creating some directories. Among them `/var/tmp`. Although unsquashfs is called with `-force` it fails to replace that by the symlink in the image as it removes only directories.
As per suggestion from @dtrudg the base environment causing the trouble is created after the extraction as done for e.g. OCI images.
> Fix SquashFS extraction when it contains directory symlinks (release 4.1)

- CHANGELOG.md
- e2e/docker/docker.go
- internal/pkg/client/library/push.go
- internal/pkg/client/net/pull.go
- internal/pkg/client/oci/nativesif.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/client/oras/pull.go
- internal/pkg/client/shub/pull.go
- internal/pkg/ociimage/fetch.go
- internal/pkg/ocisif/overlay.go
- internal/pkg/ocisif/overlay_test.go
- internal/pkg/ocisif/util.go
- internal/pkg/util/machine/machine.go
Since 4.x we have had `--platform` / `--arch` support on pull from OCI sources. The `--platform` defaults to the host native platform.
In native mode, we were entirely relying on ggcr code to apply filtering / limits by platform. ggcr only does this when handling an image via an image index, not a manifest directly. Therefore, it was possible to pull images (that do not have an image index), with an architecture not expected.
In OCI-Mode a platform check prevented this, but occured very late... after layers were copied.
Move the main platform checks in to the `ociimage.LocalImage` / `ociimage.LocalImageLayout` functions, so that they are as early as possible (before layers are retrieved), and function the same in native and OCI mode.
When an image is retrieved from the cache - because the …
> fix: enforce --platform on pull for all OCI images

- internal/pkg/ocisif/overlay.go
- internal/pkg/util/fs/squashfs/mksquashfs_singularity.go
- internal/pkg/util/fs/squashfs/mksquashfs_singularity_test.go
**fix: seal overlay from upper/ dir in extfs**
The `overlay seal` command was incorrectly taking the whole of the extfs filesystem embedded in an OCI-SIF, and  converting it into a squashfs layer.
The changes made to the image are inside an `upper/` directory. Create the squashfs layer from this. Do not include the `work/` directory.
**fix: remove fuse-overlayfs .wh..opq in overlay seal**
fuse-overlayfs creates a dangling whiteout file within opaque directories. This takes the form of a `.wh..opq` 0:0 character device.
A `.wh..opq` file is not a valid AUFS whiteout / opaque marker. The real AUFS opaque marker is `.wh..wh..opq`.
A 0:0 character device is an OverlayFS whiteout indication, in this case that a file called `.wh..opq` should be white-outed. However, that file does not really …
> fix: overlay seal upper dir and fuse-overlayfs .wh..opq issue

- .circleci/config.yml
- .github/dependabot.yml
- CHANGELOG.md
- INSTALL.md
Follow release procedure for 4.2.0-rc.1
* Bump Go version in CI to latest.
* Add branch to dependabot config.
* Update .MD files.
> chore: 4.2.0-rc.1 docs / CI changes

- CHANGELOG.md
- e2e/docker/docker.go
- internal/pkg/client/library/push.go
- internal/pkg/client/net/pull.go
- internal/pkg/client/oci/nativesif.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/client/oras/pull.go
- internal/pkg/client/shub/pull.go
- internal/pkg/ociimage/fetch.go
- internal/pkg/ocisif/util.go
- internal/pkg/util/machine/machine.go
Pick #3159
Since 4.x we have had `--platform` / `--arch` support on pull from OCI sources. The `--platform` defaults to the host native platform.
In native mode, we were entirely relying on ggcr code to apply filtering / limits by platform. ggcr only does this when handling an image via an image index, not a manifest directly. Therefore, it was possible for a pull images (that do not have an image index), with an architecture not expected.
In OCI-Mode a platform check prevented this, but occured very late... after layers were copied.
Move the main platform checks in to the `ociimage.LocalImage` / `ociimage.LocalImageLayout` functions, so that they are as early as possible (before layers are retrieved), and function the same in native and OCI mode.
When an image is retrieved from the cache …
> fix: enforce --platform for all OCI images (release-4.1)

- scripts/update-license-dependencies.sh
If the go toolchain is downloaded due to installed version vs go.mod then we need to set GOROOT for go-licenses to run correctly.
See: https://github.com/google/go-licenses/issues/149 …
> fix: run go-licenses correctly with downloaded go

- scripts/update-license-dependencies.sh
Pick #3265
If the go toolchain is downloaded due to installed version vs go.mod then we need to set GOROOT for go-licenses to run correctly.
See: https://github.com/google/go-licenses/issues/149 …
> fix: run go-licenses correctly with downloaded go (release-4.2)

- CHANGELOG.md
- CONTRIBUTORS.md
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
Pick https://github.com/apptainer/apptainer/pull/1848
Fixes an empty shell field in the user's `/etc/passwd` entry in native mode. …
> fix: pick apptainer 1848 (fix empty shell field)

- CHANGELOG.md
- CONTRIBUTORS.md
- e2e/actions/actions.go
- e2e/actions/regressions.go
- internal/pkg/runtime/engine/singularity/prepare_linux.go
Pick https://github.com/apptainer/apptainer/pull/1848
Fixes an empty shell field in the user's `/etc/passwd` entry in native mode. …
> fix: pick apptainer 1848 (fix empty shell field) (release-4.2)

- .circleci/config.yml
- CHANGELOG.md
- e2e/build/regressions.go
- internal/pkg/build/sources/base_environment.go
- internal/pkg/build/sources/base_environment_test.go
- internal/pkg/build/sources/conveyorPacker_arch.go
- internal/pkg/build/sources/conveyorPacker_busybox.go
- internal/pkg/build/sources/conveyorPacker_debootstrap.go
- internal/pkg/build/sources/conveyorPacker_library.go
- internal/pkg/build/sources/conveyorPacker_local.go
- internal/pkg/build/sources/conveyorPacker_oci.go
- internal/pkg/build/sources/conveyorPacker_oras.go
- internal/pkg/build/sources/conveyorPacker_scratch.go
- internal/pkg/build/sources/conveyorPacker_shub.go
- internal/pkg/build/sources/conveyorPacker_yum.go
- internal/pkg/build/sources/conveyorPacker_zypper.go
Pick #3360 
When building from a local image, we need to insert the base environment (default runscripts etc), into the rootfs after extracting it. This is because of an issue with `unsquashfs` that causes it to fail in the presence of certain symlinks (#3151).
We also want any runscript etc. in the source image to be preservered, and not replaced with defaults.
Modify the base environment insertion to accept a bool controlling whether it overwrites any existing files. For the local image case, where we insert the baseenv after extraction, do not overwrite. In all other cases keep existing behaviour by setting overwrite to true.
- Fixes #3353 …
> fix: ensure source baseenv not overwritten in local build (release-4.2)

- .github/dependabot.yml
Generate dependabot version updates weekly, on a Friday at 7 & 8am UTC.
Setup an intial grouping:
- All moby/* and docker/* updates together, as these are generally quite interdependent, and often require adapting some code.
- All containerd/* updates together, as these can be interdependent and require more review / adaptation.
- All opencontainers/* updates together, so OCI spec changes are not wrapped up with general minor updates.
-  All other minor / patch version updates together.
Any security updates will still raise a separate PR.
Any major updates (outside of moby/containerd/opencontainers) will still raise a separate PR.
> chore: dependabot grouping / schedule

- e2e/actions/oci.go
Newest alpine:3.18 image has WorkingDir="/" explicitly set, causing this test to fail.
Use the non-OCI-SIF test image, which results in an unset WorkingDir as before. This will remain the case as non-OCI-SIF Singularity images don't have a way of setting a working dir. …
> e2e: fix: use image with no WorkingDir for actionOCIHomeCwdPasswd (4.2)

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/oci_linux.go
On systems where `pam-systemd` is disabled, or there is other configuration preventing the creation of a /run/user/<uid> directory, we need to use a different location for the OCI runtime state.
Change the runtimeStateDir handling to:
* Use XDG_RUNTIME_DIR if set.
* Otherwise, try to use /run/user/<uid>.
* Otherwise, use a location under $TMPDIR.
- Fixes #3393
- Added tests to validate this PR, linted with `make check` …
> feat: accommodate missing /run/user dir in OCI mode

- CHANGELOG.md
- internal/pkg/build/buildkit/client/client.go
The buildkit code that we call as a dependency uses XDG_RUNTIME_DIR in multiple locations, so we cannot handle it being unset.
Add a specific error for rootless build --oci with XDG_RUNTIME_DIR unset, so it is clear that this env var must be set.
I don't think we should be setting XDG_RUNTIME_DIR ourselves, to a tmpdir we create. There is a strong assumption that this value is a genuine session specific directory that is configured by systemd, or by the user manually.
- Fixes #3410  …
> fix: improve build --oci error for missing XDG_RUNTIME_DIR

- CHANGELOG.md
- internal/pkg/runtime/engine/singularity/cleanup_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/util/priv/priv_linux.go
- internal/pkg/util/priv/priv_linux_test.go
- pkg/network/network_linux.go
Newer versions of the `iptables` command use a real vs effective uid check whether they are being called from a setuid script, and exit if that's the case.
This check was added because iptables can call out to binaries / libraries on `PATH` / `LD_LIBRARY_PATH`, and these are generally under control of the user - allowing privilege escalation attackes.
Singularity sanitizes the environment before running CNI plugins, which will call `iptables`, so we can set both real and effective uid to 0 to avoid the error.
While we are here, make `PATH` sanitization the default in the network code, rather than relying on the caller applying it.
- Fixes #3318 …
> fix: CNI: avoid error with iptables setuid check

- CHANGELOG.md
- internal/pkg/runtime/engine/singularity/cleanup_linux.go
- internal/pkg/runtime/engine/singularity/container_linux.go
- internal/pkg/util/priv/priv_linux.go
- internal/pkg/util/priv/priv_linux_test.go
- pkg/network/network_linux.go
Pick #3444
Newer versions of the `iptables` command use a real vs effective uid check whether they are being called from a setuid script, and exit if that's the case.
This check was added because iptables can call out to binaries / libraries on `PATH` / `LD_LIBRARY_PATH`, and these are generally under control of the user - allowing privilege escalation attackes.
Singularity sanitizes the environment before running CNI plugins, which will call `iptables`, so we can set both real and effective uid to 0 to avoid the error.
While we are here, make `PATH` sanitization the default in the network code, rather than relying on the caller applying it.
- Fixes #3318 
- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the …
> fix: CNI: avoid error with iptables setuid check (release-4.2)

- .circleci/config.yml
- CHANGELOG.md
- INSTALL.md
- mconfig
> chore: prepare 4.2.2 release

- .circleci/config.yml
Add centos stream 10 to the CI matrix for RPM builds.
This will be replaced with a non-stream EL distribution once RHEL 10 releases.
CI portion of #3432
> ci: Add centos stream 10 RPM builds

- .circleci/config.yml
There seem to be some issues with rpmbuild failures on some stream 10 docker hub updates, suggesting stream 10 (or at least the Docker image) isn't yet stable enough.
Move the stream 10 rpmbuild to a separate workflow named `preview` that can be excluded from branch protection rules so it doesn't block PR merge.
> ci: split stream 10 rpm build to a 'preview' workflow

- e2e/actions/actions.go
- e2e/actions/oci.go
Allow the user fullname to for root to be anything. It is usually `root`, but on EL10 it's now `Super User`.
- Fixes #3455
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CON …
> e2e: fix: relax CustomHomePreservesRootShell regex

- CHANGELOG.md
- internal/pkg/runtime/launcher/oci/oci_linux.go
For `singularity oci` commands (not `--oci` mode), a conmon/singularity state dir is required. The path was erroneously being computed based on the user's Name, instead of Username.
This shows as a test failure on EL10 where the Name != Username for `root / Super User`, as opposed to other distributions that use `root / root`.
- Fixes #3456  …
> fix: use username, not name for conmon/singularity stateDir

- internal/pkg/test/tool/require/require.go
- pkg/network/network_linux_test.go
Network e2e tests were failing to run due to an invalid container name (with newer CNI plugins / distro) in the `require.Network(t)` function.
Fix the container name so that the requirement function passes, and the tests will run properly.
While we are in this code, ensure some other network tests run with named subtests for convenience when reviewing the test logs.
- Fixes #3433 …
> fix: ensure network e2e tests run

- .circleci/config.yml
- .golangci.yml
- .vscode/settings.json
- CHANGELOG.md
- CONTRIBUTORS.md
- INSTALL.md
- LICENSE_THIRD_PARTY.md
- dist/rpm/singularity-ce.spec.in
- internal/pkg/fakeroot/fakeroot.go
- internal/pkg/fakeroot/idtools_supported.go
- internal/pkg/fakeroot/idtools_unsupported.go
- mconfig
- mlocal/checks/project-post.chk
- mlocal/frags/go_libsubid_opts.mk
Pick and adapt https://github.com/apptainer/apptainer/pull/2433
**Original description:**
This commit adds support for remote access to /etc/subuid and /etc/subgid mappings from ldap services using libsubid. Requires shadow-utils + libsubid.
Code ported from podman / container storage.
**Additional adaptation:**
fakeroot: don't use libsubid in config fakeroot operations
When reading or modifying an `/etc/sub[ug]id` file, via the `config fakeroot` commands, don't consider libsubid results.
Prevents e.g. `config fakeroot --remove user` giving a confusing failure when `user` is not in the file, but present in results from libsubid.
Only use `libsubid` for the `fakeroot.GetIDRange` function, which is used by the runtime engines to discover applicable ID mapping ranges.
Note - no further …
> pick: Add initial support for libsubid

- CHANGELOG.md
- cmd/internal/cli/push.go
- e2e/push/push.go
- internal/pkg/client/oci/push.go
- internal/pkg/client/ocisif/ocisif.go
When the `--with-cosign` flag is specified, `singularity push` will now push cosign signatures from an OCI-SIF to a remote OCI registry.
Signatures cannot be pushed if the push operation would mutate the image. …
> feat: push --with-cosign

- CHANGELOG.md
- cmd/internal/cli/pull.go
- e2e/pull/pull.go
- internal/pkg/client/library/pull.go
- internal/pkg/client/oci/pull.go
- internal/pkg/client/ocisif/ocisif.go
- internal/pkg/ociimage/sourcesink.go
When using `singularity pull --oci` to pull an image from an OCI registry (or registry backed library) into an OCI-SIF it is now possible to pull any cosign signatures associated with the image using a new `--with-cosign` flag.
Pulling cosign signatures requires that the image in the registry is in a format where it will not be mutated as it is pulled into the OCI-SIF. Any mutations change the image manifest, which would invalidate the signatures. Therefore:
* The image must have SquashFS layers - i.e. it was created and signed with Singularity, and is not a standard tar layer Docker / OCI image.
* The '--keep-layers' flag must be used if the image has more than one layer.
There are important limitations to signature pulling:
* If an image & signatures are updated at the registry during a …
> feat: pull -oci --with-cosign support

- CHANGELOG.md
- cmd/internal/cli/key.go
- cmd/internal/cli/key_generatecosignkeypair.go
- docs/content.go
- e2e/key/key.go
Adds a new subcommand that will generate a key-pair suitable for signing OCI-SIF images with a cosign-compatible signature.
Intentionally uses output prefix flag matching `cosign generate-key-pair`.
- Fixes #3489 …
> feat: key generate-cosign-key-pair

- CHANGELOG.md
- mlocal/frags/go_normal_opts.mk
Pick of https://github.com/apptainer/apptainer/pull/2699
This is achieved using the linker option `-B gobuildid` See: https://pkg.go.dev/cmd/link.
This way binaries will get unique build IDs and the build will be reproducible as binaries built from identical sources will have the same build ID.
> build: Derive the GNU build ID from the Go one

- CHANGELOG.md
- internal/pkg/build/sources/conveyorPacker_oci.go
Pick of https://github.com/apptainer/apptainer/issues/2582
> Ignore invalid environment variables when pulling oci/docker containers.

- CHANGELOG.md
- e2e/cgroups/cgroups.go
- internal/pkg/cgroups/util.go
- internal/pkg/runtime/launcher/oci/launcher_linux.go
- internal/pkg/runtime/launcher/oci/launcher_linux_test.go
- internal/pkg/runtime/launcher/oci/mounts_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux.go
- internal/pkg/runtime/launcher/oci/spec_linux_test.go
In OCI-Mode, try to create a cgroup for the container even when no resource limits have been requested.
On a cgroups v2 system, with functioning cgroups management, create a cgroups namespace for OCI-Mode containers, and perform an explicit `/sys/fs/cgroups` mount. The mount is `ro` by default, or `rw` when `--keep-privs` is specified.
This fixes issues with nested container execution in OCI-Mode, and improves compatibility with other OCI runtimes.
Verified manually on cgroups v2 (Fedora/Ubuntu 24.04) and checked for regression on cgroups v1 (RHEL8).
- Fixes #3538 …
> oci: cgroupsv2 namespace / mount handling

- CHANGELOG.md
- cmd/starter/c/include/starter.h
- internal/pkg/runtime/engine/config/starter/starter_linux.go
Replace use of a custom `bool` enum with the C `_Bool` aliased to `bool` via `<stdbool.h>` etc.
Fixes issues with `-std=c23` where `bool / true / false` are now defined by the language.
- Fixes #3561 …
> fix: use built-in C boolean type in starter (release-4.2)

- .circleci/config.yml
- CHANGELOG.md
- INSTALL.md
- e2e/testdata/Dockerfile.nested
Bump go version.
Bump squashfuse to 0.6.0.
> chore: prep 4.3.1 release

- e2e/actions/actions.go
- e2e/actions/oci.go
Previous fix in #3740 was not correct.
The EL10 "Super User" value has a space in it, therefore `\w*` is not a complete match.
- Fixes #3715 …
> e2e: fix: accommodate "Super User" in e2e CustomHomePreservesRootShell

- e2e/actions/oci.go
Filesystem specific options not valid on binds, and checked with runc 1.2+.
Remove `users` option from binds in `actionOciCdi` e2e test.
Fixes #3720
> e2e: fs options not valid on binds (actionOciCdi)

- CHANGELOG.md
- internal/pkg/client/oras/image.go
Use OCI Manifest Schema 1 for ORAS pushes. Addresses errors pushing to Quay, which applies a `must be` restriction for the `config.mediaType` value on Docker Manifest Schema 2 (spec has a looser `should generally be`).
Fixes #3664
> oras: use OCI Manifest Schema 1 (release-4.3)

- examples/fedora-amd64/Singularity
- examples/fedora-arm64/Singularity
Fedora 40 is no longer on the main mirrors - it has been archived. Use current 42.
> e2e: fix: use Fedora version currently on mirrors

- examples/fedora-amd64/Singularity
- examples/fedora-arm64/Singularity
Fedora 40 is no longer on the main mirrors - it has been archived. Use current 42.
> e2e: fix: use Fedora version currently on mirrors (release-4.3)
